"""
Canonical Diagnostic Center and Radiology Services Catalog.
Generated from services/DIAGNOSTIC CENTER SCOPE.xls.
MRI (33), CT Scans (31), General Scans (11), Blood Tests (CBC and Cultures), plus base radiography.
Total: 84 services.
"""
from typing import List, Dict, Any

CANONICAL_RADIOLOGY_SERVICES: List[Dict[str, Any]] = [{'id': 'cat-xray-single',
  'name': 'X-Ray (Single View)',
  'slug': 'x-ray-single',
  'category': 'imaging',
  'sub_category': 'xray',
  'synonyms': ['X-Ray Single',
               'X-Ray (Single)',
               'Plain Radiography 1 View',
               'Chest X-Ray Single View',
               'Digital X-Ray Single'],
  'typical_turnaround_hours': 4,
  'mrp': 450.0,
  'is_active': True,
  'preparation': 'Remove metallic jewelry, body piercings, and belts prior to examination.',
  'description': 'High-resolution digital radiography single projection for bone, joint, or pulmonary diagnosis.'},
 {'id': 'cat-xray-double',
  'name': 'X-Ray (Double View)',
  'slug': 'x-ray-double',
  'category': 'imaging',
  'sub_category': 'xray',
  'synonyms': ['X-Ray Double', 'X-Ray (Double)', 'X-Ray 2 Views', 'AP and Lateral View', 'Chest X-Ray PA and Lateral'],
  'typical_turnaround_hours': 4,
  'mrp': 750.0,
  'is_active': True,
  'preparation': 'Remove metallic jewelry, body piercings, and belts prior to examination.',
  'description': 'Two orthogonal digital projections (Anteroposterior and Lateral) for anatomical alignment and '
                 'fracture evaluation.'},
 {'id': 'cat-spine-xray-single',
  'name': 'Spine X-Ray (Single View)',
  'slug': 'spine-x-ray-single',
  'category': 'imaging',
  'sub_category': 'xray',
  'synonyms': ['Spine X-Ray Single',
               'Spine X-Ray (Single)',
               'Cervical Spine X-Ray',
               'Lumbar Spine X-Ray Single',
               'Thoracic Spine X-Ray'],
  'typical_turnaround_hours': 4,
  'mrp': 550.0,
  'is_active': True,
  'preparation': 'Wear loose, comfortable cotton clothing without metal zippers.',
  'description': 'Targeted digital spinal radiography evaluating vertebral alignment, disc heights, and curvature.'},
 {'id': 'cat-spine-xray-double',
  'name': 'Spine X-Ray (Double View)',
  'slug': 'spine-x-ray-double',
  'category': 'imaging',
  'sub_category': 'xray',
  'synonyms': ['Spine X-Ray Double',
               'Spine X-Ray (Double)',
               'Spine AP and Lateral',
               'Lumbosacral Spine 2 Views',
               'Cervical Spine AP Lat'],
  'typical_turnaround_hours': 4,
  'mrp': 950.0,
  'is_active': True,
  'preparation': 'Wear loose, comfortable cotton clothing without metal zippers.',
  'description': 'Dual-view AP and Lateral spinal imaging diagnosing spondylosis, scoliosis, and degenerative disc '
                 'diseases.'},
 {'id': 'cat-ecg-12lead',
  'name': 'ECG (12-Lead Resting)',
  'slug': 'ecg-12-lead',
  'category': 'imaging',
  'sub_category': 'ecg_echo',
  'synonyms': ['ECG', 'Electrocardiogram', '12 Lead ECG', 'Resting ECG', 'Cardiogram'],
  'typical_turnaround_hours': 2,
  'mrp': 350.0,
  'is_active': True,
  'preparation': 'Avoid strenuous exercise and caffeinated beverages 30 minutes before testing.',
  'description': 'Certified 12-lead electrocardiographic tracing evaluating cardiac electrical conduction and rhythm.'},
 {'id': 'cat-pft-spirometry',
  'name': 'Pulmonary Function Test (PFT)',
  'slug': 'pft-spirometry',
  'category': 'imaging',
  'sub_category': 'pft',
  'synonyms': ['PFT', 'Pulmonary Function Test', 'Spirometry', 'Lung Function Test', 'FVC Spirometry'],
  'typical_turnaround_hours': 4,
  'mrp': 850.0,
  'is_active': True,
  'preparation': 'Do not take short-acting bronchodilator inhalers for 4 hours before test unless advised by doctor.',
  'description': 'Comprehensive spirometric evaluation of forced vital capacity (FVC), FEV1, and airway resistance.'},
 {'id': 'cat-audiometry',
  'name': 'Audiometry (Hearing Evaluation)',
  'slug': 'audiometry-hearing-test',
  'category': 'imaging',
  'sub_category': 'audiometry',
  'synonyms': ['Audiometry', 'PTA', 'Pure Tone Audiometry', 'Hearing Test', 'Audiogram', 'Air and Bone Conduction'],
  'typical_turnaround_hours': 3,
  'mrp': 700.0,
  'is_active': True,
  'preparation': 'Avoid exposure to loud environments or headphones for 14 hours prior to evaluation.',
  'description': 'Certified pure-tone audiometric threshold testing assessing air and bone conduction hearing '
                 'profiles.'},
 {'id': 'cat-mri-brain-plain',
  'name': 'MRI BRAIN PLAIN',
  'slug': 'mri-brain-plain',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI BRAIN PLAIN', 'Scan MRI BRAIN PLAIN', 'MRI BRAIN PLAIN Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 5000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI BRAIN PLAIN) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-brain-plain-with-contrast',
  'name': 'MRI BRAIN PLAIN WITH CONTRAST',
  'slug': 'mri-brain-plain-with-contrast',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI BRAIN PLAIN WITH CONTRAST',
               'Scan MRI BRAIN PLAIN WITH CONTRAST',
               'MRI BRAIN PLAIN WITH CONTRAST Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI BRAIN PLAIN WITH CONTRAST) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-spine-single-region',
  'name': 'MRI SPINE SINGLE REGION',
  'slug': 'mri-spine-single-region',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI SPINE SINGLE REGION', 'Scan MRI SPINE SINGLE REGION', 'MRI SPINE SINGLE REGION Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 5000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI SPINE SINGLE REGION) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-dl-spine',
  'name': 'MRI DL SPINE',
  'slug': 'mri-dl-spine',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI DL SPINE', 'Scan MRI DL SPINE', 'MRI DL SPINE Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 6000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI DL SPINE) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-cspine-with-cv-junction',
  'name': 'MRI CSPINE WITH CV JUNCTION',
  'slug': 'mri-cspine-with-cv-junction',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI CSPINE WITH CV JUNCTION', 'Scan MRI CSPINE WITH CV JUNCTION', 'MRI CSPINE WITH CV JUNCTION Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 6500.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI CSPINE WITH CV JUNCTION) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-cervical-spine-with-brachial-plexus',
  'name': 'CERVICAL SPINE WITH BRACHIAL PLEXUS',
  'slug': 'cervical-spine-with-brachial-plexus',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['CERVICAL SPINE WITH BRACHIAL PLEXUS',
               'Scan CERVICAL SPINE WITH BRACHIAL PLEXUS',
               'CERVICAL SPINE WITH BRACHIAL PLEXUS Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 9500.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (CERVICAL SPINE WITH BRACHIAL PLEXUS) providing high-resolution '
                 'tissue visualization.'},
 {'id': 'cat-mri-abdomen',
  'name': 'MRI ABDOMEN',
  'slug': 'mri-abdomen',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI ABDOMEN', 'Scan MRI ABDOMEN', 'MRI ABDOMEN Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 7000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI ABDOMEN) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-pelvis',
  'name': 'MRI PELVIS',
  'slug': 'mri-pelvis',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI PELVIS', 'Scan MRI PELVIS', 'MRI PELVIS Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 7000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI PELVIS) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-brain-angiogram',
  'name': 'MRI BRAIN ANGIOGRAM',
  'slug': 'mri-brain-angiogram',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI BRAIN ANGIOGRAM', 'Scan MRI BRAIN ANGIOGRAM', 'MRI BRAIN ANGIOGRAM Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI BRAIN ANGIOGRAM) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-venogram-brain',
  'name': 'MRI VENOGRAM - Brain',
  'slug': 'mri-venogram-brain',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI VENOGRAM - Brain', 'Scan MRI VENOGRAM - Brain', 'MRI VENOGRAM - Brain Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI VENOGRAM - Brain) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-any-joint',
  'name': 'MRI ANY JOINT',
  'slug': 'mri-any-joint',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI ANY JOINT', 'Scan MRI ANY JOINT', 'MRI ANY JOINT Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 6000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI ANY JOINT) providing high-resolution tissue visualization.'},
 {'id': 'cat-only-contrast-charges',
  'name': 'ONLY CONTRAST CHARGES',
  'slug': 'only-contrast-charges',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['ONLY CONTRAST CHARGES', 'Scan ONLY CONTRAST CHARGES', 'ONLY CONTRAST CHARGES Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 3000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (ONLY CONTRAST CHARGES) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-neck',
  'name': 'MRI NECK',
  'slug': 'mri-neck',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI NECK', 'Scan MRI NECK', 'MRI NECK Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 6000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI NECK) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-renal-angio',
  'name': 'MRI RENAL ANGIO',
  'slug': 'mri-renal-angio',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI RENAL ANGIO', 'Scan MRI RENAL ANGIO', 'MRI RENAL ANGIO Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI RENAL ANGIO) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-brain-and-neck-angiogram',
  'name': 'MRI BRAIN AND NECK ANGIOGRAM',
  'slug': 'mri-brain-and-neck-angiogram',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI BRAIN AND NECK ANGIOGRAM',
               'Scan MRI BRAIN AND NECK ANGIOGRAM',
               'MRI BRAIN AND NECK ANGIOGRAM Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 9000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI BRAIN AND NECK ANGIOGRAM) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-fistulogram',
  'name': 'MRI FISTULOGRAM',
  'slug': 'mri-fistulogram',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI FISTULOGRAM', 'Scan MRI FISTULOGRAM', 'MRI FISTULOGRAM Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 6000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI FISTULOGRAM) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-orbits',
  'name': 'MRI ORBITS',
  'slug': 'mri-orbits',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI ORBITS', 'Scan MRI ORBITS', 'MRI ORBITS Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 5000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI ORBITS) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-pns',
  'name': 'MRI PNS',
  'slug': 'mri-pns',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI PNS', 'Scan MRI PNS', 'MRI PNS Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 6000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI PNS) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-peripheral-lower-limb-angiogram',
  'name': 'MRI PERIPHERAL LOWER LIMB ANGIOGRAM',
  'slug': 'mri-peripheral-lower-limb-angiogram',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI PERIPHERAL LOWER LIMB ANGIOGRAM',
               'Scan MRI PERIPHERAL LOWER LIMB ANGIOGRAM',
               'MRI PERIPHERAL LOWER LIMB ANGIOGRAM Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 11000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI PERIPHERAL LOWER LIMB ANGIOGRAM) providing high-resolution '
                 'tissue visualization.'},
 {'id': 'cat-mri-brain-with-orbits',
  'name': 'MRI BRAIN WITH ORBITS',
  'slug': 'mri-brain-with-orbits',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI BRAIN WITH ORBITS', 'Scan MRI BRAIN WITH ORBITS', 'MRI BRAIN WITH ORBITS Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 7000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI BRAIN WITH ORBITS) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-breast',
  'name': 'MRI BREAST',
  'slug': 'mri-breast',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI BREAST', 'Scan MRI BREAST', 'MRI BREAST Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 9000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI BREAST) providing high-resolution tissue visualization.'},
 {'id': 'cat-abrevation-breast-mri-for-screening',
  'name': 'ABREVATION BREAST MRI FOR SCREENING',
  'slug': 'abrevation-breast-mri-for-screening',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['ABREVATION BREAST MRI FOR SCREENING',
               'Scan ABREVATION BREAST MRI FOR SCREENING',
               'ABREVATION BREAST MRI FOR SCREENING Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (ABREVATION BREAST MRI FOR SCREENING) providing high-resolution '
                 'tissue visualization.'},
 {'id': 'cat-mri-breast-with-contrast',
  'name': 'MRI BREAST WITH CONTRAST',
  'slug': 'mri-breast-with-contrast',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI BREAST WITH CONTRAST', 'Scan MRI BREAST WITH CONTRAST', 'MRI BREAST WITH CONTRAST Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 9000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI BREAST WITH CONTRAST) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-cardiac',
  'name': 'MRI CARDIAC',
  'slug': 'mri-cardiac',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI CARDIAC', 'Scan MRI CARDIAC', 'MRI CARDIAC Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 15000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI CARDIAC) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-stroke-protocol',
  'name': 'MRI STROKE PROTOCOL',
  'slug': 'mri-stroke-protocol',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI STROKE PROTOCOL', 'Scan MRI STROKE PROTOCOL', 'MRI STROKE PROTOCOL Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI STROKE PROTOCOL) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-sella-with-contrast',
  'name': 'MRI SELLA WITH CONTRAST',
  'slug': 'mri-sella-with-contrast',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI SELLA WITH CONTRAST', 'Scan MRI SELLA WITH CONTRAST', 'MRI SELLA WITH CONTRAST Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI SELLA WITH CONTRAST) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mrcp',
  'name': 'MRCP',
  'slug': 'mrcp',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRCP', 'Scan MRCP', 'MRCP Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 7000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRCP) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-urogram',
  'name': 'MRI UROGRAM',
  'slug': 'mri-urogram',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI UROGRAM', 'Scan MRI UROGRAM', 'MRI UROGRAM Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 7000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI UROGRAM) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-prostate',
  'name': 'MRI PROSTATE',
  'slug': 'mri-prostate',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI PROSTATE', 'Scan MRI PROSTATE', 'MRI PROSTATE Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 9000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI PROSTATE) providing high-resolution tissue visualization.'},
 {'id': 'cat-mri-epilepsy-protocol',
  'name': 'MRI EPILEPSY PROTOCOL',
  'slug': 'mri-epilepsy-protocol',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI EPILEPSY PROTOCOL', 'Scan MRI EPILEPSY PROTOCOL', 'MRI EPILEPSY PROTOCOL Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI EPILEPSY PROTOCOL) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-dementia-protocol',
  'name': 'MRI DEMENTIA PROTOCOL',
  'slug': 'mri-dementia-protocol',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI DEMENTIA PROTOCOL', 'Scan MRI DEMENTIA PROTOCOL', 'MRI DEMENTIA PROTOCOL Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI DEMENTIA PROTOCOL) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-headache-protocol',
  'name': 'MRI HEADACHE PROTOCOL',
  'slug': 'mri-headache-protocol',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI HEADACHE PROTOCOL', 'Scan MRI HEADACHE PROTOCOL', 'MRI HEADACHE PROTOCOL Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI HEADACHE PROTOCOL) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-mri-defecography',
  'name': 'MRI DEFECOGRAPHY',
  'slug': 'mri-defecography',
  'category': 'imaging',
  'sub_category': 'mri',
  'synonyms': ['MRI DEFECOGRAPHY', 'Scan MRI DEFECOGRAPHY', 'MRI DEFECOGRAPHY Scan'],
  'typical_turnaround_hours': 12,
  'mrp': 10000.0,
  'is_active': True,
  'preparation': 'Remove all metallic objects, jewelry, and belts. Fasting 4 hours prior if contrast is advised.',
  'description': 'Advanced magnetic resonance imaging (MRI DEFECOGRAPHY) providing high-resolution tissue '
                 'visualization.'},
 {'id': 'cat-3-d-ct-any-region',
  'name': '3 D CT ANY REGION',
  'slug': '3-d-ct-any-region',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['3 D CT ANY REGION', 'Scan 3 D CT ANY REGION', '3 D CT ANY REGION Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 5000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (3 D CT ANY REGION) with high geometric accuracy.'},
 {'id': 'cat-3d-ct-skull',
  'name': '3D CT SKULL',
  'slug': '3d-ct-skull',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['3D CT SKULL', 'Scan 3D CT SKULL', '3D CT SKULL Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 5000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (3D CT SKULL) with high geometric accuracy.'},
 {'id': 'cat-ct-abdomen-plain',
  'name': 'CT ABDOMEN PLAIN',
  'slug': 'ct-abdomen-plain',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT ABDOMEN PLAIN', 'Scan CT ABDOMEN PLAIN', 'CT ABDOMEN PLAIN Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 4000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT ABDOMEN PLAIN) with high geometric accuracy.'},
 {'id': 'cat-ct-abdomen-plain-with-contrast',
  'name': 'CT ABDOMEN PLAIN WITH CONTRAST',
  'slug': 'ct-abdomen-plain-with-contrast',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT ABDOMEN PLAIN WITH CONTRAST',
               'Scan CT ABDOMEN PLAIN WITH CONTRAST',
               'CT ABDOMEN PLAIN WITH CONTRAST Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 6500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT ABDOMEN PLAIN WITH CONTRAST) with high geometric '
                 'accuracy.'},
 {'id': 'cat-ct-aortogram',
  'name': 'CT AORTOGRAM',
  'slug': 'ct-aortogram',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT AORTOGRAM', 'Scan CT AORTOGRAM', 'CT AORTOGRAM Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 8500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT AORTOGRAM) with high geometric accuracy.'},
 {'id': 'cat-ct-biopsy',
  'name': 'CT BIOPSY',
  'slug': 'ct-biopsy',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT BIOPSY', 'Scan CT BIOPSY', 'CT BIOPSY Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 9000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT BIOPSY) with high geometric accuracy.'},
 {'id': 'cat-ct-brain-plain',
  'name': 'CT BRAIN PLAIN',
  'slug': 'ct-brain-plain',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT BRAIN PLAIN', 'Scan CT BRAIN PLAIN', 'CT BRAIN PLAIN Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 2500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT BRAIN PLAIN) with high geometric accuracy.'},
 {'id': 'cat-ct-chest-plain',
  'name': 'CT CHEST PLAIN',
  'slug': 'ct-chest-plain',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT CHEST PLAIN', 'Scan CT CHEST PLAIN', 'CT CHEST PLAIN Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 4000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT CHEST PLAIN) with high geometric accuracy.'},
 {'id': 'cat-ct-chest-plain-with-contrast',
  'name': 'CT CHEST PLAIN WITH CONTRAST',
  'slug': 'ct-chest-plain-with-contrast',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT CHEST PLAIN WITH CONTRAST',
               'Scan CT CHEST PLAIN WITH CONTRAST',
               'CT CHEST PLAIN WITH CONTRAST Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 6500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT CHEST PLAIN WITH CONTRAST) with high geometric '
                 'accuracy.'},
 {'id': 'cat-ct-entroclysis',
  'name': 'CT ENTROCLYSIS',
  'slug': 'ct-entroclysis',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT ENTROCLYSIS', 'Scan CT ENTROCLYSIS', 'CT ENTROCLYSIS Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 7000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT ENTROCLYSIS) with high geometric accuracy.'},
 {'id': 'cat-ct-facial-bones',
  'name': 'CT Facial Bones',
  'slug': 'ct-facial-bones',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT Facial Bones', 'Scan CT Facial Bones', 'CT Facial Bones Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 5000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT Facial Bones) with high geometric accuracy.'},
 {'id': 'cat-ct-fnac',
  'name': 'CT FNAC',
  'slug': 'ct-fnac',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT FNAC', 'Scan CT FNAC', 'CT FNAC Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT FNAC) with high geometric accuracy.'},
 {'id': 'cat-ct-guided-pigtail-catheter',
  'name': 'CT GUIDED PIGTAIL CATHETER',
  'slug': 'ct-guided-pigtail-catheter',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT GUIDED PIGTAIL CATHETER', 'Scan CT GUIDED PIGTAIL CATHETER', 'CT GUIDED PIGTAIL CATHETER Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 8600.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT GUIDED PIGTAIL CATHETER) with high geometric '
                 'accuracy.'},
 {'id': 'cat-ct-kub',
  'name': 'CT KUB',
  'slug': 'ct-kub',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT KUB', 'Scan CT KUB', 'CT KUB Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 4000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT KUB) with high geometric accuracy.'},
 {'id': 'cat-ct-mastoids',
  'name': 'CT MASTOIDS',
  'slug': 'ct-mastoids',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT MASTOIDS', 'Scan CT MASTOIDS', 'CT MASTOIDS Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 4000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT MASTOIDS) with high geometric accuracy.'},
 {'id': 'cat-ct-neck',
  'name': 'CT NECK',
  'slug': 'ct-neck',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT NECK', 'Scan CT NECK', 'CT NECK Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 4500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT NECK) with high geometric accuracy.'},
 {'id': 'cat-ct-neck-plain-with-contrast',
  'name': 'CT NECK PLAIN WITH CONTRAST',
  'slug': 'ct-neck-plain-with-contrast',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT NECK PLAIN WITH CONTRAST', 'Scan CT NECK PLAIN WITH CONTRAST', 'CT NECK PLAIN WITH CONTRAST Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 5500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT NECK PLAIN WITH CONTRAST) with high geometric '
                 'accuracy.'},
 {'id': 'cat-ct-neck-vessel-angio',
  'name': 'CT NECK VESSEL ANGIO',
  'slug': 'ct-neck-vessel-angio',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT NECK VESSEL ANGIO', 'Scan CT NECK VESSEL ANGIO', 'CT NECK VESSEL ANGIO Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 6500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT NECK VESSEL ANGIO) with high geometric accuracy.'},
 {'id': 'cat-ct-orbits',
  'name': 'CT ORBITS',
  'slug': 'ct-orbits',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT ORBITS', 'Scan CT ORBITS', 'CT ORBITS Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 3700.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT ORBITS) with high geometric accuracy.'},
 {'id': 'cat-ct-pcnl',
  'name': 'CT PCNL',
  'slug': 'ct-pcnl',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT PCNL', 'Scan CT PCNL', 'CT PCNL Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 8500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT PCNL) with high geometric accuracy.'},
 {'id': 'cat-ct-pelvis-with-hip-joints',
  'name': 'CT PELVIS WITH HIP JOINTS',
  'slug': 'ct-pelvis-with-hip-joints',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT PELVIS WITH HIP JOINTS', 'Scan CT PELVIS WITH HIP JOINTS', 'CT PELVIS WITH HIP JOINTS Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 5000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT PELVIS WITH HIP JOINTS) with high geometric '
                 'accuracy.'},
 {'id': 'cat-ct-pns-single-film',
  'name': 'CT PNS (Single film)',
  'slug': 'ct-pns-single-film',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT PNS (Single film)', 'Scan CT PNS (Single film)', 'CT PNS (Single film) Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 3000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT PNS (Single film)) with high geometric accuracy.'},
 {'id': 'cat-ct-pns-two-films',
  'name': 'CT PNS (Two  films)',
  'slug': 'ct-pns-two-films',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT PNS (Two  films)', 'Scan CT PNS (Two  films)', 'CT PNS (Two  films) Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 3500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT PNS (Two  films)) with high geometric accuracy.'},
 {'id': 'cat-ct-pns-three-films',
  'name': 'CT PNS (Three  films)',
  'slug': 'ct-pns-three-films',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT PNS (Three  films)', 'Scan CT PNS (Three  films)', 'CT PNS (Three  films) Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 3500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT PNS (Three  films)) with high geometric accuracy.'},
 {'id': 'cat-ct-temporal-bones',
  'name': 'CT TEMPORAL BONES',
  'slug': 'ct-temporal-bones',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT TEMPORAL BONES', 'Scan CT TEMPORAL BONES', 'CT TEMPORAL BONES Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 4000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT TEMPORAL BONES) with high geometric accuracy.'},
 {'id': 'cat-ct-pulmonary-angio',
  'name': 'CT PULMONARY ANGIO',
  'slug': 'ct-pulmonary-angio',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT PULMONARY ANGIO', 'Scan CT PULMONARY ANGIO', 'CT PULMONARY ANGIO Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 6500.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT PULMONARY ANGIO) with high geometric accuracy.'},
 {'id': 'cat-ct-renal-angiogram',
  'name': 'CT RENAL ANGIOGRAM',
  'slug': 'ct-renal-angiogram',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT RENAL ANGIOGRAM', 'Scan CT RENAL ANGIOGRAM', 'CT RENAL ANGIOGRAM Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT RENAL ANGIOGRAM) with high geometric accuracy.'},
 {'id': 'cat-ct-spine-any-region',
  'name': 'CT SPINE ANY REGION',
  'slug': 'ct-spine-any-region',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT SPINE ANY REGION', 'Scan CT SPINE ANY REGION', 'CT SPINE ANY REGION Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 5000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT SPINE ANY REGION) with high geometric accuracy.'},
 {'id': 'cat-ct-upper-lower-limb-angioram',
  'name': 'CT UPPER / LOWER LIMB ANGIORAM',
  'slug': 'ct-upper-lower-limb-angioram',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT UPPER / LOWER LIMB ANGIORAM',
               'Scan CT UPPER / LOWER LIMB ANGIORAM',
               'CT UPPER / LOWER LIMB ANGIORAM Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT UPPER / LOWER LIMB ANGIORAM) with high geometric '
                 'accuracy.'},
 {'id': 'cat-ct-urogram',
  'name': 'CT UROGRAM',
  'slug': 'ct-urogram',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT UROGRAM', 'Scan CT UROGRAM', 'CT UROGRAM Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 5000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT UROGRAM) with high geometric accuracy.'},
 {'id': 'cat-ct-enterography',
  'name': 'CT ENTEROGRAPHY',
  'slug': 'ct-enterography',
  'category': 'imaging',
  'sub_category': 'ct',
  'synonyms': ['CT ENTEROGRAPHY', 'Scan CT ENTEROGRAPHY', 'CT ENTEROGRAPHY Scan'],
  'typical_turnaround_hours': 8,
  'mrp': 8000.0,
  'is_active': True,
  'preparation': 'Wear comfortable loose cotton clothing without metallic fastenings. Fasting 4 hours if contrast '
                 'administration is required.',
  'description': 'High-speed multi-slice computed tomography (CT ENTEROGRAPHY) with high geometric accuracy.'},
 {'id': 'cat-ultra-sound-scans',
  'name': 'ULTRA SOUND SCANS',
  'slug': 'ultra-sound-scans',
  'category': 'imaging',
  'sub_category': 'ultrasound',
  'synonyms': ['ULTRA SOUND SCANS', 'ULTRA SOUND SCANS Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 1200.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (ULTRA SOUND SCANS) conducted under certified '
                 'radiologist supervision.'},
 {'id': 'cat-doppler',
  'name': 'DOPPLER',
  'slug': 'doppler',
  'category': 'imaging',
  'sub_category': 'ultrasound',
  'synonyms': ['DOPPLER', 'DOPPLER Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 2500.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (DOPPLER) conducted under certified radiologist '
                 'supervision.'},
 {'id': 'cat-tiffa',
  'name': 'TIFFA',
  'slug': 'tiffa',
  'category': 'imaging',
  'sub_category': 'ultrasound',
  'synonyms': ['TIFFA', 'TIFFA Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 3000.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (TIFFA) conducted under certified radiologist '
                 'supervision.'},
 {'id': 'cat-antenatal-scan',
  'name': 'ANTENATAL SCAN',
  'slug': 'antenatal-scan',
  'category': 'imaging',
  'sub_category': 'ultrasound',
  'synonyms': ['ANTENATAL SCAN', 'ANTENATAL SCAN Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 1800.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (ANTENATAL SCAN) conducted under certified '
                 'radiologist supervision.'},
 {'id': 'cat-2d-echo',
  'name': '2D ECHO',
  'slug': '2d-echo',
  'category': 'imaging',
  'sub_category': 'cardiology',
  'synonyms': ['2D ECHO', '2D ECHO Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 2200.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (2D ECHO) conducted under certified radiologist '
                 'supervision.'},
 {'id': 'cat-x-ray-single',
  'name': 'X RAY (SINGLE)',
  'slug': 'x-ray-single',
  'category': 'imaging',
  'sub_category': 'xray',
  'synonyms': ['X RAY (SINGLE)', 'X RAY (SINGLE) Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 500.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (X RAY (SINGLE)) conducted under certified '
                 'radiologist supervision.'},
 {'id': 'cat-x-ray-double',
  'name': 'X RAY (DOUBLE)',
  'slug': 'x-ray-double',
  'category': 'imaging',
  'sub_category': 'xray',
  'synonyms': ['X RAY (DOUBLE)', 'X RAY (DOUBLE) Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 800.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (X RAY (DOUBLE)) conducted under certified '
                 'radiologist supervision.'},
 {'id': 'cat-tmt',
  'name': 'TMT',
  'slug': 'tmt',
  'category': 'imaging',
  'sub_category': 'cardiology',
  'synonyms': ['TMT', 'TMT Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 2000.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (TMT) conducted under certified radiologist '
                 'supervision.'},
 {'id': 'cat-bmd',
  'name': 'BMD',
  'slug': 'bmd',
  'category': 'imaging',
  'sub_category': 'specialized_scan',
  'synonyms': ['BMD', 'BMD Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 2500.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (BMD) conducted under certified radiologist '
                 'supervision.'},
 {'id': 'cat-mammogram',
  'name': 'MAMMOGRAM',
  'slug': 'mammogram',
  'category': 'imaging',
  'sub_category': 'specialized_scan',
  'synonyms': ['MAMMOGRAM', 'MAMMOGRAM Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 2500.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (MAMMOGRAM) conducted under certified radiologist '
                 'supervision.'},
 {'id': 'cat-hsg',
  'name': 'HSG',
  'slug': 'hsg',
  'category': 'imaging',
  'sub_category': 'specialized_scan',
  'synonyms': ['HSG', 'HSG Imaging'],
  'typical_turnaround_hours': 4,
  'mrp': 3500.0,
  'is_active': True,
  'preparation': 'Follow study-specific preparation instructions (e.g. full bladder for pelvic USG, cotton clothing).',
  'description': 'Diagnostic scan and specialized imaging evaluation (HSG) conducted under certified radiologist '
                 'supervision.'},
 {'id': 'cat-cbc',
  'name': 'CBC',
  'slug': 'cbc',
  'category': 'lab_test',
  'sub_category': 'blood_test',
  'synonyms': ['CBC', 'Complete Blood Count'],
  'typical_turnaround_hours': 6,
  'mrp': 400.0,
  'is_active': True,
  'preparation': 'Fasting is generally not required for CBC. Sterile collection for cultures.',
  'description': 'Laboratory core diagnostic analysis (CBC) performed in accredited diagnostic pathology facility.'},
 {'id': 'cat-cultures',
  'name': 'CULTURES',
  'slug': 'cultures',
  'category': 'lab_test',
  'sub_category': 'blood_test',
  'synonyms': ['CULTURES', 'Blood Culture'],
  'typical_turnaround_hours': 48,
  'mrp': 900.0,
  'is_active': True,
  'preparation': 'Fasting is generally not required for CBC. Sterile collection for cultures.',
  'description': 'Laboratory core diagnostic analysis (CULTURES) performed in accredited diagnostic pathology '
                 'facility.'}]
