-- ============================================================================
-- CallMedex service catalogue — master data load
--
-- Generated from the owner-supplied commercial sheets (kept local, gitignored):
--   CALL MEDEX LAB MASTER DATA.xlsx                     487 lab tests
--   PHYSIOTHERAPY_SCOPE_SERVICES1.xlsx                  94 physiotherapy services
--   Dental_Clinic_Hospital_Scope_of_Services_Offer_Price 298 dental services
--
-- reference_mrp is the indicative regular price; reference_offer_price is the
-- CallMedex rate where the sheet supplies one. The lab sheet supplies both. The
-- dental and physiotherapy sheets deliberately leave Offer Price blank — those
-- are negotiated per partner — so reference_offer_price is NULL there and the
-- marketplace shows no saving until a real figure exists. An invented discount
-- would be a false claim to the patient and an unfunded liability for a partner.
--
-- Idempotent: ON CONFLICT (slug) refreshes prices without duplicating rows.
-- ============================================================================

BEGIN;

ALTER TABLE service_catalog DROP CONSTRAINT IF EXISTS service_catalog_category_check;
ALTER TABLE service_catalog ADD CONSTRAINT service_catalog_category_check
  CHECK (category IN ('lab_test','imaging','health_package','procedure',
                      'consultation','physiotherapy','dental','nursing'));

ALTER TABLE service_catalog ADD COLUMN IF NOT EXISTS sub_category          TEXT DEFAULT '';
ALTER TABLE service_catalog ADD COLUMN IF NOT EXISTS unit                  TEXT DEFAULT '';
ALTER TABLE service_catalog ADD COLUMN IF NOT EXISTS reference_mrp         NUMERIC(10,2);
ALTER TABLE service_catalog ADD COLUMN IF NOT EXISTS reference_offer_price NUMERIC(10,2);

CREATE INDEX IF NOT EXISTS idx_service_catalog_subcategory
    ON service_catalog(category, sub_category) WHERE is_active;

INSERT INTO service_catalog
    (name, slug, category, sub_category, unit, reference_mrp, reference_offer_price)
VALUES
 ('1,25 Dihydroxy Vitamin D', '1-25-dihydroxy-vitamin-d', 'lab_test', NULL, NULL, 3500.00, 2800.00),
 ('17 Alpha Hydroxy Progesteron', '17-alpha-hydroxy-progesteron', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('17 Hydroxy Corticosteroids, Urine 24H', '17-hydroxy-corticosteroids-urine-24h', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('17-Ketosteroids, Urine 24H', '17-ketosteroids-urine-24h', 'lab_test', NULL, NULL, 10000.00, 8000.00),
 ('25 Hydroxy Vitamin D', '25-hydroxy-vitamin-d', 'lab_test', NULL, NULL, 1600.00, 1280.00),
 ('5 Hydroxy Indole Acetic Acid, 24 Urine', '5-hydroxy-indole-acetic-acid-24-urine', 'lab_test', NULL, NULL, 3570.00, 2856.00),
 ('Absolute Eosinophil Count (AEC)', 'absolute-eosinophil-count-aec', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Absolute Lymphocyte Count', 'absolute-lymphocyte-count', 'lab_test', NULL, NULL, 310.00, 248.00),
 ('Absolute Monocyte Count', 'absolute-monocyte-count', 'lab_test', NULL, NULL, 310.00, 248.00),
 ('Absolute Neutrophil Count (ANC)', 'absolute-neutrophil-count-anc', 'lab_test', NULL, NULL, 310.00, 248.00),
 ('Acetone (Ketone), Urine', 'acetone-ketone-urine', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Acetylcholine Receptor Antibody', 'acetylcholine-receptor-antibody', 'lab_test', NULL, NULL, 3270.00, 2616.00),
 ('Activated Partial Thromboplastin Time (APTT)', 'activated-partial-thromboplastin-time-aptt', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Activated Protein C (APC) Resistance Test,Plasma', 'activated-protein-c-apc-resistance-test-plasma', 'lab_test', NULL, NULL, 4590.00, 3672.00),
 ('Acute Leukemia Diagnostic Panel', 'acute-leukemia-diagnostic-panel', 'lab_test', NULL, NULL, 12240.00, 9792.00),
 ('ADA, Ascitic fluid', 'ada-ascitic-fluid', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('ADA, CSF', 'ada-csf', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('ADA, cyst aspiration fluid', 'ada-cyst-aspiration-fluid', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('ADA, Guided Aspirate', 'ada-guided-aspirate', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('ADA, Pericardial Fluid', 'ada-pericardial-fluid', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('ADA, Peritoneal Fluid', 'ada-peritoneal-fluid', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('ADA, Pleural fluid', 'ada-pleural-fluid', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('ADA, PUS', 'ada-pus', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('ADA, Serum', 'ada-serum', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('ADA, Synovial Fluid', 'ada-synovial-fluid', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('Adrenaline (Epinephrine),urine 24H', 'adrenaline-epinephrine-urine-24h', 'lab_test', NULL, NULL, 3060.00, 2448.00),
 ('Adreno Corticotrophic Horomone (ACTH)', 'adreno-corticotrophic-horomone-acth', 'lab_test', NULL, NULL, 1800.00, 1440.00),
 ('AFB Culture- Biopsy', 'afb-culture-biopsy', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('AFB Culture, Conventional Method', 'afb-culture-conventional-method', 'lab_test', NULL, NULL, 1020.00, 816.00),
 ('AFB Stain, Sputum', 'afb-stain-sputum', 'lab_test', NULL, NULL, 450.00, 360.00),
 ('AFB Stain, Sputum - 1st Sample', 'afb-stain-sputum-1st-sample', 'lab_test', NULL, NULL, 450.00, 360.00),
 ('Albumin, Serum', 'albumin-serum', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Albumin, Urine 24H', 'albumin-urine-24h', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('Albumin, Urine Spot', 'albumin-urine-spot', 'lab_test', NULL, NULL, 110.00, 88.00),
 ('Alkaline Phosphatase (ALP)', 'alkaline-phosphatase-alp', 'lab_test', NULL, NULL, 170.00, 136.00),
 ('Alkaline Phosphatase with bone Fraction (Ostase)', 'alkaline-phosphatase-with-bone-fraction-ostase', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Alpha Feto Protein (AFP)', 'alpha-feto-protein-afp', 'lab_test', NULL, NULL, 1050.00, 840.00),
 ('Alpha Feto Protein (AFP), CSF', 'alpha-feto-protein-afp-csf', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('ALT (SGPT)', 'alt-sgpt', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Ammonia', 'ammonia', 'lab_test', NULL, NULL, 1020.00, 816.00),
 ('Amylase, Cyst Fluid', 'amylase-cyst-fluid', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('Amylase, Fluid', 'amylase-fluid', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('Amylase, Serum', 'amylase-serum', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('ANA Profile', 'ana-profile', 'lab_test', NULL, NULL, 3500.00, 2800.00),
 ('ANA PROFILE', 'ana-profile-2', 'lab_test', NULL, NULL, 3500.00, 2800.00),
 ('Angiotensing Converting Enzyme (ACE)', 'angiotensing-converting-enzyme-ace', 'lab_test', NULL, NULL, 2800.00, 2240.00),
 ('Angiotensing Converting Enzyme (ACE),CSF', 'angiotensing-converting-enzyme-ace-csf', 'lab_test', NULL, NULL, 3500.00, 2800.00),
 ('Anti DNase B, serum', 'anti-dnase-b-serum', 'lab_test', NULL, NULL, 1840.00, 1472.00),
 ('Anti ds DNA', 'anti-ds-dna', 'lab_test', NULL, NULL, 2200.00, 1760.00),
 ('Anti Neutrophil Cytoplasmic Antibody (ANCA)', 'anti-neutrophil-cytoplasmic-antibody-anca', 'lab_test', NULL, NULL, 2350.00, 1880.00),
 ('Anti Nuclear Antibodies (ANA)', 'anti-nuclear-antibodies-ana', 'lab_test', NULL, NULL, 950.00, 760.00),
 ('Anti Streptolisin O (ASO)', 'anti-streptolisin-o-aso', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Anti Thrombin III Activity', 'anti-thrombin-iii-activity', 'lab_test', NULL, NULL, 5100.00, 4080.00),
 ('Anti Thrombin III Antigen', 'anti-thrombin-iii-antigen', 'lab_test', NULL, NULL, 5100.00, 4080.00),
 ('Anti Thyroid Anti Bodies/TPO/2/ATG', 'anti-thyroid-anti-bodies-tpo-2-atg', 'lab_test', NULL, NULL, 2700.00, 2160.00),
 ('Anti Thyroid Peroxidase (Anti Tpo), Microsomal Antibody', 'anti-thyroid-peroxidase-anti-tpo-microsomal-antibody', 'lab_test', NULL, NULL, 2800.00, 2240.00),
 ('APLA PROFILE', 'apla-profile', 'lab_test', NULL, NULL, 6000.00, 4800.00),
 ('Apolipoprotein - B', 'apolipoprotein-b', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('AST (SGOT)', 'ast-sgot', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('B Type Natriuretic Peptide (BNP)(NT-Pro)', 'b-type-natriuretic-peptide-bnp-nt-pro', 'lab_test', NULL, NULL, 3270.00, 2616.00),
 ('Bence Jones Proteins, Urine', 'bence-jones-proteins-urine', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Beta 2 Microglobulin, Serum', 'beta-2-microglobulin-serum', 'lab_test', NULL, NULL, 1800.00, 1440.00),
 ('Beta HCG, Serum', 'beta-hcg-serum', 'lab_test', NULL, NULL, 1300.00, 1040.00),
 ('Beta-2-Glycoprotein I IgG Antibody Serum', 'beta-2-glycoprotein-i-igg-antibody-serum', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('Beta-2-Glycoprotein I IgM Antibody Serum', 'beta-2-glycoprotein-i-igm-antibody-serum', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('Bicarbonate', 'bicarbonate', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('Bile Acids-Total, Serum', 'bile-acids-total-serum', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('Bile Salts and Bile Pigments , Urine', 'bile-salts-and-bile-pigments-urine', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Bilirubin, (Total,Direct,Indirect)', 'bilirubin-total-direct-indirect', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('Bilirubin, Direct', 'bilirubin-direct', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Bilirubin, Total', 'bilirubin-total', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Biochemical analysis, Ascitic fluid', 'biochemical-analysis-ascitic-fluid', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('Biochemical analysis, Peritoneal fluid', 'biochemical-analysis-peritoneal-fluid', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('BIOPSY (Large)', 'biopsy-large', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('BIOPSY MEDIUM', 'biopsy-medium', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('Bleeding Time', 'bleeding-time', 'lab_test', NULL, NULL, 30.00, 24.00),
 ('Blood Culture and Sensitivity - 1st Report', 'blood-culture-and-sensitivity-1st-report', 'lab_test', NULL, NULL, 1350.00, 1080.00),
 ('Blood Culture and Sensitivity - 2nd Report', 'blood-culture-and-sensitivity-2nd-report', 'lab_test', NULL, NULL, 1350.00, 1080.00),
 ('Blood Culture and Sensitivity - Final Report', 'blood-culture-and-sensitivity-final-report', 'lab_test', NULL, NULL, 1350.00, 1080.00),
 ('Blood Grouping and Rh Typing', 'blood-grouping-and-rh-typing', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Blood Urea Nitrogen (BUN)', 'blood-urea-nitrogen-bun', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Bun Creatinine Ratio', 'bun-creatinine-ratio', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('C- Peptide', 'c-peptide', 'lab_test', NULL, NULL, 1640.00, 1312.00),
 ('C1 Esterase Inhibitor, Serum', 'c1-esterase-inhibitor-serum', 'lab_test', NULL, NULL, 3570.00, 2856.00),
 ('CA - 125', 'ca-125', 'lab_test', NULL, NULL, 1300.00, 1040.00),
 ('CA 15.3', 'ca-15-3', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('CA 19.9', 'ca-19-9', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('CA-125 Fluid', 'ca-125-fluid', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Calcitonin (Thyrocalcitonin),Serum', 'calcitonin-thyrocalcitonin-serum', 'lab_test', NULL, NULL, 3570.00, 2856.00),
 ('Calcium, Ionized', 'calcium-ionized', 'lab_test', NULL, NULL, 700.00, 560.00),
 ('Calcium, Serum', 'calcium-serum', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Calcium, Urine 24H', 'calcium-urine-24h', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Calcium/Creatinine Ratio, Urine spot', 'calcium-creatinine-ratio-urine-spot', 'lab_test', NULL, NULL, 620.00, 496.00),
 ('C-ANCA', 'c-anca', 'lab_test', NULL, NULL, 2100.00, 1680.00),
 ('Carbamezepine (Tegretol)', 'carbamezepine-tegretol', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Carcino Embroynic Antigen (CEA)', 'carcino-embroynic-antigen-cea', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('Cardiolipin IgA Antibody', 'cardiolipin-iga-antibody', 'lab_test', NULL, NULL, 1230.00, 984.00),
 ('Cardiolipin IgG Antibody', 'cardiolipin-igg-antibody', 'lab_test', NULL, NULL, 1230.00, 984.00),
 ('Cardiolipin IgM Antibody', 'cardiolipin-igm-antibody', 'lab_test', NULL, NULL, 1250.00, 1000.00),
 ('Cardiolipin Profile', 'cardiolipin-profile', 'lab_test', NULL, NULL, 3270.00, 2616.00),
 ('Catecholamines, Urine 24Hrs', 'catecholamines-urine-24hrs', 'lab_test', NULL, NULL, 7900.00, 6320.00),
 ('CB NAAT Sputum', 'cb-naat-sputum', 'lab_test', NULL, NULL, 2500.00, 2000.00),
 ('CBC', 'cbc', 'lab_test', NULL, NULL, 350.00, 280.00),
 ('CBP WITH ESR', 'cbp-with-esr', 'lab_test', NULL, NULL, 650.00, 520.00),
 ('CD 4 & CD 8 Count', 'cd-4-cd-8-count', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('CD 4 Count', 'cd-4-count', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('CD3, CD 4 & CD 8 Count', 'cd3-cd-4-cd-8-count', 'lab_test', NULL, NULL, 2700.00, 2160.00),
 ('Cell count & cell type, Ascitic Fluid', 'cell-count-cell-type-ascitic-fluid', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Cell count & cell type, Bronchial Wash', 'cell-count-cell-type-bronchial-wash', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('Cell count & cell type, CSF', 'cell-count-cell-type-csf', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('Cell count & cell type, fluid', 'cell-count-cell-type-fluid', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Cell count & cell type, Guided Aspirate Fluid', 'cell-count-cell-type-guided-aspirate-fluid', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Cell count & cell type,Dialysis Fluid', 'cell-count-cell-type-dialysis-fluid', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Centromere Antibody', 'centromere-antibody', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Ceruloplasmin(Copper Oxidase), Serum', 'ceruloplasmin-copper-oxidase-serum', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Chikungunya IgM Antibody', 'chikungunya-igm-antibody', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Chlamydia Trachomatis IgA Antibody', 'chlamydia-trachomatis-iga-antibody', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('Chlorides, CSF', 'chlorides-csf', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Chlorides, Serum', 'chlorides-serum', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Chlorides, Urine 24H', 'chlorides-urine-24h', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('Cholesterol,Total', 'cholesterol-total', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Cholinesterase- Acetyl, Plasma', 'cholinesterase-acetyl-plasma', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('Chyle, Urine', 'chyle-urine', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Citrate, Urine 24 H', 'citrate-urine-24-h', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('Clotting Time', 'clotting-time', 'lab_test', NULL, NULL, 30.00, 24.00),
 ('Cobalt, Blood', 'cobalt-blood', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('COLLAGEN PROFILE', 'collagen-profile', 'lab_test', NULL, NULL, 6900.00, 5520.00),
 ('COLLAGEN PROFILE ADVANCED', 'collagen-profile-advanced', 'lab_test', NULL, NULL, 6900.00, 5520.00),
 ('Complement-3', 'complement-3', 'lab_test', NULL, NULL, 1300.00, 1040.00),
 ('Complement-4', 'complement-4', 'lab_test', NULL, NULL, 1300.00, 1040.00),
 ('Complete Blood Picture (CBP)', 'complete-blood-picture-cbp', 'lab_test', NULL, NULL, 350.00, 280.00),
 ('Complete Urine Examination (CUE)', 'complete-urine-examination-cue', 'lab_test', NULL, NULL, 160.00, 128.00),
 ('Coombs Test - Direct (DCT)', 'coombs-test-direct-dct', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Coombs Test - Indirect (ICT)', 'coombs-test-indirect-ict', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Copper, Serum', 'copper-serum', 'lab_test', NULL, NULL, 1840.00, 1472.00),
 ('Copper, Urine 24H', 'copper-urine-24h', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('Cortisol (4 PM)', 'cortisol-4-pm', 'lab_test', NULL, NULL, 920.00, 736.00),
 ('Cortisol (8 AM)', 'cortisol-8-am', 'lab_test', NULL, NULL, 920.00, 736.00),
 ('Cortisol ,Free Urine 24H', 'cortisol-free-urine-24h', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('CPK- MB', 'cpk-mb', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('C-Reactive Proteins (CRP)', 'c-reactive-proteins-crp', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Creatine Kinase (CPK)', 'creatine-kinase-cpk', 'lab_test', NULL, NULL, 600.00, 480.00),
 ('Creatinine Clearance Test, Urine 24H', 'creatinine-clearance-test-urine-24h', 'lab_test', NULL, NULL, 620.00, 496.00),
 ('Creatinine, Serum', 'creatinine-serum', 'lab_test', NULL, NULL, 120.00, 96.00),
 ('Creatinine, Urine 24H', 'creatinine-urine-24h', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Creatinine, Urine Spot', 'creatinine-urine-spot', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Creatinine-GFR by MDRD', 'creatinine-gfr-by-mdrd', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('Cryptococcus Antigen, CSF', 'cryptococcus-antigen-csf', 'lab_test', NULL, NULL, 3570.00, 2856.00),
 ('CSF ANALYSIS ANURADHA NEURO', 'csf-analysis-anuradha-neuro', 'lab_test', NULL, NULL, 6020.00, 4816.00),
 ('CT BOTH TEMPORAL BONES', 'ct-both-temporal-bones', 'lab_test', NULL, NULL, 7000.00, 5600.00),
 ('CT GUIDED BIOPSY', 'ct-guided-biopsy', 'lab_test', NULL, NULL, 7500.00, 6000.00),
 ('CT REPORT (SECOND OPINION)', 'ct-report-second-opinion', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('CT STRYKER PROTOCOL', 'ct-stryker-protocol', 'lab_test', NULL, NULL, 9500.00, 7600.00),
 ('Culture & Sensitivity , Tracheal secretion', 'culture-sensitivity-tracheal-secretion', 'lab_test', NULL, NULL, 570.00, 456.00),
 ('Culture and Sensitivity , Biopsy', 'culture-and-sensitivity-biopsy', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Ascitic Fluid', 'culture-and-sensitivity-ascitic-fluid', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Bronchial Wash', 'culture-and-sensitivity-bronchial-wash', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, CSF', 'culture-and-sensitivity-csf', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, cyst aspiration Fluid', 'culture-and-sensitivity-cyst-aspiration-fluid', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Ear/Eye Swab', 'culture-and-sensitivity-ear-eye-swab', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Fluid', 'culture-and-sensitivity-fluid', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Guided Aspirate', 'culture-and-sensitivity-guided-aspirate', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Nasal Swab', 'culture-and-sensitivity-nasal-swab', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Pleural Fluid', 'culture-and-sensitivity-pleural-fluid', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Pus', 'culture-and-sensitivity-pus', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Pus Swab', 'culture-and-sensitivity-pus-swab', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Sputum', 'culture-and-sensitivity-sputum', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Stool', 'culture-and-sensitivity-stool', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Synovial Fluid', 'culture-and-sensitivity-synovial-fluid', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity, Throat Swab', 'culture-and-sensitivity-throat-swab', 'lab_test', NULL, NULL, 700.00, 560.00),
 ('Culture and Sensitivity, Urine', 'culture-and-sensitivity-urine', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity,Urethral Swab', 'culture-and-sensitivity-urethral-swab', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity,Vaginal Swab', 'culture-and-sensitivity-vaginal-swab', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensitivity,Wound Swab', 'culture-and-sensitivity-wound-swab', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Culture and Sensivity ,Cervical swab', 'culture-and-sensivity-cervical-swab', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Cyclic Citrullinated Peptide (CCP) Antibody', 'cyclic-citrullinated-peptide-ccp-antibody', 'lab_test', NULL, NULL, 1900.00, 1520.00),
 ('Cytology, Ascitic Fluid', 'cytology-ascitic-fluid', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Cytology, Papsmear', 'cytology-papsmear', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Cytology, Papsmear', 'cytology-papsmear-2', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Cytology, Papsmear by LBC Method', 'cytology-papsmear-by-lbc-method', 'lab_test', NULL, NULL, 1230.00, 984.00),
 ('D-Dimer', 'd-dimer', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('Dehydro Epiandrosterone Sulphate (DHEA-S)', 'dehydro-epiandrosterone-sulphate-dhea-s', 'lab_test', NULL, NULL, 1600.00, 1280.00),
 ('Dengue Antigen NS1 (ELISA)', 'dengue-antigen-ns1-elisa', 'lab_test', NULL, NULL, 950.00, 760.00),
 ('Dengue Ig G & Ig M - Rapid', 'dengue-ig-g-ig-m-rapid', 'lab_test', NULL, NULL, 950.00, 760.00),
 ('Dengue IgG IgM NS1 (Rapid)', 'dengue-igg-igm-ns1-rapid', 'lab_test', NULL, NULL, 950.00, 760.00),
 ('Dengue Serology', 'dengue-serology', 'lab_test', NULL, NULL, 950.00, 760.00),
 ('Di HydroTestosterone (DHT)', 'di-hydrotestosterone-dht', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Differential Count (DC)', 'differential-count-dc', 'lab_test', NULL, NULL, 50.00, 40.00),
 ('Double Marker Test', 'double-marker-test', 'lab_test', NULL, NULL, 3060.00, 2448.00),
 ('Double Marker Test Graph', 'double-marker-test-graph', 'lab_test', NULL, NULL, 3060.00, 2448.00),
 ('DTI (DIFFUSION TENSOR IMAGING)', 'dti-diffusion-tensor-imaging', 'lab_test', NULL, NULL, 6250.00, 5000.00),
 ('ECG(ELECTROCARDIOGRAM)', 'ecg-electrocardiogram', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('EEGUSG PACKAGE', 'eegusg-package', 'lab_test', NULL, NULL, 2400.00, 1920.00),
 ('Electrolytes, 24H Urine', 'electrolytes-24h-urine', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('Electrolytes, Serum', 'electrolytes-serum', 'lab_test', NULL, NULL, 450.00, 360.00),
 ('Electrolytes, Urine spot', 'electrolytes-urine-spot', 'lab_test', NULL, NULL, 450.00, 360.00),
 ('Erythrocyte Sedimentation Rate (ESR)', 'erythrocyte-sedimentation-rate-esr', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Erythropoitin, Serum', 'erythropoitin-serum', 'lab_test', NULL, NULL, 3570.00, 2856.00),
 ('Estradiol (E2)', 'estradiol-e2', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('Estriol unconjugated (E3)', 'estriol-unconjugated-e3', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Factor-I (Fibrinogen) Activity', 'factor-i-fibrinogen-activity', 'lab_test', NULL, NULL, 1230.00, 984.00),
 ('Fat, Stool', 'fat-stool', 'lab_test', NULL, NULL, 210.00, 168.00),
 ('FBS AND PPBS', 'fbs-and-ppbs', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('FBS AND PPBS', 'fbs-and-ppbs-2', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Ferritin, Serum', 'ferritin-serum', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('FMR', 'fmr', 'lab_test', NULL, NULL, 115.00, 92.00),
 ('FNAC Blind Procedure & Report', 'fnac-blind-procedure-report', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('Folic Acid, serum', 'folic-acid-serum', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Follicular Stimulating Hormone (FSH)', 'follicular-stimulating-hormone-fsh', 'lab_test', NULL, NULL, 650.00, 520.00),
 ('Free Beta HCG,Serum', 'free-beta-hcg-serum', 'lab_test', NULL, NULL, 1130.00, 904.00),
 ('Fungal Culture, Sputum', 'fungal-culture-sputum', 'lab_test', NULL, NULL, 920.00, 736.00),
 ('Fungal Stain, CSF', 'fungal-stain-csf', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('G6PD , Blood', 'g6pd-blood', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('GAD 65 (Glutamic Acid Decorboxilase) Antibodies', 'gad-65-glutamic-acid-decorboxilase-antibodies', 'lab_test', NULL, NULL, 7550.00, 6040.00),
 ('Gamma GT (GGTP)', 'gamma-gt-ggtp', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Ganglioside Antibody,Serum', 'ganglioside-antibody-serum', 'lab_test', NULL, NULL, 4000.00, 3200.00),
 ('Gene expert (xpert MTB)', 'gene-expert-xpert-mtb', 'lab_test', NULL, NULL, 3060.00, 2448.00),
 ('Gene expert PUS', 'gene-expert-pus', 'lab_test', NULL, NULL, 3060.00, 2448.00),
 ('Globulin Serum', 'globulin-serum', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Glucose Challenge Test (GCT)', 'glucose-challenge-test-gct', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('GLUCOSE TOLERANCE TEST (3 Samples)', 'glucose-tolerance-test-3-samples', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Glucose, (RBS)', 'glucose-rbs', 'lab_test', NULL, NULL, 50.00, 40.00),
 ('Glucose, Fasting (FBS)', 'glucose-fasting-fbs', 'lab_test', NULL, NULL, 50.00, 40.00),
 ('Glucose, Post Lunch (PLBS)', 'glucose-post-lunch-plbs', 'lab_test', NULL, NULL, 50.00, 40.00),
 ('Glycosylated Hb (HbA1C)', 'glycosylated-hb-hba1c', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Grams Stain, Ascitic Fluid', 'grams-stain-ascitic-fluid', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Grams Stain, Bronchial Wash', 'grams-stain-bronchial-wash', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Grams Stain, CSF', 'grams-stain-csf', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Grams Stain, Pericardial Fluid', 'grams-stain-pericardial-fluid', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Grams Stain, Pleural Fluid', 'grams-stain-pleural-fluid', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Grams Stain, Pus', 'grams-stain-pus', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Grams Stain, Stool', 'grams-stain-stool', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Grams Stain, Wound Swab', 'grams-stain-wound-swab', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('GTT - 1st Hour Plasma Glucose', 'gtt-1st-hour-plasma-glucose', 'lab_test', NULL, NULL, NULL, NULL),
 ('GTT -Fasting Plasma Glucose( 3 Samples )', 'gtt-fasting-plasma-glucose-3-samples', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Haemogram', 'haemogram', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Haptoglobin', 'haptoglobin', 'lab_test', NULL, NULL, 3270.00, 2616.00),
 ('HBV-DNA Detection (Qualitative)', 'hbv-dna-detection-qualitative', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('HBV-DNA Quantification (Viral load)', 'hbv-dna-quantification-viral-load', 'lab_test', NULL, NULL, 5600.00, 4480.00),
 ('HCV Genotyping', 'hcv-genotyping', 'lab_test', NULL, NULL, 8160.00, 6528.00),
 ('HCV RNA Quantification (Viral load)', 'hcv-rna-quantification-viral-load', 'lab_test', NULL, NULL, 5100.00, 4080.00),
 ('Hemoglobin (HB%)', 'hemoglobin-hb', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Hemoglobin Electrophoresis', 'hemoglobin-electrophoresis', 'lab_test', NULL, NULL, 1400.00, 1120.00),
 ('Hepatitis A Virus (HAV) IgM Antibody', 'hepatitis-a-virus-hav-igm-antibody', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('Hepatitis A Virus Antibody, (IgG) Total', 'hepatitis-a-virus-antibody-igg-total', 'lab_test', NULL, NULL, 1300.00, 1040.00),
 ('Hepatitis B Core Antibody Toatl(HBcAb - Total)', 'hepatitis-b-core-antibody-toatl-hbcab-total', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Hepatitis B Core Antigen (HBcAg), IgM Antibody', 'hepatitis-b-core-antigen-hbcag-igm-antibody', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Hepatitis B Envelope Antibody (HBeAb)', 'hepatitis-b-envelope-antibody-hbeab', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Hepatitis B Envelope Antigen (HBeAg )', 'hepatitis-b-envelope-antigen-hbeag', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Hepatitis B Surface Antibody,Total (Anti Hbs Titre)', 'hepatitis-b-surface-antibody-total-anti-hbs-titre', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Hepatitis B surface Antigen (HBsAg)', 'hepatitis-b-surface-antigen-hbsag', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Hepatitis B surface Antigen (HBsAg) - Elisa', 'hepatitis-b-surface-antigen-hbsag-elisa', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('Hepatitis B Surface antigen (HBsAg) (CMIA)', 'hepatitis-b-surface-antigen-hbsag-cmia', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Hepatitis B surface Antigen (HBsAg) Screening (Rapid)', 'hepatitis-b-surface-antigen-hbsag-screening-rapid', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Hepatitis C Virus (HCV) Antibody', 'hepatitis-c-virus-hcv-antibody', 'lab_test', NULL, NULL, 1700.00, 1360.00),
 ('Hepatitis C Virus (HCV) Antibody - Elisa', 'hepatitis-c-virus-hcv-antibody-elisa', 'lab_test', NULL, NULL, 720.00, 576.00),
 ('Hepatitis C Virus Antibody (Anti HCV) Screening (Rapid)', 'hepatitis-c-virus-antibody-anti-hcv-screening-rapid', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Hepatitis C Virus(HCV Anitibody)  (CLIA)', 'hepatitis-c-virus-hcv-anitibody-clia', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('Hepatitis E Virus (HEV) IgG Antibody', 'hepatitis-e-virus-hev-igg-antibody', 'lab_test', NULL, NULL, 2500.00, 2000.00),
 ('Hepatitis E Virus (HEV) IgM Antibody', 'hepatitis-e-virus-hev-igm-antibody', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Herpes Simplex Virus I & II - IgG', 'herpes-simplex-virus-i-ii-igg', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('High Sensitivity - CRP (HS-CRP)', 'high-sensitivity-crp-hs-crp', 'lab_test', NULL, NULL, 980.00, 784.00),
 ('Histopathology ( Medium )', 'histopathology-medium', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('Histopathology (Extra Large)', 'histopathology-extra-large', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Histopathology (Large)', 'histopathology-large', 'lab_test', NULL, NULL, 1600.00, 1280.00),
 ('Histopathology (Small)', 'histopathology-small', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('HIV 1& 2 Ag/Ab (4th generation)  (CMIA)', 'hiv-1-2-ag-ab-4th-generation-cmia', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('HIV ELISA', 'hiv-elisa', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('HIV I & II Antibody Screening (Rapid)', 'hiv-i-ii-antibody-screening-rapid', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('HIV P-24 Antigen', 'hiv-p-24-antigen', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('HIV-1-RNA Quantification (Viral Load)', 'hiv-1-rna-quantification-viral-load', 'lab_test', NULL, NULL, 5100.00, 4080.00),
 ('HLA - B27', 'hla-b27', 'lab_test', NULL, NULL, 3300.00, 2640.00),
 ('HLA - B27 By PCR', 'hla-b27-by-pcr', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('HLA - Cross Match', 'hla-cross-match', 'lab_test', NULL, NULL, 6120.00, 4896.00),
 ('Homocysteine-Serum', 'homocysteine-serum', 'lab_test', NULL, NULL, 950.00, 760.00),
 ('Homogentisic Acid', 'homogentisic-acid', 'lab_test', NULL, NULL, 1230.00, 984.00),
 ('HPV-DNA detection (Qualitative)', 'hpv-dna-detection-qualitative', 'lab_test', NULL, NULL, 3800.00, 3040.00),
 ('HSV I & II IgG & IgM antibodies', 'hsv-i-ii-igg-igm-antibodies', 'lab_test', NULL, NULL, 2500.00, 2000.00),
 ('Immunoglobulin IgA', 'immunoglobulin-iga', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('Immunoglobulin IgG', 'immunoglobulin-igg', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('Immunoglobulin IgM', 'immunoglobulin-igm', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('Immunoglobulin Profile, CSF', 'immunoglobulin-profile-csf', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('Insulin - Fasting serum', 'insulin-fasting-serum', 'lab_test', NULL, NULL, 900.00, 720.00),
 ('Insulin - Post ,Serum', 'insulin-post-serum', 'lab_test', NULL, NULL, 900.00, 720.00),
 ('Insulin Antibody, Serum', 'insulin-antibody-serum', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Insulin like Growth factor(IGF)-1(Somatomedin C)', 'insulin-like-growth-factor-igf-1-somatomedin-c', 'lab_test', NULL, NULL, 4400.00, 3520.00),
 ('Intact Parathyroid Hormone (iPTH)', 'intact-parathyroid-hormone-ipth', 'lab_test', NULL, NULL, 2250.00, 1800.00),
 ('INTERLEUKIN 6', 'interleukin-6', 'lab_test', NULL, NULL, 2500.00, 2000.00),
 ('Iron', 'iron', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('Iron with TIBC', 'iron-with-tibc', 'lab_test', NULL, NULL, 720.00, 576.00),
 ('JAK-2 Mutation,Blood', 'jak-2-mutation-blood', 'lab_test', NULL, NULL, 7140.00, 5712.00),
 ('Kappa & Lambda Light Chains- Free, Urine', 'kappa-lambda-light-chains-free-urine', 'lab_test', NULL, NULL, 5610.00, 4488.00),
 ('Kappa Light Chains- Free, Serum', 'kappa-light-chains-free-serum', 'lab_test', NULL, NULL, 3060.00, 2448.00),
 ('Karyotyping Whole Blood', 'karyotyping-whole-blood', 'lab_test', NULL, NULL, 4590.00, 3672.00),
 ('KOH Examination, Fluid', 'koh-examination-fluid', 'lab_test', NULL, NULL, 310.00, 248.00),
 ('KOH Examination, Nasal swab', 'koh-examination-nasal-swab', 'lab_test', NULL, NULL, 310.00, 248.00),
 ('KOH Examination, Sputum', 'koh-examination-sputum', 'lab_test', NULL, NULL, 310.00, 248.00),
 ('KOH Examination, Urine', 'koh-examination-urine', 'lab_test', NULL, NULL, 350.00, 280.00),
 ('Lactate', 'lactate', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Lactate Dehydrogenase (LDH), Fluid', 'lactate-dehydrogenase-ldh-fluid', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('Lactate Dehydrogenase (LDH), Serum', 'lactate-dehydrogenase-ldh-serum', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('LC-1 (Liver Cytosolic Antigen type-1)Antibody', 'lc-1-liver-cytosolic-antigen-type-1-antibody', 'lab_test', NULL, NULL, 3060.00, 2448.00),
 ('Legionella Antigen Detection, Urine', 'legionella-antigen-detection-urine', 'lab_test', NULL, NULL, 2660.00, 2128.00),
 ('Leishmania Antibody-IgG(Kala Azar)', 'leishmania-antibody-igg-kala-azar', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Leptin', 'leptin', 'lab_test', NULL, NULL, 6120.00, 4896.00),
 ('Leptospira Detection,Blood', 'leptospira-detection-blood', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Leptospira Detection,CSF', 'leptospira-detection-csf', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Leptospira IgG Antibody', 'leptospira-igg-antibody', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Leptospira IgM Antibody', 'leptospira-igm-antibody', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Levetiracetam, Serum', 'levetiracetam-serum', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('Lipase serum', 'lipase-serum', 'lab_test', NULL, NULL, 550.00, 440.00),
 ('Lipase,Fluid', 'lipase-fluid', 'lab_test', NULL, NULL, 800.00, 640.00),
 ('Lipase,Urine', 'lipase-urine', 'lab_test', NULL, NULL, 820.00, 656.00),
 ('Lipid Profile', 'lipid-profile', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Lipoprotein-(a)', 'lipoprotein-a', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('Lithium', 'lithium', 'lab_test', NULL, NULL, 820.00, 656.00),
 ('Liver Function Test (LFT)', 'liver-function-test-lft', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('LKM I Antibody', 'lkm-i-antibody', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Lupus Anticoagulants (LAC)', 'lupus-anticoagulants-lac', 'lab_test', NULL, NULL, 3270.00, 2616.00),
 ('Luteinizing Hormone (LH)', 'luteinizing-hormone-lh', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Lyme (Borrelia Burgdorferi) Antibody IgM', 'lyme-borrelia-burgdorferi-antibody-igm', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Lyme (Borrelia Burgdorferi)Antibody IgG', 'lyme-borrelia-burgdorferi-antibody-igg', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Magnesium', 'magnesium', 'lab_test', NULL, NULL, 610.00, 488.00),
 ('Magnesium 24Hrs Urine', 'magnesium-24hrs-urine', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('MCH', 'mch', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Measels (Rubeola) IgM Antibody', 'measels-rubeola-igm-antibody', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Metanephrine, Urine 24H', 'metanephrine-urine-24h', 'lab_test', NULL, NULL, 3300.00, 2640.00),
 ('Metanephrine-Free,Plasma', 'metanephrine-free-plasma', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('Meth haemoglobin', 'meth-haemoglobin', 'lab_test', NULL, NULL, 920.00, 736.00),
 ('Microalbumin, Urine 24H', 'microalbumin-urine-24h', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('Microalbumin/Creatinine ratio, Urine Spot', 'microalbumin-creatinine-ratio-urine-spot', 'lab_test', NULL, NULL, 620.00, 496.00),
 ('Mitochondrial Antibody (AMA)', 'mitochondrial-antibody-ama', 'lab_test', NULL, NULL, 2250.00, 1800.00),
 ('MRI CARDIAC WITH CONTRAST', 'mri-cardiac-with-contrast', 'lab_test', NULL, NULL, 12500.00, 10000.00),
 ('MRI LEFT KNEE JOINT', 'mri-left-knee-joint', 'lab_test', NULL, NULL, 5000.00, 4000.00),
 ('Mullerian Inhibiting Substance (AMH)', 'mullerian-inhibiting-substance-amh', 'lab_test', NULL, NULL, 2100.00, 1680.00),
 ('Mumps IgG Antibody', 'mumps-igg-antibody', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Mumps IgM Antibody', 'mumps-igm-antibody', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('Musk Antibody,Serum', 'musk-antibody-serum', 'lab_test', NULL, NULL, 6630.00, 5304.00),
 ('Mycobacterium TB DNA Detection', 'mycobacterium-tb-dna-detection', 'lab_test', NULL, NULL, 2250.00, 1800.00),
 ('Mycoplasma Pneumoniae IgG Antibody', 'mycoplasma-pneumoniae-igg-antibody', 'lab_test', NULL, NULL, 3200.00, 2560.00),
 ('Mycoplasma Pneumoniae IgM Antibody', 'mycoplasma-pneumoniae-igm-antibody', 'lab_test', NULL, NULL, 3200.00, 2560.00),
 ('Nasal Smear for Eosinophil Count', 'nasal-smear-for-eosinophil-count', 'lab_test', NULL, NULL, 310.00, 248.00),
 ('Natural Killer Cells (NKC), Blood', 'natural-killer-cells-nkc-blood', 'lab_test', NULL, NULL, 5100.00, 4080.00),
 ('Neuronal Antibody Profile', 'neuronal-antibody-profile', 'lab_test', NULL, NULL, 11220.00, 8976.00),
 ('NIPT', 'nipt', 'lab_test', NULL, NULL, 40000.00, 32000.00),
 ('Occult Blood, Stool', 'occult-blood-stool', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Oligoclonal band By IEF, CSF', 'oligoclonal-band-by-ief-csf', 'lab_test', NULL, NULL, 5100.00, 4080.00),
 ('ORTHOPANTOMOGRAM (OPG)', 'orthopantomogram-opg', 'lab_test', NULL, NULL, 480.00, 384.00),
 ('Osmolality, Serum', 'osmolality-serum', 'lab_test', NULL, NULL, 820.00, 656.00),
 ('Osmolality, Urine', 'osmolality-urine', 'lab_test', NULL, NULL, 820.00, 656.00),
 ('Osmotic Fragility Test', 'osmotic-fragility-test', 'lab_test', NULL, NULL, 920.00, 736.00),
 ('Ova Cyst, Stool', 'ova-cyst-stool', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('P-ANCA', 'p-anca', 'lab_test', NULL, NULL, 2100.00, 1680.00),
 ('PAPP - A', 'papp-a', 'lab_test', NULL, NULL, 1840.00, 1472.00),
 ('Parathyroid Hormone (PTH)', 'parathyroid-hormone-pth', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('Peripheral Smear for Abnormal Cells', 'peripheral-smear-for-abnormal-cells', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Peripheral Smear For Malarial Parasites', 'peripheral-smear-for-malarial-parasites', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Peripheral Smear Study', 'peripheral-smear-study', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Phenytoin (Eptoin)', 'phenytoin-eptoin', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Phospholipid Antibody (IgG)', 'phospholipid-antibody-igg', 'lab_test', NULL, NULL, 1230.00, 984.00),
 ('Phospholipid Antibody (IgM)', 'phospholipid-antibody-igm', 'lab_test', NULL, NULL, 1230.00, 984.00),
 ('Phosphorous, 24Hrs Urine', 'phosphorous-24hrs-urine', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Phosphorous, Serum', 'phosphorous-serum', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Phosphorous, Urine Spot', 'phosphorous-urine-spot', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Platelet Count', 'platelet-count', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Pneumocystis Carinii Detection, Fluid', 'pneumocystis-carinii-detection-fluid', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('PNH- Confirmation test, Blood', 'pnh-confirmation-test-blood', 'lab_test', NULL, NULL, 8160.00, 6528.00),
 ('Porphobilinogen (PBG), Quantitative Urine 24 H', 'porphobilinogen-pbg-quantitative-urine-24-h', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('POST PRANDIAL BLOOD SUGAR (PPBS)', 'post-prandial-blood-sugar-ppbs', 'lab_test', NULL, NULL, 50.00, 40.00),
 ('Potassium Urine Spot', 'potassium-urine-spot', 'lab_test', NULL, NULL, 410.00, 328.00),
 ('Potassium, Serum', 'potassium-serum', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Potassium, Urine 24H', 'potassium-urine-24h', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('Potassium/Creatinine ratio, Urine spot', 'potassium-creatinine-ratio-urine-spot', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Pregnancy Test, Urine', 'pregnancy-test-urine', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Procalcitonin, Serum', 'procalcitonin-serum', 'lab_test', NULL, NULL, 3460.00, 2768.00),
 ('Progesterone', 'progesterone', 'lab_test', NULL, NULL, 900.00, 720.00),
 ('Prolactin', 'prolactin', 'lab_test', NULL, NULL, 600.00, 480.00),
 ('Prostate Specific Antigen, Free', 'prostate-specific-antigen-free', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('Prostate Specific Antigen, Total (PSA)', 'prostate-specific-antigen-total-psa', 'lab_test', NULL, NULL, 900.00, 720.00),
 ('Protein Electrophoresis', 'protein-electrophoresis', 'lab_test', NULL, NULL, 1600.00, 1280.00),
 ('Protein Electrophoresis (Oligoclonal Bands), CSF', 'protein-electrophoresis-oligoclonal-bands-csf', 'lab_test', NULL, NULL, 5610.00, 4488.00),
 ('Protein Electrophoresis, Serum', 'protein-electrophoresis-serum', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('Protein Total with Albumin', 'protein-total-with-albumin', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Protein/Creatinine ratio, Urine 24 Hours', 'protein-creatinine-ratio-urine-24-hours', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Protein/Creatinine ratio, Urine Spot', 'protein-creatinine-ratio-urine-spot', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Protein/Creatinine ratio, Urine Spot', 'protein-creatinine-ratio-urine-spot-2', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Proteins Total, Serum', 'proteins-total-serum', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Proteins, Urine 24H', 'proteins-urine-24h', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Proteins, Urine Spot', 'proteins-urine-spot', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Prothrombin Time (PT)', 'prothrombin-time-pt', 'lab_test', NULL, NULL, 450.00, 360.00),
 ('Prothrombin Time With INR', 'prothrombin-time-with-inr', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('QBC for MP', 'qbc-for-mp', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Quadraple marker', 'quadraple-marker', 'lab_test', NULL, NULL, 3050.00, 2440.00),
 ('Quadruple Markar Graph', 'quadruple-markar-graph', 'lab_test', NULL, NULL, NULL, NULL),
 ('Rapid Malaria Test (PF)', 'rapid-malaria-test-pf', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Red Blood Cells Count (RBC)', 'red-blood-cells-count-rbc', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Reducing Substances, Stool', 'reducing-substances-stool', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('RENAL FUNCTION TESTS', 'renal-function-tests', 'lab_test', NULL, NULL, 1190.00, 952.00),
 ('Reticulocyte Count', 'reticulocyte-count', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Rheumatoid Factor (RA Factor)', 'rheumatoid-factor-ra-factor', 'lab_test', NULL, NULL, 480.00, 384.00),
 ('Rheumatoid Factor IgM, Antibody', 'rheumatoid-factor-igm-antibody', 'lab_test', NULL, NULL, 1640.00, 1312.00),
 ('RT PCR FOR COVID 19', 'rt-pcr-for-covid-19', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('Rubella Antibodies (IgG & IgM)', 'rubella-antibodies-igg-igm', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Rubella IgG Antibody', 'rubella-igg-antibody', 'lab_test', NULL, NULL, 920.00, 736.00),
 ('Rubella IgM Antibody', 'rubella-igm-antibody', 'lab_test', NULL, NULL, 920.00, 736.00),
 ('SAR2 (COVID 19) IG G ANTIBODIES', 'sar2-covid-19-ig-g-antibodies', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('SARS 2 (COVID19) ANTIBODIES IG G, IG M QUANTITATIVE', 'sars-2-covid19-antibodies-ig-g-ig-m-quantitative', 'lab_test', NULL, NULL, 1600.00, 1280.00),
 ('Scrub Typhus Antibody', 'scrub-typhus-antibody', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Second Opinion, Slide', 'second-opinion-slide', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('Selenium, Serum', 'selenium-serum', 'lab_test', NULL, NULL, 5100.00, 4080.00),
 ('Selenium, Urine', 'selenium-urine', 'lab_test', NULL, NULL, 5100.00, 4080.00),
 ('Semen  Analysis (CASA)', 'semen-analysis-casa', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Semen Analysis', 'semen-analysis', 'lab_test', NULL, NULL, 300.00, 240.00),
 ('Semen Analysis (Casa Method)', 'semen-analysis-casa-method', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Sex Hormone Binding Globulin (SHBG)', 'sex-hormone-binding-globulin-shbg', 'lab_test', NULL, NULL, 2550.00, 2040.00),
 ('Sickle Cell Test', 'sickle-cell-test', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Small Bowel Enema', 'small-bowel-enema', 'lab_test', NULL, NULL, 2500.00, 2000.00),
 ('Smear of Microfilaria Detection ,Blood', 'smear-of-microfilaria-detection-blood', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Smith IgG Antibody', 'smith-igg-antibody', 'lab_test', NULL, NULL, 2250.00, 1800.00),
 ('Smooth Muscle Antibody (ASMA)', 'smooth-muscle-antibody-asma', 'lab_test', NULL, NULL, 1640.00, 1312.00),
 ('Sodium, Serum', 'sodium-serum', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Sodium, Urine 24H', 'sodium-urine-24h', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('Sodium, Urine Spot', 'sodium-urine-spot', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Soluble Liver Antigen (SLA)', 'soluble-liver-antigen-sla', 'lab_test', NULL, NULL, 3640.00, 2912.00),
 ('Sono Mammography', 'sono-mammography', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('Stool Routine Examination', 'stool-routine-examination', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('STRESS ECHOCARDIOGRAM', 'stress-echocardiogram', 'lab_test', NULL, NULL, 4000.00, 3200.00),
 ('SURGICAL PROFILE 1 Padmasri Ivf', 'surgical-profile-1-padmasri-ivf', 'lab_test', NULL, NULL, 2429.00, 1943.20),
 ('TB -PCR', 'tb-pcr', 'lab_test', NULL, NULL, 2200.00, 1760.00),
 ('TB Quantiferon', 'tb-quantiferon', 'lab_test', NULL, NULL, 3680.00, 2944.00),
 ('TB-Gold', 'tb-gold', 'lab_test', NULL, NULL, 2900.00, 2320.00),
 ('Testosterone, Free', 'testosterone-free', 'lab_test', NULL, NULL, 1800.00, 1440.00),
 ('Testosterone, Total', 'testosterone-total', 'lab_test', NULL, NULL, 920.00, 736.00),
 ('Thyroglobulin,Serum', 'thyroglobulin-serum', 'lab_test', NULL, NULL, 2300.00, 1840.00),
 ('Thyroid Antibodies (TG,TPO)', 'thyroid-antibodies-tg-tpo', 'lab_test', NULL, NULL, 2700.00, 2160.00),
 ('Thyroid Peroxidase Antibodies (TPO, Microsomal)', 'thyroid-peroxidase-antibodies-tpo-microsomal', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Thyroid Profile (T3,T4,TSH)', 'thyroid-profile-t3-t4-tsh', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Thyroid Stimulating Hormone (TSH)', 'thyroid-stimulating-hormone-tsh', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Thyroxine, Free (F-T4)', 'thyroxine-free-f-t4', 'lab_test', NULL, NULL, 350.00, 280.00),
 ('Thyroxine, Total (T4)', 'thyroxine-total-t4', 'lab_test', NULL, NULL, 150.00, 120.00),
 ('Tissue Transglutaminase Antibody IgA, Serum', 'tissue-transglutaminase-antibody-iga-serum', 'lab_test', NULL, NULL, 3570.00, 2856.00),
 ('Tissue Transglutaminase IgG Antibody', 'tissue-transglutaminase-igg-antibody', 'lab_test', NULL, NULL, 3570.00, 2856.00),
 ('Torch Profile - 10', 'torch-profile-10', 'lab_test', NULL, NULL, 3200.00, 2560.00),
 ('Torch Profile - 4 IgM', 'torch-profile-4-igm', 'lab_test', NULL, NULL, 2040.00, 1632.00),
 ('Total IGE', 'total-ige', 'lab_test', NULL, NULL, 1200.00, 960.00),
 ('Total Iron Binding Capacity (TIBC)', 'total-iron-binding-capacity-tibc', 'lab_test', NULL, NULL, 510.00, 408.00),
 ('TOTAL LFT', 'total-lft', 'lab_test', NULL, NULL, 750.00, 600.00),
 ('Toxoplasma IgG Antibody', 'toxoplasma-igg-antibody', 'lab_test', NULL, NULL, 920.00, 736.00),
 ('Toxoplasma IgM Antibody', 'toxoplasma-igm-antibody', 'lab_test', NULL, NULL, 700.00, 560.00),
 ('Transferrin', 'transferrin', 'lab_test', NULL, NULL, 1300.00, 1040.00),
 ('Transferrin Saturation', 'transferrin-saturation', 'lab_test', NULL, NULL, 720.00, 576.00),
 ('Tread Mill Test (TMT)', 'tread-mill-test-tmt', 'lab_test', NULL, NULL, 1600.00, 1280.00),
 ('Treponema Pallidum Haemagglutination Assay (TPHA)', 'treponema-pallidum-haemagglutination-assay-tpha', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('TRIDOT', 'tridot', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Triglycerides', 'triglycerides', 'lab_test', NULL, NULL, 350.00, 280.00),
 ('Triidothyronine, Free (F-T3)', 'triidothyronine-free-f-t3', 'lab_test', NULL, NULL, 350.00, 280.00),
 ('Triidothyronine, Total (T3)', 'triidothyronine-total-t3', 'lab_test', NULL, NULL, 250.00, 200.00),
 ('Triple Marker', 'triple-marker', 'lab_test', NULL, NULL, 3060.00, 2448.00),
 ('Triple Marker Graph', 'triple-marker-graph', 'lab_test', NULL, NULL, 2900.00, 2320.00),
 ('Troponin-I', 'troponin-i', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('Troponin-T', 'troponin-t', 'lab_test', NULL, NULL, 1500.00, 1200.00),
 ('Trus Guided Prostate Biopsy', 'trus-guided-prostate-biopsy', 'lab_test', NULL, NULL, 7000.00, 5600.00),
 ('TSH Receptor Antibodies (LATS-TSI), Serum', 'tsh-receptor-antibodies-lats-tsi-serum', 'lab_test', NULL, NULL, 5100.00, 4080.00),
 ('Tuberculin Skin Test (Mantoux)', 'tuberculin-skin-test-mantoux', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Typhi. IgM Antibody', 'typhi-igm-antibody', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Urea, Serum', 'urea-serum', 'lab_test', NULL, NULL, 120.00, 96.00),
 ('Urea, Urine 24H', 'urea-urine-24h', 'lab_test', NULL, NULL, 400.00, 320.00),
 ('Uric Acid, Serum', 'uric-acid-serum', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Urine Cotinine', 'urine-cotinine', 'lab_test', NULL, NULL, 500.00, 400.00),
 ('Urine Routine', 'urine-routine', 'lab_test', NULL, NULL, 100.00, 80.00),
 ('Valproic Acid', 'valproic-acid', 'lab_test', NULL, NULL, 1230.00, 984.00),
 ('Vanillyl Mandelic Acid (VMA), Urine 24H', 'vanillyl-mandelic-acid-vma-urine-24h', 'lab_test', NULL, NULL, 3900.00, 3120.00),
 ('VDRL (RPR), CSF', 'vdrl-rpr-csf', 'lab_test', NULL, NULL, 310.00, 248.00),
 ('VDRL (RPR), Serum', 'vdrl-rpr-serum', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Vitamin -A (Retinol), Serum', 'vitamin-a-retinol-serum', 'lab_test', NULL, NULL, 4590.00, 3672.00),
 ('Vitamin B1 (Thaimine),Blood', 'vitamin-b1-thaimine-blood', 'lab_test', NULL, NULL, 3570.00, 2856.00),
 ('Vitamin B12 (Cyanocobalamine),Serum', 'vitamin-b12-cyanocobalamine-serum', 'lab_test', NULL, NULL, 1000.00, 800.00),
 ('Vitamin B2 (Riboflavin), Serum', 'vitamin-b2-riboflavin-serum', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('Vitamin B6 (Pyridoxin), Serum', 'vitamin-b6-pyridoxin-serum', 'lab_test', NULL, NULL, 3570.00, 2856.00),
 ('Vitamin C (Ascorbic Acid)', 'vitamin-c-ascorbic-acid', 'lab_test', NULL, NULL, 4080.00, 3264.00),
 ('Vitamin E (Tocopherol), Serum', 'vitamin-e-tocopherol-serum', 'lab_test', NULL, NULL, 4590.00, 3672.00),
 ('Vitamin K1', 'vitamin-k1', 'lab_test', NULL, NULL, 6000.00, 4800.00),
 ('Weil Feilx Test', 'weil-feilx-test', 'lab_test', NULL, NULL, 1530.00, 1224.00),
 ('Western Blot Test For HIV- 1', 'western-blot-test-for-hiv-1', 'lab_test', NULL, NULL, 3700.00, 2960.00),
 ('Widal Test, Slide Method', 'widal-test-slide-method', 'lab_test', NULL, NULL, 200.00, 160.00),
 ('Zinc, Serum', 'zinc-serum', 'lab_test', NULL, NULL, 3300.00, 2640.00),
 ('Zinc, Urine 24H', 'zinc-urine-24h', 'lab_test', NULL, NULL, 2570.00, 2056.00),
 ('Initial Physiotherapy Assessment & Treatment Planning', 'initial-physiotherapy-assessment-treatment-planning', 'physiotherapy', 'Assessment', 'Per Visit', 500.00, NULL),
 ('Follow-up Physiotherapy Assessment', 'follow-up-physiotherapy-assessment', 'physiotherapy', 'Assessment', 'Per Visit', 300.00, NULL),
 ('Posture & Gait Analysis', 'posture-gait-analysis', 'physiotherapy', 'Assessment', 'Per Assessment', 800.00, NULL),
 ('Ergonomic Assessment', 'ergonomic-assessment', 'physiotherapy', 'Assessment', 'Per Assessment', 800.00, NULL),
 ('Fall Risk Assessment', 'fall-risk-assessment', 'physiotherapy', 'Assessment', 'Per Assessment', 800.00, NULL),
 ('Therapeutic Exercise Session', 'therapeutic-exercise-session', 'physiotherapy', 'General', 'Per Session', 400.00, NULL),
 ('Strengthening Exercise Therapy', 'strengthening-exercise-therapy', 'physiotherapy', 'General', 'Per Session', 400.00, NULL),
 ('Stretching & Flexibility Therapy', 'stretching-flexibility-therapy', 'physiotherapy', 'General', 'Per Session', 400.00, NULL),
 ('Mobility Training', 'mobility-training', 'physiotherapy', 'General', 'Per Session', 400.00, NULL),
 ('Balance Training', 'balance-training', 'physiotherapy', 'General', 'Per Session', 400.00, NULL),
 ('Coordination Training', 'coordination-training', 'physiotherapy', 'General', 'Per Session', 400.00, NULL),
 ('Breathing & Relaxation Exercises', 'breathing-relaxation-exercises', 'physiotherapy', 'General', 'Per Session', 400.00, NULL),
 ('Soft Tissue Mobilization', 'soft-tissue-mobilization', 'physiotherapy', 'Manual Therapy', 'Per Session', 500.00, NULL),
 ('Myofascial Release', 'myofascial-release', 'physiotherapy', 'Manual Therapy', 'Per Session', 500.00, NULL),
 ('Trigger Point Therapy', 'trigger-point-therapy', 'physiotherapy', 'Manual Therapy', 'Per Session', 500.00, NULL),
 ('Therapeutic Deep Tissue Massage', 'therapeutic-deep-tissue-massage', 'physiotherapy', 'Manual Therapy', 'Per Session', 800.00, NULL),
 ('Joint Mobilization', 'joint-mobilization', 'physiotherapy', 'Manual Therapy', 'Per Session', 800.00, NULL),
 ('Spinal Mobilization', 'spinal-mobilization', 'physiotherapy', 'Manual Therapy', 'Per Session', 800.00, NULL),
 ('Manual Lymphatic Drainage', 'manual-lymphatic-drainage', 'physiotherapy', 'Manual Therapy', 'Per Session', 800.00, NULL),
 ('TENS Therapy', 'tens-therapy', 'physiotherapy', 'Electrotherapy', 'Per Session', 300.00, NULL),
 ('IFT Therapy', 'ift-therapy', 'physiotherapy', 'Electrotherapy', 'Per Session', 300.00, NULL),
 ('Ultrasound Therapy', 'ultrasound-therapy', 'physiotherapy', 'Electrotherapy', 'Per Session', 300.00, NULL),
 ('Electrical Muscle Stimulation (EMS)', 'electrical-muscle-stimulation-ems', 'physiotherapy', 'Electrotherapy', 'Per Session', 300.00, NULL),
 ('NMES Therapy', 'nmes-therapy', 'physiotherapy', 'Electrotherapy', 'Per Session', 400.00, NULL),
 ('Faradic Stimulation', 'faradic-stimulation', 'physiotherapy', 'Electrotherapy', 'Per Session', 400.00, NULL),
 ('Infrared Therapy', 'infrared-therapy', 'physiotherapy', 'Electrotherapy', 'Per Session', 300.00, NULL),
 ('Cryotherapy / Cold Therapy', 'cryotherapy-cold-therapy', 'physiotherapy', 'Electrotherapy', 'Per Session', 300.00, NULL),
 ('Wax Bath Therapy', 'wax-bath-therapy', 'physiotherapy', 'Electrotherapy', 'Per Session', 300.00, NULL),
 ('Cervical Spondylosis / Neck Pain Therapy', 'cervical-spondylosis-neck-pain-therapy', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Low Back Pain / Lumbar Spondylosis Therapy', 'low-back-pain-lumbar-spondylosis-therapy', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Sciatica Management', 'sciatica-management', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Frozen Shoulder Therapy', 'frozen-shoulder-therapy', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Rotator Cuff Rehabilitation', 'rotator-cuff-rehabilitation', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Knee Pain / Osteoarthritis Therapy', 'knee-pain-osteoarthritis-therapy', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Ankle & Foot Rehabilitation', 'ankle-foot-rehabilitation', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Hip Pain Rehabilitation', 'hip-pain-rehabilitation', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Arthritis Rehabilitation', 'arthritis-rehabilitation', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Tennis Elbow / Golfer''s Elbow Therapy', 'tennis-elbow-golfer-s-elbow-therapy', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('Plantar Fasciitis Therapy', 'plantar-fasciitis-therapy', 'physiotherapy', 'Orthopaedic', 'Per Session', 500.00, NULL),
 ('TMJ Physiotherapy', 'tmj-physiotherapy', 'physiotherapy', 'Orthopaedic', 'Per Session', 600.00, NULL),
 ('Post-Operative Orthopaedic Rehabilitation', 'post-operative-orthopaedic-rehabilitation', 'physiotherapy', 'Post-Operative', 'Per Session', 600.00, NULL),
 ('Knee Replacement Rehabilitation', 'knee-replacement-rehabilitation', 'physiotherapy', 'Post-Operative', 'Per Session', 600.00, NULL),
 ('Hip Replacement Rehabilitation', 'hip-replacement-rehabilitation', 'physiotherapy', 'Post-Operative', 'Per Session', 600.00, NULL),
 ('Spine Surgery Rehabilitation', 'spine-surgery-rehabilitation', 'physiotherapy', 'Post-Operative', 'Per Session', 600.00, NULL),
 ('Fracture Rehabilitation', 'fracture-rehabilitation', 'physiotherapy', 'Post-Operative', 'Per Session', 500.00, NULL),
 ('ACL / Ligament Rehabilitation', 'acl-ligament-rehabilitation', 'physiotherapy', 'Post-Operative', 'Per Session', 600.00, NULL),
 ('Stroke Rehabilitation', 'stroke-rehabilitation', 'physiotherapy', 'Neurological', 'Per Session', 700.00, NULL),
 ('Parkinson''s Disease Physiotherapy', 'parkinson-s-disease-physiotherapy', 'physiotherapy', 'Neurological', 'Per Session', 700.00, NULL),
 ('Spinal Cord Injury Rehabilitation', 'spinal-cord-injury-rehabilitation', 'physiotherapy', 'Neurological', 'Per Session', 700.00, NULL),
 ('Multiple Sclerosis Rehabilitation', 'multiple-sclerosis-rehabilitation', 'physiotherapy', 'Neurological', 'Per Session', 700.00, NULL),
 ('Cerebral Palsy Rehabilitation', 'cerebral-palsy-rehabilitation', 'physiotherapy', 'Neurological', 'Per Session', 700.00, NULL),
 ('Facial Palsy / Bell''s Palsy Therapy', 'facial-palsy-bell-s-palsy-therapy', 'physiotherapy', 'Neurological', 'Per Session', 500.00, NULL),
 ('Vestibular Rehabilitation', 'vestibular-rehabilitation', 'physiotherapy', 'Neurological', 'Per Session', 600.00, NULL),
 ('Gait Training', 'gait-training', 'physiotherapy', 'Neurological', 'Per Session', 600.00, NULL),
 ('Motor Relearning Programme', 'motor-relearning-programme', 'physiotherapy', 'Neurological', 'Per Session', 700.00, NULL),
 ('Neuromuscular Re-education', 'neuromuscular-re-education', 'physiotherapy', 'Neurological', 'Per Session', 600.00, NULL),
 ('Breathing Exercises', 'breathing-exercises', 'physiotherapy', 'Cardiopulmonary', 'Per Session', 400.00, NULL),
 ('Chest Physiotherapy', 'chest-physiotherapy', 'physiotherapy', 'Cardiopulmonary', 'Per Session', 500.00, NULL),
 ('Post-ICU Rehabilitation', 'post-icu-rehabilitation', 'physiotherapy', 'Cardiopulmonary', 'Per Session', 800.00, NULL),
 ('Post-COVID Rehabilitation', 'post-covid-rehabilitation', 'physiotherapy', 'Cardiopulmonary', 'Per Session', 600.00, NULL),
 ('Geriatric Physiotherapy Assessment', 'geriatric-physiotherapy-assessment', 'physiotherapy', 'Geriatric', 'Per Assessment', 600.00, NULL),
 ('Fall Prevention Programme', 'fall-prevention-programme', 'physiotherapy', 'Geriatric', 'Per Session', 500.00, NULL),
 ('Age-Related Weakness Rehabilitation', 'age-related-weakness-rehabilitation', 'physiotherapy', 'Geriatric', 'Per Session', 500.00, NULL),
 ('Elderly Mobility & Walking Training', 'elderly-mobility-walking-training', 'physiotherapy', 'Geriatric', 'Per Session', 500.00, NULL),
 ('Paediatric Physiotherapy Assessment', 'paediatric-physiotherapy-assessment', 'physiotherapy', 'Paediatric', 'Per Assessment', 600.00, NULL),
 ('Developmental Delay Therapy', 'developmental-delay-therapy', 'physiotherapy', 'Paediatric', 'Per Session', 700.00, NULL),
 ('Cerebral Palsy Physiotherapy', 'cerebral-palsy-physiotherapy', 'physiotherapy', 'Paediatric', 'Per Session', 700.00, NULL),
 ('Torticollis Therapy', 'torticollis-therapy', 'physiotherapy', 'Paediatric', 'Per Session', 500.00, NULL),
 ('Gross Motor Skill Training', 'gross-motor-skill-training', 'physiotherapy', 'Paediatric', 'Per Session', 600.00, NULL),
 ('Antenatal Physiotherapy', 'antenatal-physiotherapy', 'physiotherapy', 'Women''s Health', 'Per Session', 600.00, NULL),
 ('Postnatal Physiotherapy', 'postnatal-physiotherapy', 'physiotherapy', 'Women''s Health', 'Per Session', 600.00, NULL),
 ('Pelvic Floor Muscle Training', 'pelvic-floor-muscle-training', 'physiotherapy', 'Women''s Health', 'Per Session', 700.00, NULL),
 ('Urinary Incontinence Physiotherapy', 'urinary-incontinence-physiotherapy', 'physiotherapy', 'Women''s Health', 'Per Session', 700.00, NULL),
 ('Post-Caesarean Rehabilitation', 'post-caesarean-rehabilitation', 'physiotherapy', 'Women''s Health', 'Per Session', 600.00, NULL),
 ('Diastasis Recti Rehabilitation', 'diastasis-recti-rehabilitation', 'physiotherapy', 'Women''s Health', 'Per Session', 600.00, NULL),
 ('Chronic Pain Management Programme', 'chronic-pain-management-programme', 'physiotherapy', 'Pain Management', 'Per Session', 600.00, NULL),
 ('Acute Pain Physiotherapy', 'acute-pain-physiotherapy', 'physiotherapy', 'Pain Management', 'Per Session', 500.00, NULL),
 ('Headache & Migraine Physiotherapy', 'headache-migraine-physiotherapy', 'physiotherapy', 'Pain Management', 'Per Session', 500.00, NULL),
 ('Fibromyalgia Management', 'fibromyalgia-management', 'physiotherapy', 'Pain Management', 'Per Session', 600.00, NULL),
 ('Sports Injury Assessment', 'sports-injury-assessment', 'physiotherapy', 'Sports', 'Per Assessment', 700.00, NULL),
 ('Sports Injury Rehabilitation', 'sports-injury-rehabilitation', 'physiotherapy', 'Sports', 'Per Session', 600.00, NULL),
 ('Sports Performance Conditioning', 'sports-performance-conditioning', 'physiotherapy', 'Sports', 'Per Session', 700.00, NULL),
 ('Return-to-Sport Programme', 'return-to-sport-programme', 'physiotherapy', 'Sports', 'Per Session', 700.00, NULL),
 ('Kinesio Taping', 'kinesio-taping', 'physiotherapy', 'Sports', 'Per Application', 300.00, NULL),
 ('Sports Massage', 'sports-massage', 'physiotherapy', 'Sports', 'Per Session', 700.00, NULL),
 ('Cervical Traction Therapy', 'cervical-traction-therapy', 'physiotherapy', 'Special Techniques', 'Per Session', 400.00, NULL),
 ('Lumbar Traction Therapy', 'lumbar-traction-therapy', 'physiotherapy', 'Special Techniques', 'Per Session', 400.00, NULL),
 ('Home Physiotherapy – Standard Session', 'home-physiotherapy-standard-session', 'physiotherapy', 'Home Service', 'Per Visit', 800.00, NULL),
 ('Home Physiotherapy – Senior Citizen', 'home-physiotherapy-senior-citizen', 'physiotherapy', 'Home Service', 'Per Visit', 800.00, NULL),
 ('Home Physiotherapy – Post-Operative', 'home-physiotherapy-post-operative', 'physiotherapy', 'Home Service', 'Per Visit', 1000.00, NULL),
 ('Home Physiotherapy – Stroke / Neurological', 'home-physiotherapy-stroke-neurological', 'physiotherapy', 'Home Service', 'Per Visit', 1000.00, NULL),
 ('Home Physiotherapy – Bedridden Patient', 'home-physiotherapy-bedridden-patient', 'physiotherapy', 'Home Service', 'Per Visit', 1000.00, NULL),
 ('Home Physiotherapy – Paediatric', 'home-physiotherapy-paediatric', 'physiotherapy', 'Home Service', 'Per Visit', 800.00, NULL),
 ('Emergency / Same-Day Home Visit', 'emergency-same-day-home-visit', 'physiotherapy', 'Home Service', 'Per Visit', 1000.00, NULL),
 ('Dental Consultation & Comprehensive Oral Examination', 'dental-consultation-comprehensive-oral-examination', 'dental', 'General Dentistry', NULL, 500.00, NULL),
 ('Emergency Dental Consultation', 'emergency-dental-consultation', 'dental', 'General Dentistry', NULL, 700.00, NULL),
 ('Preventive Dental Care', 'preventive-dental-care', 'dental', 'General Dentistry', NULL, 500.00, NULL),
 ('Oral Hygiene Instructions', 'oral-hygiene-instructions', 'dental', 'General Dentistry', NULL, 300.00, NULL),
 ('Dental Health Education & Counselling', 'dental-health-education-counselling', 'dental', 'General Dentistry', NULL, 300.00, NULL),
 ('Dental Screening Camps', 'dental-screening-camps', 'dental', 'General Dentistry', NULL, 250.00, NULL),
 ('Routine Dental Check-up', 'routine-dental-check-up', 'dental', 'General Dentistry', NULL, 500.00, NULL),
 ('Dental Treatment Planning', 'dental-treatment-planning', 'dental', 'General Dentistry', NULL, 500.00, NULL),
 ('Second Opinion Services', 'second-opinion-services', 'dental', 'General Dentistry', NULL, 750.00, NULL),
 ('Digital Dental Records & Documentation', 'digital-dental-records-documentation', 'dental', 'General Dentistry', NULL, 200.00, NULL),
 ('Intraoral Examination', 'intraoral-examination', 'dental', 'Diagnostic Dentistry', NULL, 300.00, NULL),
 ('Dental Photography', 'dental-photography', 'dental', 'Diagnostic Dentistry', NULL, 500.00, NULL),
 ('Intraoral Camera Examination', 'intraoral-camera-examination', 'dental', 'Diagnostic Dentistry', NULL, 750.00, NULL),
 ('Dental Radiography', 'dental-radiography', 'dental', 'Diagnostic Dentistry', NULL, 300.00, NULL),
 ('IOPA X-Ray', 'iopa-x-ray', 'dental', 'Diagnostic Dentistry', NULL, 300.00, NULL),
 ('Bitewing X-Ray', 'bitewing-x-ray', 'dental', 'Diagnostic Dentistry', NULL, 500.00, NULL),
 ('Occlusal X-Ray', 'occlusal-x-ray', 'dental', 'Diagnostic Dentistry', NULL, 500.00, NULL),
 ('OPG / Panoramic Radiography', 'opg-panoramic-radiography', 'dental', 'Diagnostic Dentistry', NULL, 1000.00, NULL),
 ('Cephalometric Radiography', 'cephalometric-radiography', 'dental', 'Diagnostic Dentistry', NULL, 1200.00, NULL),
 ('CBCT / 3D Dental Imaging', 'cbct-3d-dental-imaging', 'dental', 'Diagnostic Dentistry', NULL, 3000.00, NULL),
 ('TMJ Imaging', 'tmj-imaging', 'dental', 'Diagnostic Dentistry', NULL, 2500.00, NULL),
 ('Digital Radiology', 'digital-radiology', 'dental', 'Diagnostic Dentistry', NULL, 500.00, NULL),
 ('Dental Pulp Vitality Testing', 'dental-pulp-vitality-testing', 'dental', 'Diagnostic Dentistry', NULL, 500.00, NULL),
 ('Periodontal Probing', 'periodontal-probing', 'dental', 'Diagnostic Dentistry', NULL, 500.00, NULL),
 ('Occlusal Analysis', 'occlusal-analysis', 'dental', 'Diagnostic Dentistry', NULL, 1000.00, NULL),
 ('Salivary Testing', 'salivary-testing', 'dental', 'Diagnostic Dentistry', NULL, 1500.00, NULL),
 ('Oral Cancer Screening', 'oral-cancer-screening', 'dental', 'Diagnostic Dentistry', NULL, 1000.00, NULL),
 ('Dental Cleaning / Scaling', 'dental-cleaning-scaling', 'dental', 'Preventive Dentistry', NULL, 1500.00, NULL),
 ('Polishing', 'polishing', 'dental', 'Preventive Dentistry', NULL, 750.00, NULL),
 ('Fluoride Application', 'fluoride-application', 'dental', 'Preventive Dentistry', NULL, 750.00, NULL),
 ('Pit & Fissure Sealants', 'pit-fissure-sealants', 'dental', 'Preventive Dentistry', NULL, 1000.00, NULL),
 ('Preventive Resin Restoration', 'preventive-resin-restoration', 'dental', 'Preventive Dentistry', NULL, 1500.00, NULL),
 ('Caries Risk Assessment', 'caries-risk-assessment', 'dental', 'Preventive Dentistry', NULL, 500.00, NULL),
 ('Oral Hygiene Counselling', 'oral-hygiene-counselling', 'dental', 'Preventive Dentistry', NULL, 300.00, NULL),
 ('Diet Counselling for Dental Health', 'diet-counselling-for-dental-health', 'dental', 'Preventive Dentistry', NULL, 500.00, NULL),
 ('Preventive Dental Programmes', 'preventive-dental-programmes', 'dental', 'Preventive Dentistry', NULL, 1000.00, NULL),
 ('Dental Fillings', 'dental-fillings', 'dental', 'Restorative / Conservative Dentistry', NULL, 1200.00, NULL),
 ('Composite Restorations', 'composite-restorations', 'dental', 'Restorative / Conservative Dentistry', NULL, 1500.00, NULL),
 ('GIC Restorations', 'gic-restorations', 'dental', 'Restorative / Conservative Dentistry', NULL, 1000.00, NULL),
 ('Amalgam Restorations', 'amalgam-restorations', 'dental', 'Restorative / Conservative Dentistry', NULL, 1000.00, NULL),
 ('Temporary Restorations', 'temporary-restorations', 'dental', 'Restorative / Conservative Dentistry', NULL, 500.00, NULL),
 ('Inlays', 'inlays', 'dental', 'Restorative / Conservative Dentistry', NULL, 6000.00, NULL),
 ('Onlays', 'onlays', 'dental', 'Restorative / Conservative Dentistry', NULL, 7000.00, NULL),
 ('Tooth-Coloured Restorations', 'tooth-coloured-restorations', 'dental', 'Restorative / Conservative Dentistry', NULL, 1500.00, NULL),
 ('Diastema Closure', 'diastema-closure', 'dental', 'Restorative / Conservative Dentistry', NULL, 3000.00, NULL),
 ('Tooth Reconstruction', 'tooth-reconstruction', 'dental', 'Restorative / Conservative Dentistry', NULL, 5000.00, NULL),
 ('Management of Tooth Wear', 'management-of-tooth-wear', 'dental', 'Restorative / Conservative Dentistry', NULL, 2500.00, NULL),
 ('Management of Dental Erosion', 'management-of-dental-erosion', 'dental', 'Restorative / Conservative Dentistry', NULL, 2500.00, NULL),
 ('Management of Abrasion', 'management-of-abrasion', 'dental', 'Restorative / Conservative Dentistry', NULL, 2000.00, NULL),
 ('Management of Abfraction', 'management-of-abfraction', 'dental', 'Restorative / Conservative Dentistry', NULL, 2000.00, NULL),
 ('Root Canal Treatment (RCT)', 'root-canal-treatment-rct', 'dental', 'Endodontics / Root Canal Treatment', NULL, 6000.00, NULL),
 ('Single-Visit RCT', 'single-visit-rct', 'dental', 'Endodontics / Root Canal Treatment', NULL, 7000.00, NULL),
 ('Multi-Visit RCT', 'multi-visit-rct', 'dental', 'Endodontics / Root Canal Treatment', NULL, 6000.00, NULL),
 ('Re-Root Canal Treatment', 're-root-canal-treatment', 'dental', 'Endodontics / Root Canal Treatment', NULL, 10000.00, NULL),
 ('Pulpotomy', 'pulpotomy', 'dental', 'Endodontics / Root Canal Treatment', NULL, 2500.00, NULL),
 ('Pulpectomy', 'pulpectomy', 'dental', 'Endodontics / Root Canal Treatment', NULL, 3000.00, NULL),
 ('Apexification', 'apexification', 'dental', 'Endodontics / Root Canal Treatment', NULL, 5000.00, NULL),
 ('Apexogenesis', 'apexogenesis', 'dental', 'Endodontics / Root Canal Treatment', NULL, 5000.00, NULL),
 ('Apicoectomy', 'apicoectomy', 'dental', 'Endodontics / Root Canal Treatment', NULL, 10000.00, NULL),
 ('Perforation Repair', 'perforation-repair', 'dental', 'Endodontics / Root Canal Treatment', NULL, 8000.00, NULL),
 ('Internal Resorption Management', 'internal-resorption-management', 'dental', 'Endodontics / Root Canal Treatment', NULL, 10000.00, NULL),
 ('External Resorption Management', 'external-resorption-management', 'dental', 'Endodontics / Root Canal Treatment', NULL, 10000.00, NULL),
 ('Trauma-Related Endodontic Treatment', 'trauma-related-endodontic-treatment', 'dental', 'Endodontics / Root Canal Treatment', NULL, 7000.00, NULL),
 ('Emergency Pulpal Treatment', 'emergency-pulpal-treatment', 'dental', 'Endodontics / Root Canal Treatment', NULL, 2500.00, NULL),
 ('Post & Core Placement', 'post-core-placement', 'dental', 'Endodontics / Root Canal Treatment', NULL, 3000.00, NULL),
 ('Complete Dentures', 'complete-dentures', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 15000.00, NULL),
 ('Partial Dentures', 'partial-dentures', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 8000.00, NULL),
 ('Flexible Dentures', 'flexible-dentures', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 12000.00, NULL),
 ('Acrylic Dentures', 'acrylic-dentures', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 8000.00, NULL),
 ('Metal Framework Dentures', 'metal-framework-dentures', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 25000.00, NULL),
 ('Immediate Dentures', 'immediate-dentures', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 12000.00, NULL),
 ('Overdentures', 'overdentures', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 25000.00, NULL),
 ('Fixed Partial Dentures', 'fixed-partial-dentures', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 15000.00, NULL),
 ('Dental Bridges', 'dental-bridges', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 15000.00, NULL),
 ('Metal-Ceramic Crowns', 'metal-ceramic-crowns', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 8000.00, NULL),
 ('All-Ceramic Crowns', 'all-ceramic-crowns', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 12000.00, NULL),
 ('Zirconia Crowns', 'zirconia-crowns', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 15000.00, NULL),
 ('E-Max Restorations', 'e-max-restorations', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 18000.00, NULL),
 ('Veneers', 'veneers', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 12000.00, NULL),
 ('Inlays & Onlays', 'inlays-onlays', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 7000.00, NULL),
 ('Implant-Supported Prosthesis', 'implant-supported-prosthesis', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 40000.00, NULL),
 ('Full-Mouth Rehabilitation', 'full-mouth-rehabilitation', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 200000.00, NULL),
 ('Occlusal Rehabilitation', 'occlusal-rehabilitation', 'dental', 'Prosthodontics / Replacement of Missing Teeth', NULL, 50000.00, NULL),
 ('Dental Implant Consultation', 'dental-implant-consultation', 'dental', 'Dental Implantology', NULL, 1000.00, NULL),
 ('Implant Treatment Planning', 'implant-treatment-planning', 'dental', 'Dental Implantology', NULL, 2000.00, NULL),
 ('Single-Tooth Implant', 'single-tooth-implant', 'dental', 'Dental Implantology', NULL, 35000.00, NULL),
 ('Multiple Dental Implants', 'multiple-dental-implants', 'dental', 'Dental Implantology', NULL, 30000.00, NULL),
 ('Full-Mouth Implant Rehabilitation', 'full-mouth-implant-rehabilitation', 'dental', 'Dental Implantology', NULL, 300000.00, NULL),
 ('Immediate Implant Placement', 'immediate-implant-placement', 'dental', 'Dental Implantology', NULL, 40000.00, NULL),
 ('Implant-Supported Crown', 'implant-supported-crown', 'dental', 'Dental Implantology', NULL, 15000.00, NULL),
 ('Implant-Supported Bridge', 'implant-supported-bridge', 'dental', 'Dental Implantology', NULL, 40000.00, NULL),
 ('Implant-Supported Denture', 'implant-supported-denture', 'dental', 'Dental Implantology', NULL, 80000.00, NULL),
 ('All-on-4 Treatment', 'all-on-4-treatment', 'dental', 'Dental Implantology', NULL, 250000.00, NULL),
 ('All-on-6 Treatment', 'all-on-6-treatment', 'dental', 'Dental Implantology', NULL, 350000.00, NULL),
 ('Bone Grafting', 'bone-grafting', 'dental', 'Dental Implantology', NULL, 20000.00, NULL),
 ('Sinus Lift Procedure', 'sinus-lift-procedure', 'dental', 'Dental Implantology', NULL, 30000.00, NULL),
 ('Guided Bone Regeneration', 'guided-bone-regeneration', 'dental', 'Dental Implantology', NULL, 20000.00, NULL),
 ('Implant Maintenance', 'implant-maintenance', 'dental', 'Dental Implantology', NULL, 2000.00, NULL),
 ('Management of Peri-Implantitis', 'management-of-peri-implantitis', 'dental', 'Dental Implantology', NULL, 10000.00, NULL),
 ('Failed Implant Management', 'failed-implant-management', 'dental', 'Dental Implantology', NULL, 15000.00, NULL),
 ('Gum Disease Screening', 'gum-disease-screening', 'dental', 'Periodontics / Gum Care', NULL, 500.00, NULL),
 ('Gingivitis Treatment', 'gingivitis-treatment', 'dental', 'Periodontics / Gum Care', NULL, 1500.00, NULL),
 ('Periodontitis Treatment', 'periodontitis-treatment', 'dental', 'Periodontics / Gum Care', NULL, 5000.00, NULL),
 ('Scaling & Root Planing', 'scaling-root-planing', 'dental', 'Periodontics / Gum Care', NULL, 3000.00, NULL),
 ('Deep Cleaning', 'deep-cleaning', 'dental', 'Periodontics / Gum Care', NULL, 3000.00, NULL),
 ('Periodontal Pocket Treatment', 'periodontal-pocket-treatment', 'dental', 'Periodontics / Gum Care', NULL, 5000.00, NULL),
 ('Gum Disease Maintenance', 'gum-disease-maintenance', 'dental', 'Periodontics / Gum Care', NULL, 2000.00, NULL),
 ('Periodontal Splinting', 'periodontal-splinting', 'dental', 'Periodontics / Gum Care', NULL, 5000.00, NULL),
 ('Gum Grafting', 'gum-grafting', 'dental', 'Periodontics / Gum Care', NULL, 15000.00, NULL),
 ('Crown Lengthening', 'crown-lengthening', 'dental', 'Periodontics / Gum Care', NULL, 10000.00, NULL),
 ('Gingivectomy', 'gingivectomy', 'dental', 'Periodontics / Gum Care', NULL, 8000.00, NULL),
 ('Gingivoplasty', 'gingivoplasty', 'dental', 'Periodontics / Gum Care', NULL, 8000.00, NULL),
 ('Flap Surgery', 'flap-surgery', 'dental', 'Periodontics / Gum Care', NULL, 15000.00, NULL),
 ('Regenerative Periodontal Surgery', 'regenerative-periodontal-surgery', 'dental', 'Periodontics / Gum Care', NULL, 20000.00, NULL),
 ('Treatment of Gum Recession', 'treatment-of-gum-recession', 'dental', 'Periodontics / Gum Care', NULL, 15000.00, NULL),
 ('Periodontal Maintenance Programme', 'periodontal-maintenance-programme', 'dental', 'Periodontics / Gum Care', NULL, 3000.00, NULL),
 ('Simple Tooth Extraction', 'simple-tooth-extraction', 'dental', 'Oral & Maxillofacial Surgery', NULL, 1000.00, NULL),
 ('Surgical Tooth Extraction', 'surgical-tooth-extraction', 'dental', 'Oral & Maxillofacial Surgery', NULL, 3000.00, NULL),
 ('Wisdom Tooth Removal', 'wisdom-tooth-removal', 'dental', 'Oral & Maxillofacial Surgery', NULL, 5000.00, NULL),
 ('Impacted Tooth Removal', 'impacted-tooth-removal', 'dental', 'Oral & Maxillofacial Surgery', NULL, 10000.00, NULL),
 ('Surgical Removal of Root Fragments', 'surgical-removal-of-root-fragments', 'dental', 'Oral & Maxillofacial Surgery', NULL, 3000.00, NULL),
 ('Alveoloplasty', 'alveoloplasty', 'dental', 'Oral & Maxillofacial Surgery', NULL, 8000.00, NULL),
 ('Frenectomy', 'frenectomy', 'dental', 'Oral & Maxillofacial Surgery', NULL, 8000.00, NULL),
 ('Biopsy Procedures', 'biopsy-procedures', 'dental', 'Oral & Maxillofacial Surgery', NULL, 5000.00, NULL),
 ('Cyst Removal', 'cyst-removal', 'dental', 'Oral & Maxillofacial Surgery', NULL, 15000.00, NULL),
 ('Minor Oral Surgery', 'minor-oral-surgery', 'dental', 'Oral & Maxillofacial Surgery', NULL, 10000.00, NULL),
 ('Management of Oral Trauma', 'management-of-oral-trauma', 'dental', 'Oral & Maxillofacial Surgery', NULL, 5000.00, NULL),
 ('Management of Dental Abscess', 'management-of-dental-abscess', 'dental', 'Oral & Maxillofacial Surgery', NULL, 3000.00, NULL),
 ('Incision & Drainage', 'incision-drainage', 'dental', 'Oral & Maxillofacial Surgery', NULL, 3000.00, NULL),
 ('Pre-Prosthetic Surgery', 'pre-prosthetic-surgery', 'dental', 'Oral & Maxillofacial Surgery', NULL, 10000.00, NULL),
 ('Oral Surgical Procedures Under Local Anaesthesia', 'oral-surgical-procedures-under-local-anaesthesia', 'dental', 'Oral & Maxillofacial Surgery', NULL, 10000.00, NULL),
 ('Oral Surgical Procedures Under Sedation / General Anaesthesia', 'oral-surgical-procedures-under-sedation-general-anaesthesia', 'dental', 'Oral & Maxillofacial Surgery', NULL, 25000.00, NULL),
 ('Orthodontic Consultation', 'orthodontic-consultation', 'dental', 'Orthodontics', NULL, 1000.00, NULL),
 ('Child Orthodontic Assessment', 'child-orthodontic-assessment', 'dental', 'Orthodontics', NULL, 1000.00, NULL),
 ('Adult Orthodontic Treatment', 'adult-orthodontic-treatment', 'dental', 'Orthodontics', NULL, 50000.00, NULL),
 ('Fixed Braces', 'fixed-braces', 'dental', 'Orthodontics', NULL, 40000.00, NULL),
 ('Metal Braces', 'metal-braces', 'dental', 'Orthodontics', NULL, 40000.00, NULL),
 ('Ceramic Braces', 'ceramic-braces', 'dental', 'Orthodontics', NULL, 60000.00, NULL),
 ('Self-Ligating Braces', 'self-ligating-braces', 'dental', 'Orthodontics', NULL, 70000.00, NULL),
 ('Lingual Braces', 'lingual-braces', 'dental', 'Orthodontics', NULL, 150000.00, NULL),
 ('Clear Aligners', 'clear-aligners', 'dental', 'Orthodontics', NULL, 100000.00, NULL),
 ('Retainers', 'retainers', 'dental', 'Orthodontics', NULL, 5000.00, NULL),
 ('Removable Appliances', 'removable-appliances', 'dental', 'Orthodontics', NULL, 5000.00, NULL),
 ('Functional Appliances', 'functional-appliances', 'dental', 'Orthodontics', NULL, 10000.00, NULL),
 ('Habit-Breaking Appliances', 'habit-breaking-appliances', 'dental', 'Orthodontics', NULL, 5000.00, NULL),
 ('Space Maintainers', 'space-maintainers', 'dental', 'Orthodontics', NULL, 5000.00, NULL),
 ('Growth Modification Treatment', 'growth-modification-treatment', 'dental', 'Orthodontics', NULL, 30000.00, NULL),
 ('Orthognathic Treatment Planning', 'orthognathic-treatment-planning', 'dental', 'Orthodontics', NULL, 25000.00, NULL),
 ('Child Dental Consultation', 'child-dental-consultation', 'dental', 'Pediatric Dentistry', NULL, 500.00, NULL),
 ('Preventive Dental Care', 'preventive-dental-care-2', 'dental', 'Pediatric Dentistry', NULL, 500.00, NULL),
 ('Fluoride Application', 'fluoride-application-2', 'dental', 'Pediatric Dentistry', NULL, 750.00, NULL),
 ('Pit & Fissure Sealants', 'pit-fissure-sealants-2', 'dental', 'Pediatric Dentistry', NULL, 1000.00, NULL),
 ('Dental Fillings for Children', 'dental-fillings-for-children', 'dental', 'Pediatric Dentistry', NULL, 1000.00, NULL),
 ('Pulpotomy', 'pulpotomy-2', 'dental', 'Pediatric Dentistry', NULL, 2500.00, NULL),
 ('Pulpectomy', 'pulpectomy-2', 'dental', 'Pediatric Dentistry', NULL, 3000.00, NULL),
 ('Stainless Steel Crowns', 'stainless-steel-crowns', 'dental', 'Pediatric Dentistry', NULL, 5000.00, NULL),
 ('Space Maintainers', 'space-maintainers-2', 'dental', 'Pediatric Dentistry', NULL, 5000.00, NULL),
 ('Management of Early Childhood Caries', 'management-of-early-childhood-caries', 'dental', 'Pediatric Dentistry', NULL, 3000.00, NULL),
 ('Dental Trauma Management', 'dental-trauma-management', 'dental', 'Pediatric Dentistry', NULL, 3000.00, NULL),
 ('Child Behaviour Management', 'child-behaviour-management', 'dental', 'Pediatric Dentistry', NULL, 1000.00, NULL),
 ('Special Needs Dentistry', 'special-needs-dentistry', 'dental', 'Pediatric Dentistry', NULL, NULL, NULL),
 ('Dental Treatment Under Sedation', 'dental-treatment-under-sedation', 'dental', 'Pediatric Dentistry', NULL, 15000.00, NULL),
 ('Smile Analysis', 'smile-analysis', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 2000.00, NULL),
 ('Smile Design', 'smile-design', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 5000.00, NULL),
 ('Teeth Whitening', 'teeth-whitening', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 12000.00, NULL),
 ('Bleaching', 'bleaching', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 12000.00, NULL),
 ('Dental Veneers', 'dental-veneers', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 12000.00, NULL),
 ('Composite Veneers', 'composite-veneers', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 5000.00, NULL),
 ('Ceramic Veneers', 'ceramic-veneers', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 15000.00, NULL),
 ('Tooth-Coloured Restorations', 'tooth-coloured-restorations-2', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 1500.00, NULL),
 ('Cosmetic Bonding', 'cosmetic-bonding', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 3000.00, NULL),
 ('Tooth Reshaping', 'tooth-reshaping', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 2000.00, NULL),
 ('Diastema Closure', 'diastema-closure-2', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 3000.00, NULL),
 ('Gum Depigmentation', 'gum-depigmentation', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 10000.00, NULL),
 ('Gingival Contouring', 'gingival-contouring', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 10000.00, NULL),
 ('Full Smile Makeover', 'full-smile-makeover', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 150000.00, NULL),
 ('Digital Smile Design', 'digital-smile-design', 'dental', 'Cosmetic / Aesthetic Dentistry', NULL, 10000.00, NULL),
 ('Oral Mucosal Disease Diagnosis', 'oral-mucosal-disease-diagnosis', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1000.00, NULL),
 ('Oral Ulcer Evaluation', 'oral-ulcer-evaluation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1000.00, NULL),
 ('White Lesion Evaluation', 'white-lesion-evaluation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1000.00, NULL),
 ('Red Lesion Evaluation', 'red-lesion-evaluation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1000.00, NULL),
 ('Oral Pigmentation Evaluation', 'oral-pigmentation-evaluation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1000.00, NULL),
 ('Burning Mouth Evaluation', 'burning-mouth-evaluation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1500.00, NULL),
 ('Oral Pain Management', 'oral-pain-management', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1000.00, NULL),
 ('Temporomandibular Joint Disorder Evaluation', 'temporomandibular-joint-disorder-evaluation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1500.00, NULL),
 ('Facial Pain Evaluation', 'facial-pain-evaluation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1500.00, NULL),
 ('Oral Cancer Screening', 'oral-cancer-screening-2', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1000.00, NULL),
 ('Pre-Cancerous Lesion Evaluation', 'pre-cancerous-lesion-evaluation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1500.00, NULL),
 ('Salivary Gland Disorder Evaluation', 'salivary-gland-disorder-evaluation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1500.00, NULL),
 ('Oral Medicine Consultation', 'oral-medicine-consultation', 'dental', 'Oral Medicine & Oral Diagnosis', NULL, 1000.00, NULL),
 ('Emergency Toothache Management', 'emergency-toothache-management', 'dental', 'Dental Emergency Services', NULL, 1500.00, NULL),
 ('Dental Abscess Management', 'dental-abscess-management', 'dental', 'Dental Emergency Services', NULL, 3000.00, NULL),
 ('Emergency Tooth Extraction', 'emergency-tooth-extraction', 'dental', 'Dental Emergency Services', NULL, 2000.00, NULL),
 ('Emergency RCT / Pulpotomy', 'emergency-rct-pulpotomy', 'dental', 'Dental Emergency Services', NULL, 3000.00, NULL),
 ('Dental Trauma Management', 'dental-trauma-management-2', 'dental', 'Dental Emergency Services', NULL, 3000.00, NULL),
 ('Broken Tooth Management', 'broken-tooth-management', 'dental', 'Dental Emergency Services', NULL, 2000.00, NULL),
 ('Dislodged Crown / Bridge Management', 'dislodged-crown-bridge-management', 'dental', 'Dental Emergency Services', NULL, 2000.00, NULL),
 ('Dental Bleeding Management', 'dental-bleeding-management', 'dental', 'Dental Emergency Services', NULL, 1500.00, NULL),
 ('Facial Swelling Management', 'facial-swelling-management', 'dental', 'Dental Emergency Services', NULL, 2000.00, NULL),
 ('Post-Operative Dental Emergency', 'post-operative-dental-emergency', 'dental', 'Dental Emergency Services', NULL, 1500.00, NULL),
 ('24-Hour Dental Emergency Service', '24-hour-dental-emergency-service', 'dental', 'Dental Emergency Services', NULL, NULL, NULL),
 ('Geriatric Dentistry', 'geriatric-dentistry', 'dental', 'Specialized Dental Services', NULL, 1000.00, NULL),
 ('Special Needs Dentistry', 'special-needs-dentistry-2', 'dental', 'Specialized Dental Services', NULL, NULL, NULL),
 ('Medically Compromised Patient Dentistry', 'medically-compromised-patient-dentistry', 'dental', 'Specialized Dental Services', NULL, 1500.00, NULL),
 ('Dental Care for Diabetic Patients', 'dental-care-for-diabetic-patients', 'dental', 'Specialized Dental Services', NULL, 1000.00, NULL),
 ('Dental Care for Cardiac Patients', 'dental-care-for-cardiac-patients', 'dental', 'Specialized Dental Services', NULL, 1500.00, NULL),
 ('Dental Care for Patients on Anticoagulants', 'dental-care-for-patients-on-anticoagulants', 'dental', 'Specialized Dental Services', NULL, 1500.00, NULL),
 ('Dental Care for Pregnant Patients', 'dental-care-for-pregnant-patients', 'dental', 'Specialized Dental Services', NULL, 1000.00, NULL),
 ('Hospital Dentistry', 'hospital-dentistry', 'dental', 'Specialized Dental Services', NULL, 2000.00, NULL),
 ('Dental Care for Bedridden Patients', 'dental-care-for-bedridden-patients', 'dental', 'Specialized Dental Services', NULL, 2500.00, NULL),
 ('Home Dental Consultation', 'home-dental-consultation', 'dental', 'Specialized Dental Services', NULL, 2000.00, NULL),
 ('Mobile Dental Services', 'mobile-dental-services', 'dental', 'Specialized Dental Services', NULL, 2500.00, NULL),
 ('Dental Camp Services', 'dental-camp-services', 'dental', 'Specialized Dental Services', NULL, 500.00, NULL),
 ('Local Anaesthesia', 'local-anaesthesia', 'dental', 'Sedation & Anaesthesia Services', NULL, 300.00, NULL),
 ('Topical Anaesthesia', 'topical-anaesthesia', 'dental', 'Sedation & Anaesthesia Services', NULL, 200.00, NULL),
 ('Nitrous Oxide Sedation', 'nitrous-oxide-sedation', 'dental', 'Sedation & Anaesthesia Services', NULL, 5000.00, NULL),
 ('Conscious Sedation', 'conscious-sedation', 'dental', 'Sedation & Anaesthesia Services', NULL, 10000.00, NULL),
 ('IV Sedation', 'iv-sedation', 'dental', 'Sedation & Anaesthesia Services', NULL, 15000.00, NULL),
 ('General Anaesthesia', 'general-anaesthesia', 'dental', 'Sedation & Anaesthesia Services', NULL, 30000.00, NULL),
 ('In-House Dental Laboratory', 'in-house-dental-laboratory', 'dental', 'Dental Laboratory Services', NULL, NULL, NULL),
 ('Crown & Bridge Fabrication', 'crown-bridge-fabrication', 'dental', 'Dental Laboratory Services', NULL, 5000.00, NULL),
 ('Denture Fabrication', 'denture-fabrication', 'dental', 'Dental Laboratory Services', NULL, 8000.00, NULL),
 ('Orthodontic Appliance Fabrication', 'orthodontic-appliance-fabrication', 'dental', 'Dental Laboratory Services', NULL, 5000.00, NULL),
 ('Implant Prosthesis Fabrication', 'implant-prosthesis-fabrication', 'dental', 'Dental Laboratory Services', NULL, 15000.00, NULL),
 ('Digital Dental Scanning', 'digital-dental-scanning', 'dental', 'Dental Laboratory Services', NULL, 3000.00, NULL),
 ('CAD/CAM Dentistry', 'cad-cam-dentistry', 'dental', 'Dental Laboratory Services', NULL, 10000.00, NULL),
 ('3D Printing', '3d-printing', 'dental', 'Dental Laboratory Services', NULL, 5000.00, NULL),
 ('Digital Wax-Up', 'digital-wax-up', 'dental', 'Dental Laboratory Services', NULL, 5000.00, NULL),
 ('Custom Tray Fabrication', 'custom-tray-fabrication', 'dental', 'Dental Laboratory Services', NULL, 1500.00, NULL),
 ('Night Guard Fabrication', 'night-guard-fabrication', 'dental', 'Dental Laboratory Services', NULL, 5000.00, NULL),
 ('Sports Mouthguard Fabrication', 'sports-mouthguard-fabrication', 'dental', 'Dental Laboratory Services', NULL, 5000.00, NULL),
 ('Digital Patient Registration', 'digital-patient-registration', 'dental', 'Digital & Technology-Based Dentistry', NULL, 200.00, NULL),
 ('Electronic Dental Case Sheet', 'electronic-dental-case-sheet', 'dental', 'Digital & Technology-Based Dentistry', NULL, 500.00, NULL),
 ('Digital Dental Charting', 'digital-dental-charting', 'dental', 'Digital & Technology-Based Dentistry', NULL, 500.00, NULL),
 ('Digital Dental Photography', 'digital-dental-photography', 'dental', 'Digital & Technology-Based Dentistry', NULL, 1000.00, NULL),
 ('Intraoral Scanner', 'intraoral-scanner', 'dental', 'Digital & Technology-Based Dentistry', NULL, 3000.00, NULL),
 ('Digital Smile Design', 'digital-smile-design-2', 'dental', 'Digital & Technology-Based Dentistry', NULL, 10000.00, NULL),
 ('CAD/CAM Dentistry', 'cad-cam-dentistry-2', 'dental', 'Digital & Technology-Based Dentistry', NULL, 10000.00, NULL),
 ('Digital Treatment Planning', 'digital-treatment-planning', 'dental', 'Digital & Technology-Based Dentistry', NULL, 3000.00, NULL),
 ('3D Printing', '3d-printing-2', 'dental', 'Digital & Technology-Based Dentistry', NULL, 5000.00, NULL),
 ('Tele-Dentistry Consultation', 'tele-dentistry-consultation', 'dental', 'Digital & Technology-Based Dentistry', NULL, 500.00, NULL),
 ('Online Appointment Booking', 'online-appointment-booking', 'dental', 'Digital & Technology-Based Dentistry', NULL, NULL, NULL),
 ('Online Follow-Up Consultation', 'online-follow-up-consultation', 'dental', 'Digital & Technology-Based Dentistry', NULL, 500.00, NULL),
 ('Digital Consent Documentation', 'digital-consent-documentation', 'dental', 'Digital & Technology-Based Dentistry', NULL, 200.00, NULL),
 ('Instrument Sterilization', 'instrument-sterilization', 'dental', 'Dental Hygiene & Infection Control', NULL, 300.00, NULL),
 ('Autoclave Sterilization', 'autoclave-sterilization', 'dental', 'Dental Hygiene & Infection Control', NULL, 500.00, NULL),
 ('Ultrasonic Cleaning', 'ultrasonic-cleaning', 'dental', 'Dental Hygiene & Infection Control', NULL, 300.00, NULL),
 ('Instrument Disinfection', 'instrument-disinfection', 'dental', 'Dental Hygiene & Infection Control', NULL, 200.00, NULL),
 ('Dental Unit Disinfection', 'dental-unit-disinfection', 'dental', 'Dental Hygiene & Infection Control', NULL, 300.00, NULL),
 ('Biomedical Waste Management', 'biomedical-waste-management', 'dental', 'Dental Hygiene & Infection Control', NULL, 200.00, NULL),
 ('Sharps Disposal', 'sharps-disposal', 'dental', 'Dental Hygiene & Infection Control', NULL, 100.00, NULL),
 ('PPE Protocols', 'ppe-protocols', 'dental', 'Dental Hygiene & Infection Control', NULL, 200.00, NULL),
 ('Infection Control Protocols', 'infection-control-protocols', 'dental', 'Dental Hygiene & Infection Control', NULL, 500.00, NULL),
 ('Sterilization Monitoring', 'sterilization-monitoring', 'dental', 'Dental Hygiene & Infection Control', NULL, 300.00, NULL),
 ('Dental Waterline Management', 'dental-waterline-management', 'dental', 'Dental Hygiene & Infection Control', NULL, 500.00, NULL),
 ('Inpatient Dental Consultation', 'inpatient-dental-consultation', 'dental', 'Hospital / Institutional Dental Services', NULL, 1500.00, NULL),
 ('Pre-Operative Dental Clearance', 'pre-operative-dental-clearance', 'dental', 'Hospital / Institutional Dental Services', NULL, 1500.00, NULL),
 ('Dental Consultation for Hospitalized Patients', 'dental-consultation-for-hospitalized-patients', 'dental', 'Hospital / Institutional Dental Services', NULL, 1500.00, NULL),
 ('Dental Services for ICU Patients', 'dental-services-for-icu-patients', 'dental', 'Hospital / Institutional Dental Services', NULL, 2500.00, NULL),
 ('Dental Services for Oncology Patients', 'dental-services-for-oncology-patients', 'dental', 'Hospital / Institutional Dental Services', NULL, 2000.00, NULL),
 ('Dental Services for Cardiac Patients', 'dental-services-for-cardiac-patients', 'dental', 'Hospital / Institutional Dental Services', NULL, 2000.00, NULL),
 ('Dental Services for Diabetic Patients', 'dental-services-for-diabetic-patients', 'dental', 'Hospital / Institutional Dental Services', NULL, 1500.00, NULL),
 ('Dental Services for Medically Compromised Patients', 'dental-services-for-medically-compromised-patients', 'dental', 'Hospital / Institutional Dental Services', NULL, 2000.00, NULL),
 ('Multidisciplinary Case Management', 'multidisciplinary-case-management', 'dental', 'Hospital / Institutional Dental Services', NULL, 3000.00, NULL),
 ('Dental Referral Services', 'dental-referral-services', 'dental', 'Hospital / Institutional Dental Services', NULL, 500.00, NULL),
 ('Emergency Dental Support', 'emergency-dental-support', 'dental', 'Hospital / Institutional Dental Services', NULL, 2500.00, NULL),
 ('Dental Operation Theatre Services', 'dental-operation-theatre-services', 'dental', 'Hospital / Institutional Dental Services', NULL, 25000.00, NULL),
 ('School Dental Screening Camps', 'school-dental-screening-camps', 'dental', 'Outreach & Community Dental Services', NULL, 250.00, NULL),
 ('Corporate Dental Camps', 'corporate-dental-camps', 'dental', 'Outreach & Community Dental Services', NULL, 500.00, NULL),
 ('Community Dental Camps', 'community-dental-camps', 'dental', 'Outreach & Community Dental Services', NULL, 250.00, NULL),
 ('Rural Dental Camps', 'rural-dental-camps', 'dental', 'Outreach & Community Dental Services', NULL, 250.00, NULL),
 ('Corporate Dental Health Programmes', 'corporate-dental-health-programmes', 'dental', 'Outreach & Community Dental Services', NULL, 500.00, NULL),
 ('School Oral Health Programmes', 'school-oral-health-programmes', 'dental', 'Outreach & Community Dental Services', NULL, 250.00, NULL),
 ('Employee Dental Health Programmes', 'employee-dental-health-programmes', 'dental', 'Outreach & Community Dental Services', NULL, 500.00, NULL),
 ('Dental Awareness Programmes', 'dental-awareness-programmes', 'dental', 'Outreach & Community Dental Services', NULL, 250.00, NULL),
 ('Preventive Dental Screening Programmes', 'preventive-dental-screening-programmes', 'dental', 'Outreach & Community Dental Services', NULL, 250.00, NULL),
 ('Home Dental Consultation', 'home-dental-consultation-2', 'dental', 'Home Dental Care Services', NULL, 2000.00, NULL),
 ('Home Oral Examination', 'home-oral-examination', 'dental', 'Home Dental Care Services', NULL, 1500.00, NULL),
 ('Home Dental Hygiene Counselling', 'home-dental-hygiene-counselling', 'dental', 'Home Dental Care Services', NULL, 1000.00, NULL),
 ('Bedridden Patient Dental Care', 'bedridden-patient-dental-care', 'dental', 'Home Dental Care Services', NULL, 2500.00, NULL),
 ('Elderly Patient Dental Care', 'elderly-patient-dental-care', 'dental', 'Home Dental Care Services', NULL, 2000.00, NULL),
 ('Denture Assessment at Home', 'denture-assessment-at-home', 'dental', 'Home Dental Care Services', NULL, 2000.00, NULL),
 ('Home Denture Delivery', 'home-denture-delivery', 'dental', 'Home Dental Care Services', NULL, 1000.00, NULL),
 ('Post-Dental Procedure Home Follow-Up', 'post-dental-procedure-home-follow-up', 'dental', 'Home Dental Care Services', NULL, 1000.00, NULL),
 ('Mobile Dental Unit Services', 'mobile-dental-unit-services', 'dental', 'Home Dental Care Services', NULL, 2500.00, NULL),
 ('Online Appointment Booking', 'online-appointment-booking-2', 'dental', 'Patient Support & Administrative Services', NULL, NULL, NULL),
 ('Walk-In Registration', 'walk-in-registration', 'dental', 'Patient Support & Administrative Services', NULL, 200.00, NULL),
 ('Emergency Registration', 'emergency-registration', 'dental', 'Patient Support & Administrative Services', NULL, 300.00, NULL),
 ('Insurance / TPA Services', 'insurance-tpa-services', 'dental', 'Patient Support & Administrative Services', NULL, 500.00, NULL),
 ('Cashless Dental Services', 'cashless-dental-services', 'dental', 'Patient Support & Administrative Services', NULL, 500.00, NULL),
 ('Treatment Estimates', 'treatment-estimates', 'dental', 'Patient Support & Administrative Services', NULL, 500.00, NULL),
 ('Payment Plans', 'payment-plans', 'dental', 'Patient Support & Administrative Services', NULL, 500.00, NULL),
 ('EMI / Instalment Facility', 'emi-instalment-facility', 'dental', 'Patient Support & Administrative Services', NULL, 500.00, NULL),
 ('Patient Follow-Up Services', 'patient-follow-up-services', 'dental', 'Patient Support & Administrative Services', NULL, 500.00, NULL),
 ('Recall / Reminder Services', 'recall-reminder-services', 'dental', 'Patient Support & Administrative Services', NULL, 200.00, NULL),
 ('Patient Feedback System', 'patient-feedback-system', 'dental', 'Patient Support & Administrative Services', NULL, 200.00, NULL),
 ('Second Opinion Services', 'second-opinion-services-2', 'dental', 'Patient Support & Administrative Services', NULL, 750.00, NULL),
 ('Medical Records Management', 'medical-records-management', 'dental', 'Patient Support & Administrative Services', NULL, 300.00, NULL)
ON CONFLICT (slug) DO UPDATE SET
    name                  = EXCLUDED.name,
    category              = EXCLUDED.category,
    sub_category          = COALESCE(EXCLUDED.sub_category, service_catalog.sub_category),
    unit                  = COALESCE(EXCLUDED.unit, service_catalog.unit),
    reference_mrp         = EXCLUDED.reference_mrp,
    reference_offer_price = EXCLUDED.reference_offer_price;

COMMIT;

NOTIFY pgrst, 'reload schema';
