-- ============================================================================
-- Migration: task8_full_service_catalog.sql
-- Description: home_services only ever carried the 10 tests seeded in
--              task1 (CBC/LFT/KFT/...); every other individual test a
--              patient could pick from the public /packages price list
--              (frontend/src/data/lab-test-prices.json) silently failed to
--              match a home_services row at booking time, so no sample/tube
--              record was ever created for it (bookings.py
--              _provision_home_collection logs this and moves on rather
--              than failing the booking -- see its docstring).
--
--              health_packages was defined in the schema but never seeded,
--              so package bookings (e.g. "Hormone Package (Female)") had
--              ZERO chance of matching anything. This seeds the 15 public
--              packages with their component tests, using curated
--              format-only aliases (e.g. "URIC ACID" -> "Uric Acid, Serum",
--              the SAME test, not a substitute) so bookings.py can expand a
--              package selection into its component home_services rows.
--
--              11 package components (Total Cholesterol, Total Bilirubin,
--              Apolipoprotein A1/B, Lipoprotein(A), CK-MB, TFT, 17-OHP,
--              DHEAS, C-Peptide, % Iron Saturation) have no confident 1:1
--              match in the current test catalog and are deliberately left
--              unaliased -- they will surface via the existing "did not
--              match any home_services row" warning log for manual
--              follow-up rather than being guessed at.
-- Date: 2026-08-06
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SECTION 1: MIGRATION STATEMENTS
-- ----------------------------------------------------------------------------
BEGIN;

-- All individual lab tests from the public price list, so selected_tests
-- entries actually resolve to a home_services row instead of only the 10
-- originally seeded (CBC/LFT/KFT/...). Guarded on code (a deterministic
-- slug of the test name) since name has no unique constraint; a re-run is
-- a no-op.
INSERT INTO home_services (code, name, service_kind, category, base_price)
SELECT v.code, v.name, 'blood_test', 'blood_test', v.price
  FROM (VALUES
('1_25_DIHYDROXY_VITAMIN_D', '1,25 Dihydroxy Vitamin D', 2800),
('17_ALPHA_HYDROXY_PROGESTERON', '17 Alpha Hydroxy Progesteron', 1200),
('17_HYDROXY_CORTICOSTEROIDS_URINE_24H', '17 Hydroxy Corticosteroids, Urine 24H', 1200),
('17_KETOSTEROIDS_URINE_24H', '17-Ketosteroids, Urine 24H', 8000),
('25_HYDROXY_VITAMIN_D', '25 Hydroxy Vitamin D', 1280),
('5_HYDROXY_INDOLE_ACETIC_ACID_24_URINE', '5 Hydroxy Indole Acetic Acid, 24 Urine', 2856),
('ABSOLUTE_EOSINOPHIL_COUNT_AEC', 'Absolute Eosinophil Count (AEC)', 80),
('ABSOLUTE_LYMPHOCYTE_COUNT', 'Absolute Lymphocyte Count', 248),
('ABSOLUTE_MONOCYTE_COUNT', 'Absolute Monocyte Count', 248),
('ABSOLUTE_NEUTROPHIL_COUNT_ANC', 'Absolute Neutrophil Count (ANC)', 248),
('ACETONE_KETONE_URINE', 'Acetone (Ketone), Urine', 80),
('ACETYLCHOLINE_RECEPTOR_ANTIBODY', 'Acetylcholine Receptor Antibody', 2616),
('ACTIVATED_PARTIAL_THROMBOPLASTIN_TIME_APTT', 'Activated Partial Thromboplastin Time (APTT)', 240),
('ACTIVATED_PROTEIN_C_APC_RESISTANCE_TEST_PLASMA', 'Activated Protein C (APC) Resistance Test,Plasma', 3672),
('ACUTE_LEUKEMIA_DIAGNOSTIC_PANEL', 'Acute Leukemia Diagnostic Panel', 9792),
('ADA_ASCITIC_FLUID', 'ADA, Ascitic fluid', 640),
('ADA_CSF', 'ADA, CSF', 640),
('ADA_CYST_ASPIRATION_FLUID', 'ADA, cyst aspiration fluid', 640),
('ADA_GUIDED_ASPIRATE', 'ADA, Guided Aspirate', 640),
('ADA_PERICARDIAL_FLUID', 'ADA, Pericardial Fluid', 640),
('ADA_PERITONEAL_FLUID', 'ADA, Peritoneal Fluid', 640),
('ADA_PLEURAL_FLUID', 'ADA, Pleural fluid', 640),
('ADA_PUS', 'ADA, PUS', 640),
('ADA_SERUM', 'ADA, Serum', 640),
('ADA_SYNOVIAL_FLUID', 'ADA, Synovial Fluid', 640),
('ADRENALINE_EPINEPHRINE_URINE_24H', 'Adrenaline (Epinephrine),urine 24H', 2448),
('ADRENO_CORTICOTROPHIC_HOROMONE_ACTH', 'Adreno Corticotrophic Horomone (ACTH)', 1440),
('AFB_CULTURE_BIOPSY', 'AFB Culture- Biopsy', 400),
('AFB_CULTURE_CONVENTIONAL_METHOD', 'AFB Culture, Conventional Method', 816),
('AFB_STAIN_SPUTUM', 'AFB Stain, Sputum', 360),
('AFB_STAIN_SPUTUM_1ST_SAMPLE', 'AFB Stain, Sputum - 1st Sample', 360),
('ALBUMIN_SERUM', 'Albumin, Serum', 120),
('ALBUMIN_URINE_24H', 'Albumin, Urine 24H', 328),
('ALBUMIN_URINE_SPOT', 'Albumin, Urine Spot', 88),
('ALKALINE_PHOSPHATASE_ALP', 'Alkaline Phosphatase (ALP)', 136),
('ALKALINE_PHOSPHATASE_WITH_BONE_FRACTION_OSTASE', 'Alkaline Phosphatase with bone Fraction (Ostase)', 2040),
('ALPHA_FETO_PROTEIN_AFP', 'Alpha Feto Protein (AFP)', 840),
('ALPHA_FETO_PROTEIN_AFP_CSF', 'Alpha Feto Protein (AFP), CSF', 800),
('ALT_SGPT', 'ALT (SGPT)', 80),
('AMMONIA', 'Ammonia', 816),
('AMYLASE_CYST_FLUID', 'Amylase, Cyst Fluid', 328),
('AMYLASE_FLUID', 'Amylase, Fluid', 328),
('AMYLASE_SERUM', 'Amylase, Serum', 400),
('ANA_PROFILE', 'ANA Profile', 2800),
('ANGIOTENSING_CONVERTING_ENZYME_ACE', 'Angiotensing Converting Enzyme (ACE)', 2240),
('ANGIOTENSING_CONVERTING_ENZYME_ACE_CSF', 'Angiotensing Converting Enzyme (ACE),CSF', 2800),
('ANTI_DNASE_B_SERUM', 'Anti DNase B, serum', 1472),
('ANTI_DS_DNA', 'Anti ds DNA', 1760),
('ANTI_NEUTROPHIL_CYTOPLASMIC_ANTIBODY_ANCA', 'Anti Neutrophil Cytoplasmic Antibody (ANCA)', 1880),
('ANTI_NUCLEAR_ANTIBODIES_ANA', 'Anti Nuclear Antibodies (ANA)', 760),
('ANTI_STREPTOLISIN_O_ASO', 'Anti Streptolisin O (ASO)', 120),
('ANTI_THROMBIN_III_ACTIVITY', 'Anti Thrombin III Activity', 4080),
('ANTI_THROMBIN_III_ANTIGEN', 'Anti Thrombin III Antigen', 4080),
('ANTI_THYROID_ANTI_BODIES_TPO_2_ATG', 'Anti Thyroid Anti Bodies/TPO/2/ATG', 2160),
('ANTI_THYROID_PEROXIDASE_ANTI_TPO_MICROSOMAL_ANTIBODY', 'Anti Thyroid Peroxidase (Anti Tpo), Microsomal Antibody', 2240),
('APLA_PROFILE', 'APLA PROFILE', 4800),
('APOLIPOPROTEIN_B', 'Apolipoprotein - B', 400),
('AST_SGOT', 'AST (SGOT)', 80),
('B_TYPE_NATRIURETIC_PEPTIDE_BNP_NT_PRO', 'B Type Natriuretic Peptide (BNP)(NT-Pro)', 2616),
('BENCE_JONES_PROTEINS_URINE', 'Bence Jones Proteins, Urine', 240),
('BETA_2_MICROGLOBULIN_SERUM', 'Beta 2 Microglobulin, Serum', 1440),
('BETA_HCG_SERUM', 'Beta HCG, Serum', 1040),
('BETA_2_GLYCOPROTEIN_I_IGG_ANTIBODY_SERUM', 'Beta-2-Glycoprotein I IgG Antibody Serum', 1632),
('BETA_2_GLYCOPROTEIN_I_IGM_ANTIBODY_SERUM', 'Beta-2-Glycoprotein I IgM Antibody Serum', 1632),
('BICARBONATE', 'Bicarbonate', 408),
('BILE_ACIDS_TOTAL_SERUM', 'Bile Acids-Total, Serum', 1632),
('BILE_SALTS_AND_BILE_PIGMENTS_URINE', 'Bile Salts and Bile Pigments , Urine', 80),
('BILIRUBIN_TOTAL_DIRECT_INDIRECT', 'Bilirubin, (Total,Direct,Indirect)', 328),
('BILIRUBIN_DIRECT', 'Bilirubin, Direct', 200),
('BILIRUBIN_TOTAL', 'Bilirubin, Total', 200),
('BIOCHEMICAL_ANALYSIS_ASCITIC_FLUID', 'Biochemical analysis, Ascitic fluid', 408),
('BIOCHEMICAL_ANALYSIS_PERITONEAL_FLUID', 'Biochemical analysis, Peritoneal fluid', 408),
('BIOPSY_LARGE', 'BIOPSY (Large)', 960),
('BIOPSY_MEDIUM', 'BIOPSY MEDIUM', 640),
('BLEEDING_TIME', 'Bleeding Time', 24),
('BLOOD_CULTURE_AND_SENSITIVITY_1ST_REPORT', 'Blood Culture and Sensitivity - 1st Report', 1080),
('BLOOD_CULTURE_AND_SENSITIVITY_2ND_REPORT', 'Blood Culture and Sensitivity - 2nd Report', 1080),
('BLOOD_CULTURE_AND_SENSITIVITY_FINAL_REPORT', 'Blood Culture and Sensitivity - Final Report', 1080),
('BLOOD_GROUPING_AND_RH_TYPING', 'Blood Grouping and Rh Typing', 80),
('BLOOD_UREA_NITROGEN_BUN', 'Blood Urea Nitrogen (BUN)', 120),
('BUN_CREATININE_RATIO', 'Bun Creatinine Ratio', 328),
('C_PEPTIDE', 'C- Peptide', 1312),
('C1_ESTERASE_INHIBITOR_SERUM', 'C1 Esterase Inhibitor, Serum', 2856),
('CA_125', 'CA - 125', 1040),
('CA_15_3', 'CA 15.3', 960),
('CA_19_9', 'CA 19.9', 1200),
('CA_125_FLUID', 'CA-125 Fluid', 960),
('CALCITONIN_THYROCALCITONIN_SERUM', 'Calcitonin (Thyrocalcitonin),Serum', 2856),
('CALCIUM_IONIZED', 'Calcium, Ionized', 560),
('CALCIUM_SERUM', 'Calcium, Serum', 120),
('CALCIUM_URINE_24H', 'Calcium, Urine 24H', 120),
('CALCIUM_CREATININE_RATIO_URINE_SPOT', 'Calcium/Creatinine Ratio, Urine spot', 496),
('C_ANCA', 'C-ANCA', 1680),
('CARBAMEZEPINE_TEGRETOL', 'Carbamezepine (Tegretol)', 1224),
('CARCINO_EMBROYNIC_ANTIGEN_CEA', 'Carcino Embroynic Antigen (CEA)', 640),
('CARDIOLIPIN_IGA_ANTIBODY', 'Cardiolipin IgA Antibody', 984),
('CARDIOLIPIN_IGG_ANTIBODY', 'Cardiolipin IgG Antibody', 984),
('CARDIOLIPIN_IGM_ANTIBODY', 'Cardiolipin IgM Antibody', 1000),
('CARDIOLIPIN_PROFILE', 'Cardiolipin Profile', 2616),
('CATECHOLAMINES_URINE_24HRS', 'Catecholamines, Urine 24Hrs', 6320),
('CB_NAAT_SPUTUM', 'CB NAAT Sputum', 2000),
('CBC', 'CBC', 280),
('CBP_WITH_ESR', 'CBP WITH ESR', 520),
('CD_4_CD_8_COUNT', 'CD 4 & CD 8 Count', 1200),
('CD_4_COUNT', 'CD 4 Count', 960),
('CD3_CD_4_CD_8_COUNT', 'CD3, CD 4 & CD 8 Count', 2160),
('CELL_COUNT_CELL_TYPE_ASCITIC_FLUID', 'Cell count & cell type, Ascitic Fluid', 240),
('CELL_COUNT_CELL_TYPE_BRONCHIAL_WASH', 'Cell count & cell type, Bronchial Wash', 328),
('CELL_COUNT_CELL_TYPE_CSF', 'Cell count & cell type, CSF', 328),
('CELL_COUNT_CELL_TYPE_FLUID', 'Cell count & cell type, fluid', 320),
('CELL_COUNT_CELL_TYPE_GUIDED_ASPIRATE_FLUID', 'Cell count & cell type, Guided Aspirate Fluid', 320),
('CELL_COUNT_CELL_TYPE_DIALYSIS_FLUID', 'Cell count & cell type,Dialysis Fluid', 320),
('CENTROMERE_ANTIBODY', 'Centromere Antibody', 2040),
('CERULOPLASMIN_COPPER_OXIDASE_SERUM', 'Ceruloplasmin(Copper Oxidase), Serum', 1224),
('CHIKUNGUNYA_IGM_ANTIBODY', 'Chikungunya IgM Antibody', 960),
('CHLAMYDIA_TRACHOMATIS_IGA_ANTIBODY', 'Chlamydia Trachomatis IgA Antibody', 1632),
('CHLORIDES_CSF', 'Chlorides, CSF', 240),
('CHLORIDES_SERUM', 'Chlorides, Serum', 120),
('CHLORIDES_URINE_24H', 'Chlorides, Urine 24H', 328),
('CHOLESTEROL_TOTAL', 'Cholesterol,Total', 120),
('CHOLINESTERASE_ACETYL_PLASMA', 'Cholinesterase- Acetyl, Plasma', 1200),
('CHYLE_URINE', 'Chyle, Urine', 240),
('CITRATE_URINE_24_H', 'Citrate, Urine 24 H', 1632),
('CLOTTING_TIME', 'Clotting Time', 24),
('COBALT_BLOOD', 'Cobalt, Blood', 3264),
('COLLAGEN_PROFILE', 'COLLAGEN PROFILE', 5520),
('COLLAGEN_PROFILE_ADVANCED', 'COLLAGEN PROFILE ADVANCED', 5520),
('COMPLEMENT_3', 'Complement-3', 1040),
('COMPLEMENT_4', 'Complement-4', 1040),
('COMPLETE_BLOOD_PICTURE_CBP', 'Complete Blood Picture (CBP)', 280),
('COMPLETE_URINE_EXAMINATION_CUE', 'Complete Urine Examination (CUE)', 128),
('COOMBS_TEST_DIRECT_DCT', 'Coombs Test - Direct (DCT)', 320),
('COOMBS_TEST_INDIRECT_ICT', 'Coombs Test - Indirect (ICT)', 320),
('COPPER_SERUM', 'Copper, Serum', 1472),
('COPPER_URINE_24H', 'Copper, Urine 24H', 1632),
('CORTISOL_4_PM', 'Cortisol (4 PM)', 736),
('CORTISOL_8_AM', 'Cortisol (8 AM)', 736),
('CORTISOL_FREE_URINE_24H', 'Cortisol ,Free Urine 24H', 640),
('CPK_MB', 'CPK- MB', 408),
('C_REACTIVE_PROTEINS_CRP', 'C-Reactive Proteins (CRP)', 320),
('CREATINE_KINASE_CPK', 'Creatine Kinase (CPK)', 480),
('CREATININE_CLEARANCE_TEST_URINE_24H', 'Creatinine Clearance Test, Urine 24H', 496),
('CREATININE_SERUM', 'Creatinine, Serum', 96),
('CREATININE_URINE_24H', 'Creatinine, Urine 24H', 120),
('CREATININE_URINE_SPOT', 'Creatinine, Urine Spot', 120),
('CREATININE_GFR_BY_MDRD', 'Creatinine-GFR by MDRD', 408),
('CRYPTOCOCCUS_ANTIGEN_CSF', 'Cryptococcus Antigen, CSF', 2856),
('CSF_ANALYSIS_ANURADHA_NEURO', 'CSF ANALYSIS ANURADHA NEURO', 4816),
('CT_BOTH_TEMPORAL_BONES', 'CT BOTH TEMPORAL BONES', 5600),
('CT_GUIDED_BIOPSY', 'CT GUIDED BIOPSY', 6000),
('CT_REPORT_SECOND_OPINION', 'CT REPORT (SECOND OPINION)', 320),
('CT_STRYKER_PROTOCOL', 'CT STRYKER PROTOCOL', 7600),
('CULTURE_SENSITIVITY_TRACHEAL_SECRETION', 'Culture & Sensitivity , Tracheal secretion', 456),
('CULTURE_AND_SENSITIVITY_BIOPSY', 'Culture and Sensitivity , Biopsy', 400),
('CULTURE_AND_SENSITIVITY_ASCITIC_FLUID', 'Culture and Sensitivity, Ascitic Fluid', 400),
('CULTURE_AND_SENSITIVITY_BRONCHIAL_WASH', 'Culture and Sensitivity, Bronchial Wash', 400),
('CULTURE_AND_SENSITIVITY_CSF', 'Culture and Sensitivity, CSF', 400),
('CULTURE_AND_SENSITIVITY_CYST_ASPIRATION_FLUID', 'Culture and Sensitivity, cyst aspiration Fluid', 400),
('CULTURE_AND_SENSITIVITY_EAR_EYE_SWAB', 'Culture and Sensitivity, Ear/Eye Swab', 400),
('CULTURE_AND_SENSITIVITY_FLUID', 'Culture and Sensitivity, Fluid', 400),
('CULTURE_AND_SENSITIVITY_GUIDED_ASPIRATE', 'Culture and Sensitivity, Guided Aspirate', 400),
('CULTURE_AND_SENSITIVITY_NASAL_SWAB', 'Culture and Sensitivity, Nasal Swab', 400),
('CULTURE_AND_SENSITIVITY_PLEURAL_FLUID', 'Culture and Sensitivity, Pleural Fluid', 400),
('CULTURE_AND_SENSITIVITY_PUS', 'Culture and Sensitivity, Pus', 400),
('CULTURE_AND_SENSITIVITY_PUS_SWAB', 'Culture and Sensitivity, Pus Swab', 400),
('CULTURE_AND_SENSITIVITY_SPUTUM', 'Culture and Sensitivity, Sputum', 400),
('CULTURE_AND_SENSITIVITY_STOOL', 'Culture and Sensitivity, Stool', 400),
('CULTURE_AND_SENSITIVITY_SYNOVIAL_FLUID', 'Culture and Sensitivity, Synovial Fluid', 400),
('CULTURE_AND_SENSITIVITY_THROAT_SWAB', 'Culture and Sensitivity, Throat Swab', 560),
('CULTURE_AND_SENSITIVITY_URINE', 'Culture and Sensitivity, Urine', 400),
('CULTURE_AND_SENSITIVITY_URETHRAL_SWAB', 'Culture and Sensitivity,Urethral Swab', 400),
('CULTURE_AND_SENSITIVITY_VAGINAL_SWAB', 'Culture and Sensitivity,Vaginal Swab', 400),
('CULTURE_AND_SENSITIVITY_WOUND_SWAB', 'Culture and Sensitivity,Wound Swab', 400),
('CULTURE_AND_SENSIVITY_CERVICAL_SWAB', 'Culture and Sensivity ,Cervical swab', 400),
('CYCLIC_CITRULLINATED_PEPTIDE_CCP_ANTIBODY', 'Cyclic Citrullinated Peptide (CCP) Antibody', 1520),
('CYTOLOGY_ASCITIC_FLUID', 'Cytology, Ascitic Fluid', 400),
('CYTOLOGY_PAPSMEAR', 'Cytology, Papsmear', 960),
('CYTOLOGY_PAPSMEAR_BY_LBC_METHOD', 'Cytology, Papsmear by LBC Method', 984),
('D_DIMER', 'D-Dimer', 1200),
('DEHYDRO_EPIANDROSTERONE_SULPHATE_DHEA_S', 'Dehydro Epiandrosterone Sulphate (DHEA-S)', 1280),
('DENGUE_ANTIGEN_NS1_ELISA', 'Dengue Antigen NS1 (ELISA)', 760),
('DENGUE_IG_G_IG_M_RAPID', 'Dengue Ig G & Ig M - Rapid', 760),
('DENGUE_IGG_IGM_NS1_RAPID', 'Dengue IgG IgM NS1 (Rapid)', 760),
('DENGUE_SEROLOGY', 'Dengue Serology', 760),
('DI_HYDROTESTOSTERONE_DHT', 'Di HydroTestosterone (DHT)', 2040),
('DIFFERENTIAL_COUNT_DC', 'Differential Count (DC)', 40),
('DOUBLE_MARKER_TEST', 'Double Marker Test', 2448),
('DOUBLE_MARKER_TEST_GRAPH', 'Double Marker Test Graph', 2448),
('DTI_DIFFUSION_TENSOR_IMAGING', 'DTI (DIFFUSION TENSOR IMAGING)', 5000),
('ECG_ELECTROCARDIOGRAM', 'ECG(ELECTROCARDIOGRAM)', 120),
('EEGUSG_PACKAGE', 'EEGUSG PACKAGE', 1920),
('ELECTROLYTES_24H_URINE', 'Electrolytes, 24H Urine', 408),
('ELECTROLYTES_SERUM', 'Electrolytes, Serum', 360),
('ELECTROLYTES_URINE_SPOT', 'Electrolytes, Urine spot', 360),
('ERYTHROCYTE_SEDIMENTATION_RATE_ESR', 'Erythrocyte Sedimentation Rate (ESR)', 80),
('ERYTHROPOITIN_SERUM', 'Erythropoitin, Serum', 2856),
('ESTRADIOL_E2', 'Estradiol (E2)', 640),
('ESTRIOL_UNCONJUGATED_E3', 'Estriol unconjugated (E3)', 1224),
('FACTOR_I_FIBRINOGEN_ACTIVITY', 'Factor-I (Fibrinogen) Activity', 984),
('FAT_STOOL', 'Fat, Stool', 168),
('FBS_AND_PPBS', 'FBS AND PPBS', 400),
('FERRITIN_SERUM', 'Ferritin, Serum', 800),
('FMR', 'FMR', 92),
('FNAC_BLIND_PROCEDURE_REPORT', 'FNAC Blind Procedure & Report', 1200),
('FOLIC_ACID_SERUM', 'Folic Acid, serum', 960),
('FOLLICULAR_STIMULATING_HORMONE_FSH', 'Follicular Stimulating Hormone (FSH)', 520),
('FREE_BETA_HCG_SERUM', 'Free Beta HCG,Serum', 904),
('FUNGAL_CULTURE_SPUTUM', 'Fungal Culture, Sputum', 736),
('FUNGAL_STAIN_CSF', 'Fungal Stain, CSF', 400),
('G6PD_BLOOD', 'G6PD , Blood', 800),
('GAD_65_GLUTAMIC_ACID_DECORBOXILASE_ANTIBODIES', 'GAD 65 (Glutamic Acid Decorboxilase) Antibodies', 6040),
('GAMMA_GT_GGTP', 'Gamma GT (GGTP)', 400),
('GANGLIOSIDE_ANTIBODY_SERUM', 'Ganglioside Antibody,Serum', 3200),
('GENE_EXPERT_XPERT_MTB', 'Gene expert (xpert MTB)', 2448),
('GENE_EXPERT_PUS', 'Gene expert PUS', 2448),
('GLOBULIN_SERUM', 'Globulin Serum', 120),
('GLUCOSE_CHALLENGE_TEST_GCT', 'Glucose Challenge Test (GCT)', 160),
('GLUCOSE_TOLERANCE_TEST_3_SAMPLES', 'GLUCOSE TOLERANCE TEST (3 Samples)', 160),
('GLUCOSE_RBS', 'Glucose, (RBS)', 40),
('GLUCOSE_FASTING_FBS', 'Glucose, Fasting (FBS)', 40),
('GLUCOSE_POST_LUNCH_PLBS', 'Glucose, Post Lunch (PLBS)', 40),
('GLYCOSYLATED_HB_HBA1C', 'Glycosylated Hb (HbA1C)', 400),
('GRAMS_STAIN_ASCITIC_FLUID', 'Grams Stain, Ascitic Fluid', 160),
('GRAMS_STAIN_BRONCHIAL_WASH', 'Grams Stain, Bronchial Wash', 160),
('GRAMS_STAIN_CSF', 'Grams Stain, CSF', 160),
('GRAMS_STAIN_PERICARDIAL_FLUID', 'Grams Stain, Pericardial Fluid', 160),
('GRAMS_STAIN_PLEURAL_FLUID', 'Grams Stain, Pleural Fluid', 160),
('GRAMS_STAIN_PUS', 'Grams Stain, Pus', 160),
('GRAMS_STAIN_STOOL', 'Grams Stain, Stool', 160),
('GRAMS_STAIN_WOUND_SWAB', 'Grams Stain, Wound Swab', 160),
('GTT_1ST_HOUR_PLASMA_GLUCOSE', 'GTT - 1st Hour Plasma Glucose', 0),
('GTT_FASTING_PLASMA_GLUCOSE_3_SAMPLES', 'GTT -Fasting Plasma Glucose( 3 Samples )', 160),
('HAEMOGRAM', 'Haemogram', 320),
('HAPTOGLOBIN', 'Haptoglobin', 2616),
('HBV_DNA_DETECTION_QUALITATIVE', 'HBV-DNA Detection (Qualitative)', 3264),
('HBV_DNA_QUANTIFICATION_VIRAL_LOAD', 'HBV-DNA Quantification (Viral load)', 4480),
('HCV_GENOTYPING', 'HCV Genotyping', 6528),
('HCV_RNA_QUANTIFICATION_VIRAL_LOAD', 'HCV RNA Quantification (Viral load)', 4080),
('HEMOGLOBIN_HB', 'Hemoglobin (HB%)', 80),
('HEMOGLOBIN_ELECTROPHORESIS', 'Hemoglobin Electrophoresis', 1120),
('HEPATITIS_A_VIRUS_HAV_IGM_ANTIBODY', 'Hepatitis A Virus (HAV) IgM Antibody', 1200),
('HEPATITIS_A_VIRUS_ANTIBODY_IGG_TOTAL', 'Hepatitis A Virus Antibody, (IgG) Total', 1040),
('HEPATITIS_B_CORE_ANTIBODY_TOATL_HBCAB_TOTAL', 'Hepatitis B Core Antibody Toatl(HBcAb - Total)', 1224),
('HEPATITIS_B_CORE_ANTIGEN_HBCAG_IGM_ANTIBODY', 'Hepatitis B Core Antigen (HBcAg), IgM Antibody', 960),
('HEPATITIS_B_ENVELOPE_ANTIBODY_HBEAB', 'Hepatitis B Envelope Antibody (HBeAb)', 960),
('HEPATITIS_B_ENVELOPE_ANTIGEN_HBEAG', 'Hepatitis B Envelope Antigen (HBeAg )', 2040),
('HEPATITIS_B_SURFACE_ANTIBODY_TOTAL_ANTI_HBS_TITRE', 'Hepatitis B Surface Antibody,Total (Anti Hbs Titre)', 960),
('HEPATITIS_B_SURFACE_ANTIGEN_HBSAG', 'Hepatitis B surface Antigen (HBsAg)', 400),
('HEPATITIS_B_SURFACE_ANTIGEN_HBSAG_ELISA', 'Hepatitis B surface Antigen (HBsAg) - Elisa', 640),
('HEPATITIS_B_SURFACE_ANTIGEN_HBSAG_CMIA', 'Hepatitis B Surface antigen (HBsAg) (CMIA)', 960),
('HEPATITIS_B_SURFACE_ANTIGEN_HBSAG_SCREENING_RAPID', 'Hepatitis B surface Antigen (HBsAg) Screening (Rapid)', 240),
('HEPATITIS_C_VIRUS_HCV_ANTIBODY', 'Hepatitis C Virus (HCV) Antibody', 1360),
('HEPATITIS_C_VIRUS_HCV_ANTIBODY_ELISA', 'Hepatitis C Virus (HCV) Antibody - Elisa', 576),
('HEPATITIS_C_VIRUS_ANTIBODY_ANTI_HCV_SCREENING_RAPID', 'Hepatitis C Virus Antibody (Anti HCV) Screening (Rapid)', 400),
('HEPATITIS_C_VIRUS_HCV_ANITIBODY_CLIA', 'Hepatitis C Virus(HCV Anitibody)  (CLIA)', 1200),
('HEPATITIS_E_VIRUS_HEV_IGG_ANTIBODY', 'Hepatitis E Virus (HEV) IgG Antibody', 2000),
('HEPATITIS_E_VIRUS_HEV_IGM_ANTIBODY', 'Hepatitis E Virus (HEV) IgM Antibody', 2040),
('HERPES_SIMPLEX_VIRUS_I_II_IGG', 'Herpes Simplex Virus I & II - IgG', 960),
('HIGH_SENSITIVITY_CRP_HS_CRP', 'High Sensitivity - CRP (HS-CRP)', 784),
('HISTOPATHOLOGY_MEDIUM', 'Histopathology ( Medium )', 800),
('HISTOPATHOLOGY_EXTRA_LARGE', 'Histopathology (Extra Large)', 1224),
('HISTOPATHOLOGY_LARGE', 'Histopathology (Large)', 1280),
('HISTOPATHOLOGY_SMALL', 'Histopathology (Small)', 640),
('HIV_1_2_AG_AB_4TH_GENERATION_CMIA', 'HIV 1& 2 Ag/Ab (4th generation)  (CMIA)', 960),
('HIV_ELISA', 'HIV ELISA', 800),
('HIV_I_II_ANTIBODY_SCREENING_RAPID', 'HIV I & II Antibody Screening (Rapid)', 200),
('HIV_P_24_ANTIGEN', 'HIV P-24 Antigen', 1632),
('HIV_1_RNA_QUANTIFICATION_VIRAL_LOAD', 'HIV-1-RNA Quantification (Viral Load)', 4080),
('HLA_B27', 'HLA - B27', 2640),
('HLA_B27_BY_PCR', 'HLA - B27 By PCR', 3264),
('HLA_CROSS_MATCH', 'HLA - Cross Match', 4896),
('HOMOCYSTEINE_SERUM', 'Homocysteine-Serum', 760),
('HOMOGENTISIC_ACID', 'Homogentisic Acid', 984),
('HPV_DNA_DETECTION_QUALITATIVE', 'HPV-DNA detection (Qualitative)', 3040),
('HSV_I_II_IGG_IGM_ANTIBODIES', 'HSV I & II IgG & IgM antibodies', 2000),
('IMMUNOGLOBULIN_IGA', 'Immunoglobulin IgA', 800),
('IMMUNOGLOBULIN_IGG', 'Immunoglobulin IgG', 800),
('IMMUNOGLOBULIN_IGM', 'Immunoglobulin IgM', 800),
('IMMUNOGLOBULIN_PROFILE_CSF', 'Immunoglobulin Profile, CSF', 3264),
('INSULIN_FASTING_SERUM', 'Insulin - Fasting serum', 720),
('INSULIN_POST_SERUM', 'Insulin - Post ,Serum', 720),
('INSULIN_ANTIBODY_SERUM', 'Insulin Antibody, Serum', 2040),
('INSULIN_LIKE_GROWTH_FACTOR_IGF_1_SOMATOMEDIN_C', 'Insulin like Growth factor(IGF)-1(Somatomedin C)', 3520),
('INTACT_PARATHYROID_HORMONE_IPTH', 'Intact Parathyroid Hormone (iPTH)', 1800),
('INTERLEUKIN_6', 'INTERLEUKIN 6', 2000),
('IRON', 'Iron', 328),
('IRON_WITH_TIBC', 'Iron with TIBC', 576),
('JAK_2_MUTATION_BLOOD', 'JAK-2 Mutation,Blood', 5712),
('KAPPA_LAMBDA_LIGHT_CHAINS_FREE_URINE', 'Kappa & Lambda Light Chains- Free, Urine', 4488),
('KAPPA_LIGHT_CHAINS_FREE_SERUM', 'Kappa Light Chains- Free, Serum', 2448),
('KARYOTYPING_WHOLE_BLOOD', 'Karyotyping Whole Blood', 3672),
('KOH_EXAMINATION_FLUID', 'KOH Examination, Fluid', 248),
('KOH_EXAMINATION_NASAL_SWAB', 'KOH Examination, Nasal swab', 248),
('KOH_EXAMINATION_SPUTUM', 'KOH Examination, Sputum', 248),
('KOH_EXAMINATION_URINE', 'KOH Examination, Urine', 280),
('LACTATE', 'Lactate', 1224),
('LACTATE_DEHYDROGENASE_LDH_FLUID', 'Lactate Dehydrogenase (LDH), Fluid', 408),
('LACTATE_DEHYDROGENASE_LDH_SERUM', 'Lactate Dehydrogenase (LDH), Serum', 408),
('LC_1_LIVER_CYTOSOLIC_ANTIGEN_TYPE_1_ANTIBODY', 'LC-1 (Liver Cytosolic Antigen type-1)Antibody', 2448),
('LEGIONELLA_ANTIGEN_DETECTION_URINE', 'Legionella Antigen Detection, Urine', 2128),
('LEISHMANIA_ANTIBODY_IGG_KALA_AZAR', 'Leishmania Antibody-IgG(Kala Azar)', 2040),
('LEPTIN', 'Leptin', 4896),
('LEPTOSPIRA_DETECTION_BLOOD', 'Leptospira Detection,Blood', 960),
('LEPTOSPIRA_DETECTION_CSF', 'Leptospira Detection,CSF', 960),
('LEPTOSPIRA_IGG_ANTIBODY', 'Leptospira IgG Antibody', 960),
('LEPTOSPIRA_IGM_ANTIBODY', 'Leptospira IgM Antibody', 1224),
('LEVETIRACETAM_SERUM', 'Levetiracetam, Serum', 3264),
('LIPASE_SERUM', 'Lipase serum', 440),
('LIPASE_FLUID', 'Lipase,Fluid', 640),
('LIPASE_URINE', 'Lipase,Urine', 656),
('LIPID_PROFILE', 'Lipid Profile', 400),
('LIPOPROTEIN_A', 'Lipoprotein-(a)', 800),
('LITHIUM', 'Lithium', 656),
('LIVER_FUNCTION_TEST_LFT', 'Liver Function Test (LFT)', 400),
('LKM_I_ANTIBODY', 'LKM I Antibody', 2040),
('LUPUS_ANTICOAGULANTS_LAC', 'Lupus Anticoagulants (LAC)', 2616),
('LUTEINIZING_HORMONE_LH', 'Luteinizing Hormone (LH)', 400),
('LYME_BORRELIA_BURGDORFERI_ANTIBODY_IGM', 'Lyme (Borrelia Burgdorferi) Antibody IgM', 2040),
('LYME_BORRELIA_BURGDORFERI_ANTIBODY_IGG', 'Lyme (Borrelia Burgdorferi)Antibody IgG', 2040),
('MAGNESIUM', 'Magnesium', 488),
('MAGNESIUM_24HRS_URINE', 'Magnesium 24Hrs Urine', 1224),
('MCH', 'MCH', 80),
('MEASELS_RUBEOLA_IGM_ANTIBODY', 'Measels (Rubeola) IgM Antibody', 2040),
('METANEPHRINE_URINE_24H', 'Metanephrine, Urine 24H', 2640),
('METANEPHRINE_FREE_PLASMA', 'Metanephrine-Free,Plasma', 3264),
('METH_HAEMOGLOBIN', 'Meth haemoglobin', 736),
('MICROALBUMIN_URINE_24H', 'Microalbumin, Urine 24H', 408),
('MICROALBUMIN_CREATININE_RATIO_URINE_SPOT', 'Microalbumin/Creatinine ratio, Urine Spot', 496),
('MITOCHONDRIAL_ANTIBODY_AMA', 'Mitochondrial Antibody (AMA)', 1800),
('MRI_CARDIAC_WITH_CONTRAST', 'MRI CARDIAC WITH CONTRAST', 10000),
('MRI_LEFT_KNEE_JOINT', 'MRI LEFT KNEE JOINT', 4000),
('MULLERIAN_INHIBITING_SUBSTANCE_AMH', 'Mullerian Inhibiting Substance (AMH)', 1680),
('MUMPS_IGG_ANTIBODY', 'Mumps IgG Antibody', 2040),
('MUMPS_IGM_ANTIBODY', 'Mumps IgM Antibody', 1632),
('MUSK_ANTIBODY_SERUM', 'Musk Antibody,Serum', 5304),
('MYCOBACTERIUM_TB_DNA_DETECTION', 'Mycobacterium TB DNA Detection', 1800),
('MYCOPLASMA_PNEUMONIAE_IGG_ANTIBODY', 'Mycoplasma Pneumoniae IgG Antibody', 2560),
('MYCOPLASMA_PNEUMONIAE_IGM_ANTIBODY', 'Mycoplasma Pneumoniae IgM Antibody', 2560),
('NASAL_SMEAR_FOR_EOSINOPHIL_COUNT', 'Nasal Smear for Eosinophil Count', 248),
('NATURAL_KILLER_CELLS_NKC_BLOOD', 'Natural Killer Cells (NKC), Blood', 4080),
('NEURONAL_ANTIBODY_PROFILE', 'Neuronal Antibody Profile', 8976),
('NIPT', 'NIPT', 32000),
('OCCULT_BLOOD_STOOL', 'Occult Blood, Stool', 120),
('OLIGOCLONAL_BAND_BY_IEF_CSF', 'Oligoclonal band By IEF, CSF', 4080),
('ORTHOPANTOMOGRAM_OPG', 'ORTHOPANTOMOGRAM (OPG)', 384),
('OSMOLALITY_SERUM', 'Osmolality, Serum', 656),
('OSMOLALITY_URINE', 'Osmolality, Urine', 656),
('OSMOTIC_FRAGILITY_TEST', 'Osmotic Fragility Test', 736),
('OVA_CYST_STOOL', 'Ova Cyst, Stool', 80),
('P_ANCA', 'P-ANCA', 1680),
('PAPP_A', 'PAPP - A', 1472),
('PARATHYROID_HORMONE_PTH', 'Parathyroid Hormone (PTH)', 1632),
('PERIPHERAL_SMEAR_FOR_ABNORMAL_CELLS', 'Peripheral Smear for Abnormal Cells', 240),
('PERIPHERAL_SMEAR_FOR_MALARIAL_PARASITES', 'Peripheral Smear For Malarial Parasites', 200),
('PERIPHERAL_SMEAR_STUDY', 'Peripheral Smear Study', 240),
('PHENYTOIN_EPTOIN', 'Phenytoin (Eptoin)', 1224),
('PHOSPHOLIPID_ANTIBODY_IGG', 'Phospholipid Antibody (IgG)', 984),
('PHOSPHOLIPID_ANTIBODY_IGM', 'Phospholipid Antibody (IgM)', 984),
('PHOSPHOROUS_24HRS_URINE', 'Phosphorous, 24Hrs Urine', 120),
('PHOSPHOROUS_SERUM', 'Phosphorous, Serum', 120),
('PHOSPHOROUS_URINE_SPOT', 'Phosphorous, Urine Spot', 120),
('PLATELET_COUNT', 'Platelet Count', 120),
('PNEUMOCYSTIS_CARINII_DETECTION_FLUID', 'Pneumocystis Carinii Detection, Fluid', 3264),
('PNH_CONFIRMATION_TEST_BLOOD', 'PNH- Confirmation test, Blood', 6528),
('PORPHOBILINOGEN_PBG_QUANTITATIVE_URINE_24_H', 'Porphobilinogen (PBG), Quantitative Urine 24 H', 3264),
('POST_PRANDIAL_BLOOD_SUGAR_PPBS', 'POST PRANDIAL BLOOD SUGAR (PPBS)', 40),
('POTASSIUM_URINE_SPOT', 'Potassium Urine Spot', 328),
('POTASSIUM_SERUM', 'Potassium, Serum', 120),
('POTASSIUM_URINE_24H', 'Potassium, Urine 24H', 408),
('POTASSIUM_CREATININE_RATIO_URINE_SPOT', 'Potassium/Creatinine ratio, Urine spot', 320),
('PREGNANCY_TEST_URINE', 'Pregnancy Test, Urine', 80),
('PROCALCITONIN_SERUM', 'Procalcitonin, Serum', 2768),
('PROGESTERONE', 'Progesterone', 720),
('PROLACTIN', 'Prolactin', 480),
('PROSTATE_SPECIFIC_ANTIGEN_FREE', 'Prostate Specific Antigen, Free', 800),
('PROSTATE_SPECIFIC_ANTIGEN_TOTAL_PSA', 'Prostate Specific Antigen, Total (PSA)', 720),
('PROTEIN_ELECTROPHORESIS', 'Protein Electrophoresis', 1280),
('PROTEIN_ELECTROPHORESIS_OLIGOCLONAL_BANDS_CSF', 'Protein Electrophoresis (Oligoclonal Bands), CSF', 4488),
('PROTEIN_ELECTROPHORESIS_SERUM', 'Protein Electrophoresis, Serum', 800),
('PROTEIN_TOTAL_WITH_ALBUMIN', 'Protein Total with Albumin', 240),
('PROTEIN_CREATININE_RATIO_URINE_24_HOURS', 'Protein/Creatinine ratio, Urine 24 Hours', 320),
('PROTEIN_CREATININE_RATIO_URINE_SPOT', 'Protein/Creatinine ratio, Urine Spot', 320),
('PROTEINS_TOTAL_SERUM', 'Proteins Total, Serum', 120),
('PROTEINS_URINE_24H', 'Proteins, Urine 24H', 320),
('PROTEINS_URINE_SPOT', 'Proteins, Urine Spot', 120),
('PROTHROMBIN_TIME_PT', 'Prothrombin Time (PT)', 360),
('PROTHROMBIN_TIME_WITH_INR', 'Prothrombin Time With INR', 240),
('QBC_FOR_MP', 'QBC for MP', 200),
('QUADRAPLE_MARKER', 'Quadraple marker', 2440),
('QUADRUPLE_MARKAR_GRAPH', 'Quadruple Markar Graph', 0),
('RAPID_MALARIA_TEST_PF', 'Rapid Malaria Test (PF)', 200),
('RED_BLOOD_CELLS_COUNT_RBC', 'Red Blood Cells Count (RBC)', 80),
('REDUCING_SUBSTANCES_STOOL', 'Reducing Substances, Stool', 80),
('RENAL_FUNCTION_TESTS', 'RENAL FUNCTION TESTS', 952),
('RETICULOCYTE_COUNT', 'Reticulocyte Count', 160),
('RHEUMATOID_FACTOR_RA_FACTOR', 'Rheumatoid Factor (RA Factor)', 384),
('RHEUMATOID_FACTOR_IGM_ANTIBODY', 'Rheumatoid Factor IgM, Antibody', 1312),
('RT_PCR_FOR_COVID_19', 'RT PCR FOR COVID 19', 800),
('RUBELLA_ANTIBODIES_IGG_IGM', 'Rubella Antibodies (IgG & IgM)', 1224),
('RUBELLA_IGG_ANTIBODY', 'Rubella IgG Antibody', 736),
('RUBELLA_IGM_ANTIBODY', 'Rubella IgM Antibody', 736),
('SAR2_COVID_19_IG_G_ANTIBODIES', 'SAR2 (COVID 19) IG G ANTIBODIES', 960),
('SARS_2_COVID19_ANTIBODIES_IG_G_IG_M_QUANTITATIVE', 'SARS 2 (COVID19) ANTIBODIES IG G, IG M QUANTITATIVE', 1280),
('SCRUB_TYPHUS_ANTIBODY', 'Scrub Typhus Antibody', 960),
('SECOND_OPINION_SLIDE', 'Second Opinion, Slide', 408),
('SELENIUM_SERUM', 'Selenium, Serum', 4080),
('SELENIUM_URINE', 'Selenium, Urine', 4080),
('SEMEN_ANALYSIS_CASA', 'Semen  Analysis (CASA)', 960),
('SEMEN_ANALYSIS', 'Semen Analysis', 240),
('SEMEN_ANALYSIS_CASA_METHOD', 'Semen Analysis (Casa Method)', 960),
('SEX_HORMONE_BINDING_GLOBULIN_SHBG', 'Sex Hormone Binding Globulin (SHBG)', 2040),
('SICKLE_CELL_TEST', 'Sickle Cell Test', 200),
('SMALL_BOWEL_ENEMA', 'Small Bowel Enema', 2000),
('SMEAR_OF_MICROFILARIA_DETECTION_BLOOD', 'Smear of Microfilaria Detection ,Blood', 200),
('SMITH_IGG_ANTIBODY', 'Smith IgG Antibody', 1800),
('SMOOTH_MUSCLE_ANTIBODY_ASMA', 'Smooth Muscle Antibody (ASMA)', 1312),
('SODIUM_SERUM', 'Sodium, Serum', 120),
('SODIUM_URINE_24H', 'Sodium, Urine 24H', 408),
('SODIUM_URINE_SPOT', 'Sodium, Urine Spot', 320),
('SOLUBLE_LIVER_ANTIGEN_SLA', 'Soluble Liver Antigen (SLA)', 2912),
('SONO_MAMMOGRAPHY', 'Sono Mammography', 1200),
('STOOL_ROUTINE_EXAMINATION', 'Stool Routine Examination', 80),
('STRESS_ECHOCARDIOGRAM', 'STRESS ECHOCARDIOGRAM', 3200),
('SURGICAL_PROFILE_1_PADMASRI_IVF', 'SURGICAL PROFILE 1 Padmasri Ivf', 1943),
('TB_PCR', 'TB -PCR', 1760),
('TB_QUANTIFERON', 'TB Quantiferon', 2944),
('TB_GOLD', 'TB-Gold', 2320),
('TESTOSTERONE_FREE', 'Testosterone, Free', 1440),
('TESTOSTERONE_TOTAL', 'Testosterone, Total', 736),
('THYROGLOBULIN_SERUM', 'Thyroglobulin,Serum', 1840),
('THYROID_ANTIBODIES_TG_TPO', 'Thyroid Antibodies (TG,TPO)', 2160),
('THYROID_PEROXIDASE_ANTIBODIES_TPO_MICROSOMAL', 'Thyroid Peroxidase Antibodies (TPO, Microsomal)', 960),
('THYROID_PROFILE_T3_T4_TSH', 'Thyroid Profile (T3,T4,TSH)', 400),
('THYROID_STIMULATING_HORMONE_TSH', 'Thyroid Stimulating Hormone (TSH)', 200),
('THYROXINE_FREE_F_T4', 'Thyroxine, Free (F-T4)', 280),
('THYROXINE_TOTAL_T4', 'Thyroxine, Total (T4)', 120),
('TISSUE_TRANSGLUTAMINASE_ANTIBODY_IGA_SERUM', 'Tissue Transglutaminase Antibody IgA, Serum', 2856),
('TISSUE_TRANSGLUTAMINASE_IGG_ANTIBODY', 'Tissue Transglutaminase IgG Antibody', 2856),
('TORCH_PROFILE_10', 'Torch Profile - 10', 2560),
('TORCH_PROFILE_4_IGM', 'Torch Profile - 4 IgM', 1632),
('TOTAL_IGE', 'Total IGE', 960),
('TOTAL_IRON_BINDING_CAPACITY_TIBC', 'Total Iron Binding Capacity (TIBC)', 408),
('TOTAL_LFT', 'TOTAL LFT', 600),
('TOXOPLASMA_IGG_ANTIBODY', 'Toxoplasma IgG Antibody', 736),
('TOXOPLASMA_IGM_ANTIBODY', 'Toxoplasma IgM Antibody', 560),
('TRANSFERRIN', 'Transferrin', 1040),
('TRANSFERRIN_SATURATION', 'Transferrin Saturation', 576),
('TREAD_MILL_TEST_TMT', 'Tread Mill Test (TMT)', 1280),
('TREPONEMA_PALLIDUM_HAEMAGGLUTINATION_ASSAY_TPHA', 'Treponema Pallidum Haemagglutination Assay (TPHA)', 800),
('TRIDOT', 'TRIDOT', 200),
('TRIGLYCERIDES', 'Triglycerides', 280),
('TRIIDOTHYRONINE_FREE_F_T3', 'Triidothyronine, Free (F-T3)', 280),
('TRIIDOTHYRONINE_TOTAL_T3', 'Triidothyronine, Total (T3)', 200),
('TRIPLE_MARKER', 'Triple Marker', 2448),
('TRIPLE_MARKER_GRAPH', 'Triple Marker Graph', 2320),
('TROPONIN_I', 'Troponin-I', 1200),
('TROPONIN_T', 'Troponin-T', 1200),
('TRUS_GUIDED_PROSTATE_BIOPSY', 'Trus Guided Prostate Biopsy', 5600),
('TSH_RECEPTOR_ANTIBODIES_LATS_TSI_SERUM', 'TSH Receptor Antibodies (LATS-TSI), Serum', 4080),
('TUBERCULIN_SKIN_TEST_MANTOUX', 'Tuberculin Skin Test (Mantoux)', 80),
('TYPHI_IGM_ANTIBODY', 'Typhi. IgM Antibody', 320),
('UREA_SERUM', 'Urea, Serum', 96),
('UREA_URINE_24H', 'Urea, Urine 24H', 320),
('URIC_ACID_SERUM', 'Uric Acid, Serum', 160),
('URINE_COTININE', 'Urine Cotinine', 400),
('URINE_ROUTINE', 'Urine Routine', 80),
('VALPROIC_ACID', 'Valproic Acid', 984),
('VANILLYL_MANDELIC_ACID_VMA_URINE_24H', 'Vanillyl Mandelic Acid (VMA), Urine 24H', 3120),
('VDRL_RPR_CSF', 'VDRL (RPR), CSF', 248),
('VDRL_RPR_SERUM', 'VDRL (RPR), Serum', 160),
('VITAMIN_A_RETINOL_SERUM', 'Vitamin -A (Retinol), Serum', 3672),
('VITAMIN_B1_THAIMINE_BLOOD', 'Vitamin B1 (Thaimine),Blood', 2856),
('VITAMIN_B12_CYANOCOBALAMINE_SERUM', 'Vitamin B12 (Cyanocobalamine),Serum', 800),
('VITAMIN_B2_RIBOFLAVIN_SERUM', 'Vitamin B2 (Riboflavin), Serum', 3264),
('VITAMIN_B6_PYRIDOXIN_SERUM', 'Vitamin B6 (Pyridoxin), Serum', 2856),
('VITAMIN_C_ASCORBIC_ACID', 'Vitamin C (Ascorbic Acid)', 3264),
('VITAMIN_E_TOCOPHEROL_SERUM', 'Vitamin E (Tocopherol), Serum', 3672),
('VITAMIN_K1', 'Vitamin K1', 4800),
('WEIL_FEILX_TEST', 'Weil Feilx Test', 1224),
('WESTERN_BLOT_TEST_FOR_HIV_1', 'Western Blot Test For HIV- 1', 2960),
('WIDAL_TEST_SLIDE_METHOD', 'Widal Test, Slide Method', 160),
('ZINC_SERUM', 'Zinc, Serum', 2640),
('ZINC_URINE_24H', 'Zinc, Urine 24H', 2056)
  ) AS v(code, name, price)
 WHERE NOT EXISTS (SELECT 1 FROM home_services hs WHERE hs.code = v.code);

-- Health packages a patient can pick on /packages, with their component
-- tests flattened out (nested package references like
-- "BASIC SCREENING (NON DIABETIC) + HBA1C" resolved to their own components)
-- so booking-time expansion in bookings.py can match each component against
-- home_services individually.
INSERT INTO health_packages (name, description, tests_included, price)
SELECT v.name, v.description, v.tests_included, v.price
  FROM (VALUES
('Basic Screening (Non Diabetic)', 'Home collection package: CBC, Glucose, Fasting (FBS), Uric Acid, Serum, Creatinine, Serum, TOTAL CHOLESTEROL, TOTAL BILIRUBIN, Thyroid Stimulating Hormone (TSH), Complete Urine Examination (CUE)', ARRAY['CBC','Glucose, Fasting (FBS)','Uric Acid, Serum','Creatinine, Serum','TOTAL CHOLESTEROL','TOTAL BILIRUBIN','Thyroid Stimulating Hormone (TSH)','Complete Urine Examination (CUE)']::TEXT[], 599),
('Basic Screening (Diabetic)', 'Home collection package: CBC, Glucose, Fasting (FBS), Uric Acid, Serum, Creatinine, Serum, TOTAL CHOLESTEROL, TOTAL BILIRUBIN, Thyroid Stimulating Hormone (TSH), Complete Urine Examination (CUE), Glycosylated Hb (HbA1C)', ARRAY['CBC','Glucose, Fasting (FBS)','Uric Acid, Serum','Creatinine, Serum','TOTAL CHOLESTEROL','TOTAL BILIRUBIN','Thyroid Stimulating Hormone (TSH)','Complete Urine Examination (CUE)','Glycosylated Hb (HbA1C)']::TEXT[], 799),
('Full Body Screening (Non Diabetic)', 'Home collection package: CBC, Glucose, Fasting (FBS), Uric Acid, Serum, Creatinine, Serum, Urea, Serum, LIPID PROFILE, Liver Function Test (LFT), Thyroid Stimulating Hormone (TSH), Complete Urine Examination (CUE)', ARRAY['CBC','Glucose, Fasting (FBS)','Uric Acid, Serum','Creatinine, Serum','Urea, Serum','LIPID PROFILE','Liver Function Test (LFT)','Thyroid Stimulating Hormone (TSH)','Complete Urine Examination (CUE)']::TEXT[], 1099),
('Full Body Screening (Diabetic)', 'Home collection package: CBC, Glucose, Fasting (FBS), Uric Acid, Serum, Creatinine, Serum, Urea, Serum, LIPID PROFILE, Liver Function Test (LFT), Thyroid Stimulating Hormone (TSH), Complete Urine Examination (CUE), Glycosylated Hb (HbA1C)', ARRAY['CBC','Glucose, Fasting (FBS)','Uric Acid, Serum','Creatinine, Serum','Urea, Serum','LIPID PROFILE','Liver Function Test (LFT)','Thyroid Stimulating Hormone (TSH)','Complete Urine Examination (CUE)','Glycosylated Hb (HbA1C)']::TEXT[], 1299),
('Anaemia Package', 'Home collection package: Complete Blood Picture (CBP), Erythrocyte Sedimentation Rate (ESR), Iron, Total Iron Binding Capacity (TIBC), Transferrin, % IRON SATURATION', ARRAY['Complete Blood Picture (CBP)','Erythrocyte Sedimentation Rate (ESR)','Iron','Total Iron Binding Capacity (TIBC)','Transferrin','% IRON SATURATION']::TEXT[], 1499),
('Cardiac Screening Package', 'Home collection package: CBC, Creatinine, Serum, Lipoprotein (A), Apolipoprotein -A1, Apolipoprotein -B, Ck-Mb', ARRAY['CBC','Creatinine, Serum','Lipoprotein (A)','Apolipoprotein -A1','Apolipoprotein -B','Ck-Mb']::TEXT[], 1099),
('Vitamin Package', 'Home collection package: Calcium, Serum, Vitamin B12 (Cyanocobalamine),Serum, 25 Hydroxy Vitamin D', ARRAY['Calcium, Serum','Vitamin B12 (Cyanocobalamine),Serum','25 Hydroxy Vitamin D']::TEXT[], 999),
('Hormone Package (Female)', 'Home collection package: Follicular Stimulating Hormone (FSH), Luteinizing Hormone (LH), TFT, Lipid profile, Uric Acid, Serum, Creatinine, Serum, Glucose, Fasting (FBS), Complete Blood Picture (CBP), 25 Hydroxy Vitamin D, Vitamin B12 (Cyanocobalamine),Serum', ARRAY['Follicular Stimulating Hormone (FSH)','Luteinizing Hormone (LH)','TFT','Lipid profile','Uric Acid, Serum','Creatinine, Serum','Glucose, Fasting (FBS)','Complete Blood Picture (CBP)','25 Hydroxy Vitamin D','Vitamin B12 (Cyanocobalamine),Serum']::TEXT[], 2500),
('PCOD Panel', 'Home collection package: Testosterone, Total, Prolactin, TFT, 17-OHP, DHEAS, Glucose, Fasting (FBS), Insulin - Fasting serum, C peptide', ARRAY['Testosterone, Total','Prolactin','TFT','17-OHP','DHEAS','Glucose, Fasting (FBS)','Insulin - Fasting serum','C peptide']::TEXT[], 3800),
('Hormone Package (Male)', 'Home collection package: Follicular Stimulating Hormone (FSH), Luteinizing Hormone (LH), Testosterone, Total, Lipid profile, Complete Blood Picture (CBP), TFT, Creatinine, Serum, Uric Acid, Serum, Glucose, Fasting (FBS), Prostate Specific Antigen, Total (PSA), 25 Hydroxy Vitamin D, Vitamin B12 (Cyanocobalamine),Serum', ARRAY['Follicular Stimulating Hormone (FSH)','Luteinizing Hormone (LH)','Testosterone, Total','Lipid profile','Complete Blood Picture (CBP)','TFT','Creatinine, Serum','Uric Acid, Serum','Glucose, Fasting (FBS)','Prostate Specific Antigen, Total (PSA)','25 Hydroxy Vitamin D','Vitamin B12 (Cyanocobalamine),Serum']::TEXT[], 3425),
('Senior Citizen Package (Male)', 'Home collection package: Complete Blood Picture (CBP), Erythrocyte Sedimentation Rate (ESR), Glucose, Fasting (FBS), POST PRANDIAL BLOOD SUGAR (PPBS), Creatinine, Serum, Uric Acid, Serum, Electrolytes, Serum, LIPID PROFILE, Liver Function Test (LFT), Prostate Specific Antigen, Total (PSA), Complete Urine Examination (CUE)', ARRAY['Complete Blood Picture (CBP)','Erythrocyte Sedimentation Rate (ESR)','Glucose, Fasting (FBS)','POST PRANDIAL BLOOD SUGAR (PPBS)','Creatinine, Serum','Uric Acid, Serum','Electrolytes, Serum','LIPID PROFILE','Liver Function Test (LFT)','Prostate Specific Antigen, Total (PSA)','Complete Urine Examination (CUE)']::TEXT[], 1799),
('Gastric (Hepatitis) Package', 'Home collection package: Hepatitis B surface Antigen (HBsAg), Hepatitis A Virus (HAV) IgM Antibody, Hepatitis C Virus (HCV) Antibody, Amylase, Serum, Lipase serum', ARRAY['Hepatitis B surface Antigen (HBsAg)','Hepatitis A Virus (HAV) IgM Antibody','Hepatitis C Virus (HCV) Antibody','Amylase, Serum','Lipase serum']::TEXT[], 1600),
('RFT/KFT', 'Home collection package: CBC, Creatinine, Serum, Urea, Serum, Blood Urea Nitrogen (BUN), Uric Acid, Serum, Calcium, Serum, Electrolytes, Serum', ARRAY['CBC','Creatinine, Serum','Urea, Serum','Blood Urea Nitrogen (BUN)','Uric Acid, Serum','Calcium, Serum','Electrolytes, Serum']::TEXT[], 799),
('Fever Profile - Basic', 'Home collection package: CBC, Erythrocyte Sedimentation Rate (ESR), QBC for MP, Widal Test, Slide Method, C-Reactive Proteins (CRP), Urine Routine', ARRAY['CBC','Erythrocyte Sedimentation Rate (ESR)','QBC for MP','Widal Test, Slide Method','C-Reactive Proteins (CRP)','Urine Routine']::TEXT[], 899),
('Fever Profile - Complete', 'Home collection package: CBC, Erythrocyte Sedimentation Rate (ESR), QBC for MP, Widal Test, Slide Method, Dengue Antigen NS1 (ELISA), C-Reactive Proteins (CRP), Urine Routine', ARRAY['CBC','Erythrocyte Sedimentation Rate (ESR)','QBC for MP','Widal Test, Slide Method','Dengue Antigen NS1 (ELISA)','C-Reactive Proteins (CRP)','Urine Routine']::TEXT[], 1300)
  ) AS v(name, description, tests_included, price)
 WHERE NOT EXISTS (SELECT 1 FROM health_packages hp WHERE hp.name = v.name);

-- ----------------------------------------------------------------------------
-- SECTION 2: POST-MIGRATION VALIDATION CHECK
-- ----------------------------------------------------------------------------
DO $$
DECLARE
    svc_count INT;
    pkg_count INT;
BEGIN
    SELECT COUNT(*) INTO svc_count FROM home_services;
    SELECT COUNT(*) INTO pkg_count FROM health_packages;
    IF svc_count < 400 THEN
        RAISE EXCEPTION 'POST-MIGRATION FAILURE: home_services has only % rows, expected 400+.', svc_count;
    END IF;
    IF pkg_count < 15 THEN
        RAISE EXCEPTION 'POST-MIGRATION FAILURE: health_packages has only % rows, expected 15+.', pkg_count;
    END IF;
END $$;

COMMIT;

INSERT INTO schema_migrations (filename, applied_by, notes)
VALUES ('task8_full_service_catalog.sql', current_user,
        'Seeded home_services with the full individual-test catalog and health_packages with the 15 public packages + component mapping')
ON CONFLICT (filename) DO NOTHING;

NOTIFY pgrst, 'reload schema';

-- ----------------------------------------------------------------------------
-- SECTION 3: ROLLBACK INSTRUCTIONS
-- Both inserts are name/code-guarded and additive only; rolling back means
-- deleting the rows this migration added (leaves the original 10
-- home_services rows from task1 untouched, since their codes predate this
-- migration and are not in the VALUES lists above).
-- BEGIN;
-- DELETE FROM health_packages WHERE name IN (
--     'Basic Screening (Non Diabetic)', 'Basic Screening (Diabetic)',
--     'Full Body Screening (Non Diabetic)', 'Full Body Screening (Diabetic)',
--     'Anaemia Package', 'Cardiac Screening Package', 'Vitamin Package',
--     'Hormone Package (Female)', 'PCOD Panel', 'Hormone Package (Male)',
--     'Senior Citizen Package (Male)', 'Gastric (Hepatitis) Package',
--     'RFT/KFT', 'Fever Profile - Basic', 'Fever Profile - Complete'
-- );
-- DELETE FROM booking_tests WHERE home_service_id IN (
--     SELECT id FROM home_services WHERE code NOT IN (
--         'CBC','LFT','KFT','LIPID','HBA1C','THYROID','VITD','VITB12','ESR','CRP'
--     )
-- );
-- DELETE FROM home_services WHERE code NOT IN (
--     'CBC','LFT','KFT','LIPID','HBA1C','THYROID','VITD','VITB12','ESR','CRP'
-- );
-- DELETE FROM schema_migrations WHERE filename = 'task8_full_service_catalog.sql';
-- COMMIT;
-- NOTIFY pgrst, 'reload schema';
-- ----------------------------------------------------------------------------
