export const FEATURE_FLAGS = {
  ENABLE_PREVENTIVE_BIOMARKERS: true,
  ENABLE_DOCTOR_BRIEFING: true,
  ENABLE_FAMILY_SWIPER: true,
  ENABLE_EMERGENCY_SOS: true,
  ENABLE_SMART_MEDICINE_CABINET: true,
  ENABLE_PHLEBO_RADAR: true,
} as const;
